# Load additional emails to email database

In [4]:
from google.cloud import secretmanager
import pandas as pd
from currensee.utils.db_utils import create_pg_engine
from sqlalchemy import text

In [5]:
from currensee.core.settings import Settings
settings = Settings()

In [6]:
import inspect
print(inspect.signature(create_pg_engine))

(db_name: str)

In [7]:
crm_outlook_engine = create_pg_engine('crm_outlook')

In [8]:
query= ''' select * from email_data where (to_emails = 'jessica.palmer@hasbro.com' or from_email = 'jessica.palmer@hasbro.com')'''
email_df = pd.read_sql(query, crm_outlook_engine)

In [9]:
email_df.head(20)

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2018-11-01 09:45:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - FX Risk Management for International ...,"Hi Jessica,\n\nFollowing up on our initial con..."
1,2018-11-02 14:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - FX Risk Management for Internatio...,"Hi Jane,\n\nThanks for the information. FX vol..."
2,2018-11-02 14:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - FX Risk Management for Internatio...,"Hi Jessica,\n\nAbsolutely. Discussing the trad..."
3,2019-11-18 14:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - FX Hedging Strategy - Forwards vs. Op...,"Hi Jessica,\n\nThanks for the productive discu..."
4,2019-11-20 10:30:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - FX Hedging Strategy - Forwards vs...,"Hi Jane,\n\nThis summary is exactly what we ne..."
5,2020-11-23 15:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Decision on H1 2021 FX Hedging,"Hi Jessica,\n\nHope you're well. Circling back..."
6,2020-11-25 10:10:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Decision on H1 2021 FX Hedging,"Hi Jane,\n\nThanks for the nudge. We've decide..."
7,2020-11-25 14:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Decision on H1 2021 FX Hedging,"Hi Jessica,\n\nUnderstood. I'll prepare the in..."
8,2021-12-01 14:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Execution of H1 2022 FX Hedges,"Hi Jessica,\n\nConfirming that we have execute..."
9,2021-12-02 09:45:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Execution of H1 2022 FX Hedges,"Hi Jane,\n\nExcellent, thanks for the prompt e..."
10,2022-12-06 09:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Review of H1 2022 FX Hedge Performance,"Hi Jessica,\n\nAs we approach the maturity of ..."
11,2022-12-07 11:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Review of H1 2022 FX Hedge Perfor...,"Hi Jane,\n\nThanks for sending the performance..."
12,2022-12-07 11:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Review of H1 2022 FX Hedge Perfor...,"Hi Jessica,\n\nCertainly. For early January, h..."
13,2023-11-21 15:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Strategy Discussion for H1 2024 FX He...,"Hi Jessica,\n\nFollowing up on our call earlie..."
14,2023-11-22 10:30:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Hi Jane,\n\nYes, let's connect. How about Dece..."
15,2023-11-22 10:45:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Hi Jessica,\n\nDecember 11th at 11 AM ET works..."
16,2023-12-12 10:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Hi Jessica,\n\nGreat to speak with you yesterd..."
17,2024-12-12 11:30:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Thanks Jane,\n\nI will follow up if I have any..."
18,2024-01-20 14:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica,\n\nI am reaching out regarding Has..."
19,2024-01-21 09:17:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Thanks Jane,\n\nThank you for the update. Seem..."

In [21]:
create = text("""
CREATE TABLE email_data2 AS
SELECT * FROM email_data;
""")
with crm_outlook_engine.connect() as connection:
    connection.execute(create)
    connection.commit()

In [22]:
query= ''' select * from email_data2 '''
email_df2 = pd.read_sql(query, crm_outlook_engine)

In [23]:
email_df2.head()

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2018-07-15 09:30:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Introduction - Bankwell Financial Services for...,"Hi Cynthia,\n\nMy name is Jane Moneypenny, and..."
1,2018-07-16 11:05:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: Introduction - Bankwell Financial Services...,"Hi Jane,\n\nThank you for reaching out. AbbVie..."
2,2018-07-16 11:15:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Introduction - Bankwell Financial Services...,"Hi Cynthia,\n\nTuesday at 2 PM CT works perfec..."
3,2018-08-01 14:00:00,Jennifer Phelps,jennifer.phelps@aerovironment.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Follow Up: AeroVironment Financial Needs,"Hi Jennifer,\n\nIt was a pleasure speaking wit..."
4,2018-08-02 10:15:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jennifer Phelps,jennifer.phelps@aerovironment.com,Re: Follow Up: AeroVironment Financial Needs,"Hi Jane,\n\nThanks for sending this over. The ..."

In [27]:
df_append = pd.read_excel("append_emails_hasboro.xlsx")

In [28]:
df_append.head()

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2023-12-12 10:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Hi Jessica,\n\nGreat to speak with you yesterd..."
1,2024-12-12 11:30:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Thanks Jane,\n\nI will follow up if I have any..."
2,2024-01-20 14:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica,\n\nI am reaching out regarding Has..."
3,2024-01-21 09:17:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Thanks Jane,\n\nThank you for the update. Seem..."
4,2024-01-24 13:43:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica,\n\n Those are great questions. I w..."

In [29]:
df_append.to_sql(
    name="email_data2", 
    con=crm_outlook_engine, 
    if_exists="append",  # append rows to existing table
    index=False          # do not write DataFrame index as a column
)

7

In [33]:
query= ''' select * from email_data2 where (to_emails = 'jessica.palmer@hasbro.com' or from_email = 'jessica.palmer@hasbro.com')'''
email_df2 = pd.read_sql(query, crm_outlook_engine)
email_df2.head(30)

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2018-11-01 09:45:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - FX Risk Management for International ...,"Hi Jessica,\n\nFollowing up on our initial con..."
1,2018-11-02 14:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - FX Risk Management for Internatio...,"Hi Jane,\n\nThanks for the information. FX vol..."
2,2018-11-02 14:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - FX Risk Management for Internatio...,"Hi Jessica,\n\nAbsolutely. Discussing the trad..."
3,2019-11-18 14:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - FX Hedging Strategy - Forwards vs. Op...,"Hi Jessica,\n\nThanks for the productive discu..."
4,2019-11-20 10:30:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - FX Hedging Strategy - Forwards vs...,"Hi Jane,\n\nThis summary is exactly what we ne..."
5,2020-11-23 15:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Decision on H1 2021 FX Hedging,"Hi Jessica,\n\nHope you're well. Circling back..."
6,2020-11-25 10:10:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Decision on H1 2021 FX Hedging,"Hi Jane,\n\nThanks for the nudge. We've decide..."
7,2020-11-25 14:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Decision on H1 2021 FX Hedging,"Hi Jessica,\n\nUnderstood. I'll prepare the in..."
8,2021-12-01 14:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Execution of H1 2022 FX Hedges,"Hi Jessica,\n\nConfirming that we have execute..."
9,2021-12-02 09:45:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Execution of H1 2022 FX Hedges,"Hi Jane,\n\nExcellent, thanks for the prompt e..."
10,2022-12-06 09:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Review of H1 2022 FX Hedge Performance,"Hi Jessica,\n\nAs we approach the maturity of ..."
11,2022-12-07 11:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Review of H1 2022 FX Hedge Perfor...,"Hi Jane,\n\nThanks for sending the performance..."
12,2022-12-07 11:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Review of H1 2022 FX Hedge Perfor...,"Hi Jessica,\n\nCertainly. For early January, h..."
13,2023-11-21 15:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Strategy Discussion for H1 2024 FX He...,"Hi Jessica,\n\nFollowing up on our call earlie..."
14,2023-11-22 10:30:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Hi Jane,\n\nYes, let's connect. How about Dece..."
15,2023-11-22 10:45:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Hi Jessica,\n\nDecember 11th at 11 AM ET works..."
16,2023-12-12 10:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Hi Jessica,\n\nGreat to speak with you yesterd..."
17,2024-12-12 11:30:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Thanks Jane,\n\nI will follow up if I have any..."
18,2024-01-20 14:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica,\n\nI am reaching out regarding Has..."
19,2024-01-21 09:17:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Thanks Jane,\n\nThank you for the update. Seem..."
20,2024-01-24 13:43:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica,\n\n Those are great questions. I w..."
21,2024-01-24 16:10:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi jane,\n\nYes, this needs further thought. I..."
22,2024-01-24 13:43:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica,\n\n Great, I will schedule us for ..."

# Append one extra meeting for jane and jessica

In [34]:
create = text("""
CREATE TABLE meeting_data2 AS
SELECT * FROM meeting_data;
""")

with crm_outlook_engine.connect() as connection:
    connection.execute(create)
    connection.commit()

In [35]:
query= ''' select * from meeting_data2 where invitee_emails = 'jessica.palmer@hasbro.com' '''
meeting_df = pd.read_sql(query, crm_outlook_engine)
meeting_df.head(30)

,meeting_timestamp,host,host_email,invitees,invitee_emails,meeting_subject
0,2018-11-14 11:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss FX Risk Management Strategies...
1,2023-01-10 10:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss H1 2023 FX Hedging Strategy
2,2023-12-11 11:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Finalize H1 2024 FX Hedging Strategy
3,2024-01-30 10:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Review H1 2024 FX Hedge Execution Plan

In [39]:
update= '''UPDATE meeting_data2
SET meeting_subject = 'Hasbro - Discuss Portfolio Diversification and Bond Strategy'
WHERE meeting_timestamp = '2024-01-30 10:00:00'
  AND invitee_emails = 'jessica.palmer@hasbro.com'
  '''

with crm_outlook_engine.connect() as connection:
    connection.execute(text(update))
    connection.commit()

In [41]:
update= '''UPDATE meeting_data2
SET meeting_timestamp = '2024-02-04 14:30:00'
WHERE meeting_timestamp = '2024-01-30 10:00:00'
  AND invitee_emails = 'jessica.palmer@hasbro.com'
  '''

with crm_outlook_engine.connect() as connection:
    connection.execute(text(update))
    connection.commit()

In [42]:
query= ''' select * from meeting_data2 where invitee_emails = 'jessica.palmer@hasbro.com' '''
meeting_df2 = pd.read_sql(query, crm_outlook_engine)
meeting_df2.head(30)

,meeting_timestamp,host,host_email,invitees,invitee_emails,meeting_subject
0,2018-11-14 11:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss FX Risk Management Strategies...
1,2023-01-10 10:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss H1 2023 FX Hedging Strategy
2,2023-12-11 11:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Finalize H1 2024 FX Hedging Strategy
3,2024-02-04 14:30:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss Portfolio Diversification and...

# Append to real tables

In [43]:
df_append = pd.read_excel("append_emails_hasboro.xlsx")

In [44]:
df_append.to_sql(
    name="email_data", 
    con=crm_outlook_engine, 
    if_exists="append",  # append rows to existing table
    index=False          # do not write DataFrame index as a column
)

7

In [45]:
query= ''' select * from email_data where (to_emails = 'jessica.palmer@hasbro.com' or from_email = 'jessica.palmer@hasbro.com')'''
email_df = pd.read_sql(query, crm_outlook_engine)
email_df.head(30)

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2018-11-01 09:45:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - FX Risk Management for International ...,"Hi Jessica,\n\nFollowing up on our initial con..."
1,2018-11-02 14:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - FX Risk Management for Internatio...,"Hi Jane,\n\nThanks for the information. FX vol..."
2,2018-11-02 14:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - FX Risk Management for Internatio...,"Hi Jessica,\n\nAbsolutely. Discussing the trad..."
3,2019-11-18 14:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - FX Hedging Strategy - Forwards vs. Op...,"Hi Jessica,\n\nThanks for the productive discu..."
4,2019-11-20 10:30:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - FX Hedging Strategy - Forwards vs...,"Hi Jane,\n\nThis summary is exactly what we ne..."
5,2020-11-23 15:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Decision on H1 2021 FX Hedging,"Hi Jessica,\n\nHope you're well. Circling back..."
6,2020-11-25 10:10:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Decision on H1 2021 FX Hedging,"Hi Jane,\n\nThanks for the nudge. We've decide..."
7,2020-11-25 14:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Decision on H1 2021 FX Hedging,"Hi Jessica,\n\nUnderstood. I'll prepare the in..."
8,2021-12-01 14:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Execution of H1 2022 FX Hedges,"Hi Jessica,\n\nConfirming that we have execute..."
9,2021-12-02 09:45:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Execution of H1 2022 FX Hedges,"Hi Jane,\n\nExcellent, thanks for the prompt e..."
10,2022-12-06 09:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Review of H1 2022 FX Hedge Performance,"Hi Jessica,\n\nAs we approach the maturity of ..."
11,2022-12-07 11:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Review of H1 2022 FX Hedge Perfor...,"Hi Jane,\n\nThanks for sending the performance..."
12,2022-12-07 11:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Review of H1 2022 FX Hedge Perfor...,"Hi Jessica,\n\nCertainly. For early January, h..."
13,2023-11-21 15:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Strategy Discussion for H1 2024 FX He...,"Hi Jessica,\n\nFollowing up on our call earlie..."
14,2023-11-22 10:30:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Hi Jane,\n\nYes, let's connect. How about Dece..."
15,2023-11-22 10:45:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Hi Jessica,\n\nDecember 11th at 11 AM ET works..."
16,2023-12-12 10:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Hi Jessica,\n\nGreat to speak with you yesterd..."
17,2024-12-12 11:30:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Thanks Jane,\n\nI will follow up if I have any..."
18,2024-01-20 14:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica,\n\nI am reaching out regarding Has..."
19,2024-01-21 09:17:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Thanks Jane,\n\nThank you for the update. Seem..."
20,2024-01-24 13:43:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica,\n\n Those are great questions. I w..."
21,2024-01-24 16:10:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi jane,\n\nYes, this needs further thought. I..."
22,2024-01-24 13:43:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica,\n\n Great, I will schedule us for ..."

In [46]:
query= ''' select * from meeting_data where invitee_emails = 'jessica.palmer@hasbro.com' '''
meeting_df = pd.read_sql(query, crm_outlook_engine)
meeting_df.head(30)

,meeting_timestamp,host,host_email,invitees,invitee_emails,meeting_subject
0,2018-11-14 11:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss FX Risk Management Strategies...
1,2023-01-10 10:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss H1 2023 FX Hedging Strategy
2,2023-12-11 11:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Finalize H1 2024 FX Hedging Strategy
3,2024-01-30 10:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Review H1 2024 FX Hedge Execution Plan

In [47]:
update= '''UPDATE meeting_data
SET meeting_subject = 'Hasbro - Discuss Portfolio Diversification and Bond Strategy'
WHERE meeting_timestamp = '2024-01-30 10:00:00'
  AND invitee_emails = 'jessica.palmer@hasbro.com'
  '''

with crm_outlook_engine.connect() as connection:
    connection.execute(text(update))
    connection.commit()

In [48]:
update= '''UPDATE meeting_data
SET meeting_timestamp = '2024-02-04 14:30:00'
WHERE meeting_timestamp = '2024-01-30 10:00:00'
  AND invitee_emails = 'jessica.palmer@hasbro.com'
  '''

with crm_outlook_engine.connect() as connection:
    connection.execute(text(update))
    connection.commit()

In [49]:
query= ''' select * from meeting_data where invitee_emails = 'jessica.palmer@hasbro.com' '''
meeting_df2 = pd.read_sql(query, crm_outlook_engine)
meeting_df2.head(30)

,meeting_timestamp,host,host_email,invitees,invitee_emails,meeting_subject
0,2018-11-14 11:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss FX Risk Management Strategies...
1,2023-01-10 10:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss H1 2023 FX Hedging Strategy
2,2023-12-11 11:00:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Finalize H1 2024 FX Hedging Strategy
3,2024-02-04 14:30:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss Portfolio Diversification and...

# fix error in email date

In [20]:
update= '''UPDATE email_data
SET email_timestamp = '2023-12-12 11:30:00'
WHERE email_timestamp = '2024-12-12 11:30:00'
  AND from_email= 'jessica.palmer@hasbro.com'
  '''

with crm_outlook_engine.connect() as connection:
    connection.execute(text(update))
    connection.commit()

In [21]:
query= ''' select * from email_data where (to_emails = 'jessica.palmer@hasbro.com' or from_email = 'jessica.palmer@hasbro.com') order by email_timestamp desc'''
email_df = pd.read_sql(query, crm_outlook_engine)
email_df.head(10)

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2024-01-24 16:10:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi jane,\n\nYes, this needs further thought. I..."
1,2024-01-24 13:43:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica,\n\n Great, I will schedule us for ..."
2,2024-01-24 13:43:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica,\n\n Those are great questions. I w..."
3,2024-01-21 09:17:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Thanks Jane,\n\nThank you for the update. Seem..."
4,2024-01-20 14:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica,\n\nI am reaching out regarding Has..."
5,2023-12-12 11:30:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Thanks Jane,\n\nI will follow up if I have any..."
6,2023-12-12 10:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Hi Jessica,\n\nGreat to speak with you yesterd..."
7,2023-11-22 10:45:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Hi Jessica,\n\nDecember 11th at 11 AM ET works..."
8,2023-11-22 10:30:00,Jane Moneypenny,jane.moneypenny1@outlook.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Hi Jane,\n\nYes, let's connect. How about Dece..."
9,2023-11-21 15:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny1@outlook.com,Hasbro - Strategy Discussion for H1 2024 FX He...,"Hi Jessica,\n\nFollowing up on our call earlie..."