# Sample CloudSql Connection

# Need to set up for each instance - Add your VM's IP to the Authorized Networks
**1. Find the external IP of your JupyterLab VM**
https://console.cloud.google.com/compute/instances?project=adsp-34002-on02-sopho-scribe&authuser=1
 * Go to VM Instances
 * Find your JupyterLab VM
 * Copy the External IP address (looks like 34.91.100.45).

**2. Add the VM's IP to your Cloud SQL authorized networks**
https://console.cloud.google.com/sql/instances/currensee-sql/connections/networking?authuser=1&project=adsp-34002-on02-sopho-scribe
* Go to Cloud SQL instances. 
* Click your instance.
* Click Connections in the left sidebar.
* Scroll to Authorized networks → Add network.
* Name: anything like jupyterlab-vm
* Network: paste the external IP you just copied (e.g., 34.91.100.45/32)
* IMPORTANT: Add /32 to allow only that single IP.
* Click Save.

It will take ~30 seconds to update.

In [1]:
#%poetry add -q google-cloud-secret-manager==2.23.3
#%poetry add -q SQLAlchemy==2.0.40

In [2]:
#%poetry add psycopg2-binary sqlalchemy pandas

In [3]:
from google.cloud import secretmanager
import pandas as pd
import numpy as np
from currensee.utils.db_utils import create_pg_engine
from sqlalchemy import text

## IMPORTANT
The cell below will only work if you have a .env file defined at `<fl>_currensee/currensee/.env` with the credentials 
defined in `<fl>_currensee/currensee/.env.example`.

Instructions are located within the `.env.example` file with how to fill out the credentials properly.

#### Create SQLAlchemy engine

In [4]:
# Define DB_NAME
DB_NAME = 'crm'

In [5]:
engine = create_pg_engine(
   db_name=DB_NAME
)

In [6]:
df_result = pd.read_sql("SELECT * FROM Employees limit 10", con=engine)
print(df_result)

                            employee_id   first_name   last_name  \
0  31e735f6-cfbe-4107-8aba-4ef45a90e9ae         Jane  Moneypenny
1  612cbf16-0d9f-4638-b2df-d32c7d2029f0        Nancy       Hines
2  64fc5ec2-22ba-453e-8f98-fa486e702f8b    Stephanie      Taylor
3  ed0a92ef-d388-47da-a3ee-1176b3fbfe67      Jessica       Adams
4  53e47076-23f5-4e89-b3e9-6a9a516f73e1         John        Rose
5  2b2ef83b-6f59-4813-8b9b-af778ae87382  Christopher      Snyder
6  fe927078-9d29-4df0-a9b7-80e4c1e26791    Christian   Schneider
7  8b2fe421-4e9e-4b47-b327-8d3c1eada218       Sharon    Mcdonald
8  5421d73a-c146-455d-940f-dba058b74a16       Travis      Howell
9  f5a04294-4119-4b5f-a569-e288c319bec0       Justin    Townsend

                         title                             email  \
0         Relationship Manager     jane.moneypenny1@bankwell.com
1            Finance Assistant          nancy.hines@bankwell.com
2  Senior Relationship Manager     stephanie.taylor@bankwell.com
3            Finance Assistant        jessica.adams@bankwell.com
4         Relationship Manager            john.rose@bankwell.com
5            Financial Advisor   christopher.snyder@bankwell.com
6  Senior Relationship Manager  christian.schneider@bankwell.com
7  Senior Relationship Manager      sharon.mcdonald@bankwell.com
8           Product Specialist        travis.howell@bankwell.com
9            Financial Advisor      justin.townsend@bankwell.com

                   phone   hire_date                 department         market
0     971.841.4711x92417  2021-01-14      Enterprise Investment  San Fransisco
1   001-530-612-9635x682  2022-01-18      Enterprise Investment         Dallas
2      (820)807-5217x939  2022-05-21                      Sales  New York City
3          (376)246-4329  2024-04-28  Small Business Investment    Los Angeles
4    +1-491-830-9686x792  2025-01-25                      Sales         Denver
5  001-368-721-5024x7507  2021-05-08           Customer Support          Miami
6           333.201.3164  2021-06-30                      Sales         Dallas
7        +1-783-380-7619  2023-07-05  Small Business Investment        Chicago
8       740.544.1092x854  2024-09-20  Small Business Investment         Boston
9           820-931-2507  2022-03-19                      Sales          Miami

# Generate Fake Data

In [7]:
# %poetry add faker

In [8]:
import pandas as pd
import random
import os
import re
from faker import Faker

# Initialize Faker instance
#Faker is a Python package that integrates fake data for you.

#Some hard coded data of publicly traded companies to be our mock clients

In [9]:

fake = Faker()

# Helper function to generate synthetic employee data
def generate_employee_data(num_employees=10, ourcompany_name = 'bankwell'):
    company = ourcompany_name
    employees = [
        {
            'employee_id': '31e735f6-cfbe-4107-8aba-4ef45a90e9ae',
            'first_name': "Jane",
            'last_name': "Moneypenny",
            'title': "Relationship Manager",
            'email': "jane.moneypenny1@bankwell.com",
            'phone': "971.841.4711x92417",
            'hire_date': '2021-01-14',
            'department': 'Enterprise Investment',
            'market': 'San Fransisco'
        }
    ]

    for _ in range(num_employees-1):
        employee_id = fake.unique.uuid4()
        first_name = fake.first_name()
        last_name = fake.last_name()
        title = random.choice(['Finance Assistant', 'Financial Advisor', 'Senior Relationship Manager', 'Product Specialist', 'Relationship Manager'])
        phone = fake.phone_number()
        department = random.choice(['Enterprise Investment', 'Small Business Investment', 'Operations', 'Sales', 'Customer Support'])
        hire_date = fake.date_this_decade()
        market = random.choice(['San Fransisco', 'New York City', 'Boston', 'Denver', 'Los Angeles', 'Miami', 'Washington DC', 'Seattle', 'Dallas', 'Chicago'])
        company_clean = re.sub(r'\W+', '', company).lower()
        email = f"{first_name.lower()}.{last_name.lower()}@{company_clean}.com"


        employees.append({
            'employee_id': employee_id,
            'first_name': first_name,
            'last_name': last_name,
            'title': title,
            'email': email,
            'phone': phone,
            'hire_date': hire_date,
            'department': department,
            'market': market
        })
    return pd.DataFrame(employees)

# Helper function to generate point of contact and info for a Company
def generate_point_of_contact(company_name):
    account_id = fake.unique.uuid4()
    first_name = fake.first_name()
    last_name = fake.last_name()
    contact_title = random.choice(["Senior Director", "Manager", "Director", "VP", "Consultant"])
    phone = fake.phone_number()
    Website = fake.url()
    Location = random.choice(['San Fransisco', 'New York City', 'Boston', 'Denver', 'Los Angeles', 'Miami', 'Washington DC', 'Seattle', 'Dallas', 'Chicago'])
    AnnualRevenue = random.randint(1000000, 50000000)
    TotalAccountBal = random.randint(1000000, 50000000)

    # Clean Company name for use in email
    company_clean = re.sub(r'\W+', '', company_name).lower()
    email = f"{first_name.lower()}.{last_name.lower()}@{company_clean}.com"

    return {
        "account_id": account_id,
        "contact_first_name": first_name,
        "contact_last_name": last_name,
        "contact_title": contact_title,
        "phone": phone,
        "email": email,
        "website": Website,
        "location": Location,
        "annual_revenue": AnnualRevenue,
        "total_account_bal": TotalAccountBal
    }


def generate_account_data(num_accounts=5, clients_company = []):
# Build the data
    # Hi Jing - add code here. Love, Lily
    accounts = [
        { "company": 'Mariott',
         "industry": 'Hospitality',
        "account_id": 'd02ccad1-26c4-4768-95a4-833dbc2b2460',
        "contact_first_name": 'Mary',
        "contact_last_name": 'Vasquez',
        "contact_title": 'Senior Director',
        "phone": '520-618-5303x572',
        "email": 'mary.vasquez@mariott.com',
        "website": 'mariott.com',
        "location": 'New York City',
        "annual_revenue": 43000000,
        "total_account_bal": 30000000
        }
    ]
    for company in clients_company:
        contact = generate_point_of_contact(company["company"])
        record = {
          "company": company["company"],
          "industry": company["industry"],
          **contact
      }
        accounts.append(record)
    return pd.DataFrame(accounts)




# Helper function to generate synthetic opportunity data
def generate_opportunity_data(accounts_df, num_opportunities_per_account=3):
    opportunities = []
    for _, account in accounts_df.iterrows():
        num_opportunities = random.randint(1, num_opportunities_per_account)
        for _ in range(num_opportunities):
            opportunities.append({
                'opportunity_id': fake.unique.uuid4(),
                'account_id': account['account_id'],
                'opportunity_name': fake.bs(),
                'stage': random.choice(['Prospecting', 'Qualification', 'Proposal', 'Negotiation', 'Won', 'Lost', 'Closed']),
                'type': random.choice(['New Business', 'Existing Business', 'Renewal', 'Upsell']),
                'close_date': fake.date_this_year(),
                'amount': random.randint(50000, 500000),
            })
    return pd.DataFrame(opportunities)

# Helper function to generate synthetic employee-contact relationship data
def generate_employee_contact_data(employees_df, accounts_df, num_relationships_per_employee=2):
    # Jing hard code here too.
    relationships = [
       { 'employee_id': '31e735f6-cfbe-4107-8aba-4ef45a90e9ae',
        'employee_first_name': 'Jane',
        'employee_last_name': 'Moneypenny',
        'account_id': 'd02ccad1-26c4-4768-95a4-833dbc2b2460',
        'company': 'Mariott',
        'industry': 'Hospitality',
        'contact_first_name': 'Mary',
        'contact_last_name': 'Vasquez',
        'contact_email': 'mary.vasquez@mariott.com',
        'contact_title': 'Senior Director',
        'contact_phone': '520-618-5303x572'}        
    ]

    employee_nj = employees_df[employees_df['last_name'] != 'Moneypenny']
    for _, employee in employee_nj.iterrows():
        num_relationships = random.randint(1, num_relationships_per_employee)
        for _ in range(num_relationships):
            account = random.choice(accounts_df['account_id'].tolist())
            relationships.append({
                'employee_id': employee['employee_id'],
                'employee_first_name': employee['first_name'],
                'employee_last_name': employee['last_name'],
                'account_id': account,
                'company': accounts_df.loc[accounts_df['account_id'] == account, 'company'].iloc[0],
                'industry': accounts_df.loc[accounts_df['account_id'] == account, 'industry'].iloc[0],
                'contact_first_name': accounts_df.loc[accounts_df['account_id'] == account, 'contact_first_name'].iloc[0],
                'contact_last_name': accounts_df.loc[accounts_df['account_id'] == account, 'contact_last_name'].iloc[0],
                'contact_email': accounts_df.loc[accounts_df['account_id'] == account, 'email'].iloc[0],
                'contact_title': accounts_df.loc[accounts_df['account_id'] == account, 'contact_title'].iloc[0],
                'contact_phone': accounts_df.loc[accounts_df['account_id'] == account, 'phone'].iloc[0],
            })
    return pd.DataFrame(relationships)



def generate_portfolios(df_accounts, max_positions=9, instruments=[]):
    portfolio_records = []

    for _, row in df_accounts.iterrows():
        account_id = row["account_id"]
        company = row["company"]
        total_account_bal = row["total_account_bal"]

        num_positions = random.randint(2, 5)
        positions = random.sample(instruments, num_positions)

        # Generate random proportions that sum to 1
        random_weights = np.random.rand(num_positions)
        random_weights /= random_weights.sum()

        for (symbol, instrument_type), weight in zip(positions, random_weights):
            fund_balance = round(total_account_bal * weight, 2)
            portfolio_records.append({
                "account_id": account_id,
                "company": company,
                "symbol": symbol,
                "fund_type": instrument_type,
                "tot_balance": total_account_bal,
                "fund_balance": fund_balance
            })

    return pd.DataFrame(portfolio_records)

In [10]:
# Right now companies can only be selected from this list of publicly traded companies 
# Likely want this to be random instead..
clients_company_info = [
        {"company": "Broadcom", "industry": "Technology"},
        {"company": "Cisco", "industry": "Technology"},
        {"company": "Palantir Technologies", "industry": "Technology"},
        {"company": "Fiserv", "industry": "Technology"},
        {"company": "Atlassian", "industry": "Technology"},
        {"company": "Leidos", "industry": "Technology"},
        {"company": "Duolingo", "industry": "Technology"},
        {"company": "Logitech", "industry": "Technology"},
        {"company": "Celestica", "industry": "Technology"},
        {"company": "Dropbox", "industry": "Technology"},
        {"company": "Plexus", "industry": "Technology"},
        {"company": "Silicon Laboratories", "industry": "Technology"},
        {"company": "Mobix Labs", "industry": "Technology"},
        {"company": "InterContinental Hotels Group", "industry": "Hospitality"},
        {"company": "Sonder Holdings", "industry": "Hospitality"},
        {"company": "Hyatt Hotels", "industry": "Hospitality"},
        {"company": "Royal Caribbean Cruises", "industry": "Hospitality"},
        {"company": "UnitedHealth", "industry": "Healthcare"},
        {"company": "Johnson & Johnson", "industry": "Healthcare"},
        {"company": "AbbVie", "industry": "Healthcare"},
        {"company": "Novo Nordisk", "industry": "Healthcare"},
        {"company": "Abbott Laboratories", "industry": "Healthcare"},
        {"company": "AstraZeneca", "industry": "Healthcare"},
        {"company": "Merck & Co", "industry": "Healthcare"},
        {"company": "Intuitive Surgical", "industry": "Healthcare"},
        {"company": "Medtronic", "industry": "Healthcare"},
        {"company": "Zoetis", "industry": "Healthcare"},
        {"company": "Humana", "industry": "Healthcare"},
        {"company": "Illumina", "industry": "Healthcare"},
        {"company": "Guardant Health", "industry": "Healthcare"},
        {"company": "Rhythm Pharmaceuticals", "industry": "Healthcare"},
        {"company": "Amedisys", "industry": "Healthcare"},
        {"company": "Rivian Automotive", "industry": "Automotive"},
        {"company": "Fordy", "industry": "Automotive"},
        {"company": "lululemon athletica", "industry": "Retail"},
        {"company": "DICK'S Sporting Goods", "industry": "Retail"},
        {"company": "GameStop Corp", "industry": "Retail"},
        {"company": "Texas Roadhouse", "industry": "Retail"},
        {"company": "Hasbro", "industry": "Retail"},
        {"company": "Mattel", "industry": "Retail"},
        {"company": "Wayfair", "industry": "Retail"},
        {"company": "Peloton", "industry": "Retail"},
        {"company": "Sally Beauty", "industry": "Retail"},
        {"company": "Lifetime Brand", "industry": "Retail"},
        {"company": "Allbirds", "industry": "Retail"},
        {"company": "Walmart", "industry": "Retail"},
        {"company": "Tyson Foods", "industry": "Retail"},
        {"company": "Sprouts Farmers Market", "industry": "Retail"},
        {"company": "Dollar Tree", "industry": "Retail"},
        {"company": "Stride", "industry": "Retail"},
        {"company": "Spectrum Brands", "industry": "Retail"},
        {"company": "Udemy", "industry": "Retail"},
        {"company": "Vital Farms", "industry": "Retail"},
        {"company": "Graham Holdings Company", "industry": "Retail"},
        {"company": "Hims & Hers Health", "industry": "Retail"},
        {"company": "Smithfield Foods", "industry": "Retail"},
        {"company": "Albertsons Companies", "industry": "Retail"},
        {"company": "Albany International", "industry": "Manufacturing"},
        {"company": "IT Tech Packaging", "industry": "Manufacturing"},
        {"company": "Lockheed Martin Corporation", "industry": "Manufacturing"},
        {"company": "Landstar System", "industry": "Manufacturing"},
        {"company": "Hexcel Corporation", "industry": "Manufacturing"},
        {"company": "AeroVironment", "industry": "Manufacturing"},
        {"company": "Matson", "industry": "Manufacturing"},
        {"company": "McGrath RentCorp", "industry": "Manufacturing"},
        {"company": "Mueller Industries", "industry": "Manufacturing"},
        {"company": "Dolby Laboratories", "industry": "Manufacturing"},
        {"company": "ManpowerGroup", "industry": "Manufacturing"},
        {"company": "Welltower", "industry": "RealEstate"},
        {"company": "Iron Mountain Incorporated", "industry": "RealEstate"},
        {"company": "Camden Property", "industry": "RealEstate"},
        {"company": "CubeSmart", "industry": "RealEstate"},
        {"company": "Federal Realty Investment Trust", "industry": "RealEstate"},
        {"company": "Essential Properties Realty", "industry": "RealEstate"},
        {"company": "Compass", "industry": "RealEstate"},
        {"company": "Medical Properties Trust", "industry": "RealEstate"},
        {"company": "Broadstone", "industry": "RealEstate"},
        {"company": "Ladder Capital Corp", "industry": "RealEstate"},
        {"company": "Peakstone Realty Trus", "industry": "RealEstate"},
        {"company": "Fathom Holdings", "industry": "RealEstate"},
        {"company": "Presidio Property Trust", "industry": "RealEstate"},
        {"company": "Service Properties Trust", "industry": "RealEstate"},
    ]


Bond_funds = ['BND', 'MUB', 'MBB', 'VCSH', 'TLT']
Equity_funds = ['VSMPX', 'FXAIX', 'FCNTX', 'FTIEX']
# All symbols with types
instruments = (
    [(sym, 'Bond Fund') for sym in Bond_funds ] +
    [(sym, 'Equity Fund') for sym in Equity_funds]
)

fund_dtl_df = pd.read_excel('equity_fund_example.xlsx')
# Generate synthetic data for the tables
employees_df = generate_employee_data(num_employees=100, ourcompany_name = 'bankwell')
accounts_df = generate_account_data(num_accounts=1000, clients_company = clients_company_info)
opportunities_df = generate_opportunity_data(accounts_df, num_opportunities_per_account=3)
contacts_df = generate_employee_contact_data(employees_df, accounts_df, num_relationships_per_employee=30)
portfolio_df = generate_portfolios(accounts_df, max_positions=10, instruments = instruments)

# Print the first few rows of each DataFrame
print("Employees Data:")
print(employees_df.head())

print("\nAccounts Data:")
print(accounts_df.head())

print("\nOpportunities Data:")
print(opportunities_df.head())

print("\nEmployee-Contact Relationships Data:")
print(contacts_df.head())

print("\nPortfolio Info for Each Account")
print(portfolio_df.head())


print("\nPortfolio detail")
print(fund_dtl_df.head())

Employees Data:
                            employee_id first_name   last_name  \
0  31e735f6-cfbe-4107-8aba-4ef45a90e9ae       Jane  Moneypenny
1  ecd26c31-854e-46df-916e-dbc29a668d4e      Isaac      Brooks
2  70b90359-98a6-4556-bdd5-bed2d3d026dc      Jason       Weiss
3  6b4ab2be-8ea6-4bd2-b659-50ec31f4ab2d   Kathleen   Gutierrez
4  43980bcd-24f1-49b3-99eb-7d2f2a0c9786       Seth   Hernandez

                  title                            email                phone  \
0  Relationship Manager    jane.moneypenny1@bankwell.com   971.841.4711x92417
1  Relationship Manager        isaac.brooks@bankwell.com    (513)933-7654x571
2    Product Specialist         jason.weiss@bankwell.com  (673)944-9070x19343
3    Product Specialist  kathleen.gutierrez@bankwell.com           2415387938
4     Finance Assistant      seth.hernandez@bankwell.com    (476)567-5432x022

    hire_date             department         market
0  2021-01-14  Enterprise Investment  San Fransisco
1  2024-03-04  Enterprise Investment         Dallas
2  2023-10-06                  Sales         Boston
3  2023-11-15                  Sales        Seattle
4  2023-06-21       Customer Support  New York City

Accounts Data:
                 company     industry                            account_id  \
0                Mariott  Hospitality  d02ccad1-26c4-4768-95a4-833dbc2b2460
1               Broadcom   Technology  2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba
2                  Cisco   Technology  8f1f6d76-62f8-4920-9359-0464f3916a07
3  Palantir Technologies   Technology  92fca0b6-7f67-4b06-b855-be97b5ee8783
4                 Fiserv   Technology  3678b91e-4cf4-4aa1-aacf-bb946fae18ad

  contact_first_name contact_last_name    contact_title                 phone  \
0               Mary           Vasquez  Senior Director      520-618-5303x572
1              Jacob            Morris       Consultant      605.823.5891x895
2        Christopher             Craig  Senior Director     913.446.6722x6025
3              Jason             Davis  Senior Director  001-583-431-0554x517
4              Alexa          Cummings          Manager      001-443-380-9727

                                  email                  website  \
0              mary.vasquez@mariott.com              mariott.com
1             jacob.morris@broadcom.com      http://trevino.com/
2           christopher.craig@cisco.com    http://www.davis.com/
3  jason.davis@palantirtechnologies.com       http://harris.net/
4             alexa.cummings@fiserv.com  http://www.webster.com/

        location  annual_revenue  total_account_bal
0  New York City        43000000           30000000
1        Seattle        34725845           39175341
2         Denver        35647270            6326284
3        Seattle        15807351           43097563
4         Boston        39302954           22823148

Opportunities Data:
                         opportunity_id                            account_id  \
0  f7eed487-d68d-4d48-b4e7-2d7de1a1b4f2  d02ccad1-26c4-4768-95a4-833dbc2b2460
1  4b6c8bb0-a9c6-4ff5-8f23-6c2ef9b22328  d02ccad1-26c4-4768-95a4-833dbc2b2460
2  9f10ded6-79c0-4d2d-85ae-df5a1a595723  2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba
3  0aa356e5-f3cc-4ebe-bb08-96ca7d28c0bf  8f1f6d76-62f8-4920-9359-0464f3916a07
4  be6092db-e3ce-4887-997b-43baca13f9db  8f1f6d76-62f8-4920-9359-0464f3916a07

                          opportunity_name        stage               type  \
0                      mesh 24/365 schemas       Closed             Upsell
1  exploit clicks-and-mortar web-readiness     Proposal            Renewal
2                    leverage B2C channels          Won       New Business
3                       engage dynamic ROI  Negotiation            Renewal
4             cultivate enterprise content  Negotiation  Existing Business

   close_date  amount
0  2025-01-17  261392
1  2025-05-02  409326
2  2025-04-25  433312
3  2025-01-12  391157
4  2025-02-27  269100

Employee-Contact Relationships Data:
                            employee_id employee_first_name  \
0  31e735f6-cfbe-4107-8aba-4ef45a90e9ae                Jane
1  ecd26c31-854e-46df-916e-dbc29a668d4e               Isaac
2  ecd26c31-854e-46df-916e-dbc29a668d4e               Isaac
3  ecd26c31-854e-46df-916e-dbc29a668d4e               Isaac
4  70b90359-98a6-4556-bdd5-bed2d3d026dc               Jason

  employee_last_name                            account_id  \
0         Moneypenny  d02ccad1-26c4-4768-95a4-833dbc2b2460
1             Brooks  14b92430-1d3e-4889-a7d8-6a4bd9aa49fa
2             Brooks  2073ba72-c21f-4990-ab29-f81d4d6014ee
3             Brooks  45c72262-7027-4a72-af17-5c728aaef0a7
4              Weiss  3807c060-e929-43df-bf04-cb9abc8d464d

                   company     industry contact_first_name contact_last_name  \
0                  Mariott  Hospitality               Mary           Vasquez
1   Rhythm Pharmaceuticals   Healthcare               Mary            Nguyen
2  Graham Holdings Company       Retail             Amanda         Alexander
3              Tyson Foods       Retail          Christine           Woodard
4                CubeSmart   RealEstate         Jacqueline              Cain

                                contact_email    contact_title  \
0                    mary.vasquez@mariott.com  Senior Director
1       mary.nguyen@rhythmpharmaceuticals.com         Director
2  amanda.alexander@grahamholdingscompany.com       Consultant
3            christine.woodard@tysonfoods.com          Manager
4               jacqueline.cain@cubesmart.com          Manager

            contact_phone
0        520-618-5303x572
1     +1-663-223-0027x124
2  001-996-599-5681x68260
3      931-227-5812x30085
4           (845)211-9460

Portfolio Info for Each Account
                             account_id   company symbol    fund_type  \
0  d02ccad1-26c4-4768-95a4-833dbc2b2460   Mariott  VSMPX  Equity Fund
1  d02ccad1-26c4-4768-95a4-833dbc2b2460   Mariott    MUB    Bond Fund
2  2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba  Broadcom  FXAIX  Equity Fund
3  2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba  Broadcom    MUB    Bond Fund
4  2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba  Broadcom  VSMPX  Equity Fund

   tot_balance  fund_balance
0     30000000    9131421.84
1     30000000   20868578.16
2     39175341    8914618.95
3     39175341    7469131.54
4     39175341    3020979.70

Portfolio detail
      ticker                       position_name   fund  weight fund_type
0     700 HK                Tencent Holdings Ltd  FTIEX    0.05    equity
1    2330 TT  Taiwan Semiconductor Manufacturing  FTIEX    0.20    equity
2     RHM GR                      Rheinmetall AG  FTIEX    0.05    equity
3     SAP GR                              SAP SE  FTIEX    0.10    equity
4  005930 KS          Samsung Electronics Co Ltd  FTIEX    0.10    equity

In [11]:
portfolio_df.head(10)

,account_id,company,symbol,fund_type,tot_balance,fund_balance
0,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,VSMPX,Equity Fund,30000000,9131421.84
1,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,MUB,Bond Fund,30000000,20868578.16
2,2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba,Broadcom,FXAIX,Equity Fund,39175341,8914618.95
3,2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba,Broadcom,MUB,Bond Fund,39175341,7469131.54
4,2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba,Broadcom,VSMPX,Equity Fund,39175341,3020979.70
5,2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba,Broadcom,BND,Bond Fund,39175341,19770610.80
6,8f1f6d76-62f8-4920-9359-0464f3916a07,Cisco,MBB,Bond Fund,6326284,5774642.94
7,8f1f6d76-62f8-4920-9359-0464f3916a07,Cisco,VCSH,Bond Fund,6326284,551641.06
8,92fca0b6-7f67-4b06-b855-be97b5ee8783,Palantir Technologies,TLT,Bond Fund,43097563,20507241.67
9,92fca0b6-7f67-4b06-b855-be97b5ee8783,Palantir Technologies,FXAIX,Equity Fund,43097563,22590321.33

# Load to database

### Employees Table

In [12]:
employees_df.head()

,employee_id,first_name,last_name,title,email,phone,hire_date,department,market
0,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,Relationship Manager,jane.moneypenny1@bankwell.com,971.841.4711x92417,2021-01-14,Enterprise Investment,San Fransisco
1,ecd26c31-854e-46df-916e-dbc29a668d4e,Isaac,Brooks,Relationship Manager,isaac.brooks@bankwell.com,(513)933-7654x571,2024-03-04,Enterprise Investment,Dallas
2,70b90359-98a6-4556-bdd5-bed2d3d026dc,Jason,Weiss,Product Specialist,jason.weiss@bankwell.com,(673)944-9070x19343,2023-10-06,Sales,Boston
3,6b4ab2be-8ea6-4bd2-b659-50ec31f4ab2d,Kathleen,Gutierrez,Product Specialist,kathleen.gutierrez@bankwell.com,2415387938,2023-11-15,Sales,Seattle
4,43980bcd-24f1-49b3-99eb-7d2f2a0c9786,Seth,Hernandez,Finance Assistant,seth.hernandez@bankwell.com,(476)567-5432x022,2023-06-21,Customer Support,New York City

In [13]:
employees_df.shape

(100, 9)

In [14]:
employees_df.to_sql('employees', engine, if_exists='replace', index=False)

100

In [15]:
alter_sql = """
ALTER TABLE "employees"
ADD PRIMARY KEY ("employee_id");
"""

with engine.connect() as connection:
    connection.execute(text(alter_sql))

In [16]:
df = pd.read_sql("SELECT * from employees", con=engine)
df.head()

,employee_id,first_name,last_name,title,email,phone,hire_date,department,market
0,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,Relationship Manager,jane.moneypenny1@bankwell.com,971.841.4711x92417,2021-01-14,Enterprise Investment,San Fransisco
1,ecd26c31-854e-46df-916e-dbc29a668d4e,Isaac,Brooks,Relationship Manager,isaac.brooks@bankwell.com,(513)933-7654x571,2024-03-04,Enterprise Investment,Dallas
2,70b90359-98a6-4556-bdd5-bed2d3d026dc,Jason,Weiss,Product Specialist,jason.weiss@bankwell.com,(673)944-9070x19343,2023-10-06,Sales,Boston
3,6b4ab2be-8ea6-4bd2-b659-50ec31f4ab2d,Kathleen,Gutierrez,Product Specialist,kathleen.gutierrez@bankwell.com,2415387938,2023-11-15,Sales,Seattle
4,43980bcd-24f1-49b3-99eb-7d2f2a0c9786,Seth,Hernandez,Finance Assistant,seth.hernandez@bankwell.com,(476)567-5432x022,2023-06-21,Customer Support,New York City

### Clients Contact table

In [17]:
accounts_df.head()

,company,industry,account_id,contact_first_name,contact_last_name,contact_title,phone,email,website,location,annual_revenue,total_account_bal
0,Mariott,Hospitality,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mary,Vasquez,Senior Director,520-618-5303x572,mary.vasquez@mariott.com,mariott.com,New York City,43000000,30000000
1,Broadcom,Technology,2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba,Jacob,Morris,Consultant,605.823.5891x895,jacob.morris@broadcom.com,http://trevino.com/,Seattle,34725845,39175341
2,Cisco,Technology,8f1f6d76-62f8-4920-9359-0464f3916a07,Christopher,Craig,Senior Director,913.446.6722x6025,christopher.craig@cisco.com,http://www.davis.com/,Denver,35647270,6326284
3,Palantir Technologies,Technology,92fca0b6-7f67-4b06-b855-be97b5ee8783,Jason,Davis,Senior Director,001-583-431-0554x517,jason.davis@palantirtechnologies.com,http://harris.net/,Seattle,15807351,43097563
4,Fiserv,Technology,3678b91e-4cf4-4aa1-aacf-bb946fae18ad,Alexa,Cummings,Manager,001-443-380-9727,alexa.cummings@fiserv.com,http://www.webster.com/,Boston,39302954,22823148

In [18]:
accounts_df.shape

(83, 12)

In [19]:
accounts_df.to_sql('clients_contact', engine, if_exists='replace', index=False)

83

In [20]:
alter_sql = """
ALTER TABLE "clients_contact"
ADD PRIMARY KEY ("account_id");
"""

with engine.connect() as connection:
    connection.execute(text(alter_sql))

### Client alignment table

In [21]:
contacts_df.head()

,employee_id,employee_first_name,employee_last_name,account_id,company,industry,contact_first_name,contact_last_name,contact_email,contact_title,contact_phone
0,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Mary,Vasquez,mary.vasquez@mariott.com,Senior Director,520-618-5303x572
1,ecd26c31-854e-46df-916e-dbc29a668d4e,Isaac,Brooks,14b92430-1d3e-4889-a7d8-6a4bd9aa49fa,Rhythm Pharmaceuticals,Healthcare,Mary,Nguyen,mary.nguyen@rhythmpharmaceuticals.com,Director,+1-663-223-0027x124
2,ecd26c31-854e-46df-916e-dbc29a668d4e,Isaac,Brooks,2073ba72-c21f-4990-ab29-f81d4d6014ee,Graham Holdings Company,Retail,Amanda,Alexander,amanda.alexander@grahamholdingscompany.com,Consultant,001-996-599-5681x68260
3,ecd26c31-854e-46df-916e-dbc29a668d4e,Isaac,Brooks,45c72262-7027-4a72-af17-5c728aaef0a7,Tyson Foods,Retail,Christine,Woodard,christine.woodard@tysonfoods.com,Manager,931-227-5812x30085
4,70b90359-98a6-4556-bdd5-bed2d3d026dc,Jason,Weiss,3807c060-e929-43df-bf04-cb9abc8d464d,CubeSmart,RealEstate,Jacqueline,Cain,jacqueline.cain@cubesmart.com,Manager,(845)211-9460

In [22]:
client_alignment = contacts_df.drop_duplicates()

In [23]:
client_alignment.to_sql('client_alignment', engine, if_exists='replace', index=False)

366

In [24]:
alter_sql = """
ALTER TABLE "client_alignment"
ADD PRIMARY KEY ("account_id", "employee_id");
"""

with engine.connect() as connection:
    connection.execute(text(alter_sql))

### Portfolio Table

In [25]:
portfolio_df.head()

,account_id,company,symbol,fund_type,tot_balance,fund_balance
0,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,VSMPX,Equity Fund,30000000,9131421.84
1,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,MUB,Bond Fund,30000000,20868578.16
2,2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba,Broadcom,FXAIX,Equity Fund,39175341,8914618.95
3,2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba,Broadcom,MUB,Bond Fund,39175341,7469131.54
4,2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba,Broadcom,VSMPX,Equity Fund,39175341,3020979.70

In [26]:
portfolio_df.to_sql('portfolio', engine, if_exists='replace', index=False)

300

In [27]:
alter_sql = """
ALTER TABLE "portfolio"
ADD PRIMARY KEY ("account_id", "symbol");
"""

with engine.connect() as connection:
    connection.execute(text(alter_sql))

### Portfolio Detail

In [28]:
fund_dtl_df = pd.read_excel('equity_fund_example.xlsx')

In [29]:
fund_dtl_df.head()

      ticker                       position_name   fund  weight fund_type
0     700 HK                Tencent Holdings Ltd  FTIEX    0.05    equity
1    2330 TT  Taiwan Semiconductor Manufacturing  FTIEX    0.20    equity
2     RHM GR                      Rheinmetall AG  FTIEX    0.05    equity
3     SAP GR                              SAP SE  FTIEX    0.10    equity
4  005930 KS          Samsung Electronics Co Ltd  FTIEX    0.10    equity

In [30]:
fund_dtl_df.to_sql('fund_detail', engine, if_exists='replace', index=False)

55

In [31]:
alter_sql = """
ALTER TABLE "fund_detail"
ADD PRIMARY KEY ("ticker", "fund");
"""

with engine.connect() as connection:
    connection.execute(text(alter_sql))

# Test Results

In [32]:
pd.read_sql("SELECT * FROM portfolio limit 10", con=engine)

,account_id,company,symbol,fund_type,tot_balance,fund_balance
0,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,VSMPX,Equity Fund,30000000,9131421.84
1,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,MUB,Bond Fund,30000000,20868578.16
2,2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba,Broadcom,FXAIX,Equity Fund,39175341,8914618.95
3,2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba,Broadcom,MUB,Bond Fund,39175341,7469131.54
4,2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba,Broadcom,VSMPX,Equity Fund,39175341,3020979.70
5,2654cbf4-6e19-4a32-a93a-1c7b5b03d1ba,Broadcom,BND,Bond Fund,39175341,19770610.80
6,8f1f6d76-62f8-4920-9359-0464f3916a07,Cisco,MBB,Bond Fund,6326284,5774642.94
7,8f1f6d76-62f8-4920-9359-0464f3916a07,Cisco,VCSH,Bond Fund,6326284,551641.06
8,92fca0b6-7f67-4b06-b855-be97b5ee8783,Palantir Technologies,TLT,Bond Fund,43097563,20507241.67
9,92fca0b6-7f67-4b06-b855-be97b5ee8783,Palantir Technologies,FXAIX,Equity Fund,43097563,22590321.33

In [33]:
pd.read_sql("SELECT * FROM fund_detail limit 10", con=engine)

      ticker                       position_name   fund  weight fund_type
0     700 HK                Tencent Holdings Ltd  FTIEX    0.05    equity
1    2330 TT  Taiwan Semiconductor Manufacturing  FTIEX    0.20    equity
2     RHM GR                      Rheinmetall AG  FTIEX    0.05    equity
3     SAP GR                              SAP SE  FTIEX    0.10    equity
4  005930 KS          Samsung Electronics Co Ltd  FTIEX    0.10    equity
5     CRH US                             CRH PLC  FTIEX    0.20    equity
6     BA/ LN                     BAE Systems PLC  FTIEX    0.10    equity
7    ASML NA                     ASML Holding NV  FTIEX    0.15    equity
8     LIN US                           Linde PLC  FTIEX    0.04    equity
9        SAF                           Safran SA  FTIEX    0.01    equity

In [34]:
pd.read_sql("SELECT * FROM client_alignment limit 10", con=engine)

,employee_id,employee_first_name,employee_last_name,account_id,company,industry,contact_first_name,contact_last_name,contact_email,contact_title,contact_phone
0,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Mary,Vasquez,mary.vasquez@mariott.com,Senior Director,520-618-5303x572
1,ecd26c31-854e-46df-916e-dbc29a668d4e,Isaac,Brooks,14b92430-1d3e-4889-a7d8-6a4bd9aa49fa,Rhythm Pharmaceuticals,Healthcare,Mary,Nguyen,mary.nguyen@rhythmpharmaceuticals.com,Director,+1-663-223-0027x124
2,ecd26c31-854e-46df-916e-dbc29a668d4e,Isaac,Brooks,2073ba72-c21f-4990-ab29-f81d4d6014ee,Graham Holdings Company,Retail,Amanda,Alexander,amanda.alexander@grahamholdingscompany.com,Consultant,001-996-599-5681x68260
3,ecd26c31-854e-46df-916e-dbc29a668d4e,Isaac,Brooks,45c72262-7027-4a72-af17-5c728aaef0a7,Tyson Foods,Retail,Christine,Woodard,christine.woodard@tysonfoods.com,Manager,931-227-5812x30085
4,70b90359-98a6-4556-bdd5-bed2d3d026dc,Jason,Weiss,3807c060-e929-43df-bf04-cb9abc8d464d,CubeSmart,RealEstate,Jacqueline,Cain,jacqueline.cain@cubesmart.com,Manager,(845)211-9460
5,70b90359-98a6-4556-bdd5-bed2d3d026dc,Jason,Weiss,b88a80c0-b0c2-4ca5-a30d-9afe6da4f83c,UnitedHealth,Healthcare,Kelly,West,kelly.west@unitedhealth.com,Senior Director,001-773-816-4601
6,70b90359-98a6-4556-bdd5-bed2d3d026dc,Jason,Weiss,98f39666-c706-4750-b2d2-663b6a74bee6,Novo Nordisk,Healthcare,William,Parker,william.parker@novonordisk.com,Consultant,001-675-480-9981x4818
7,70b90359-98a6-4556-bdd5-bed2d3d026dc,Jason,Weiss,123dd42e-1116-45ad-a2ab-bb577e2323d1,Allbirds,Retail,Andrew,Benitez,andrew.benitez@allbirds.com,Senior Director,+1-709-752-0021x152
8,70b90359-98a6-4556-bdd5-bed2d3d026dc,Jason,Weiss,a0570b7a-aa91-4448-ba28-693a96c5337d,Broadstone,RealEstate,Steve,Allen,steve.allen@broadstone.com,Director,536.227.5350x220
9,70b90359-98a6-4556-bdd5-bed2d3d026dc,Jason,Weiss,9ada8819-fceb-469d-8f66-22ec0ceacf11,Sprouts Farmers Market,Retail,Catherine,Burton,catherine.burton@sproutsfarmersmarket.com,VP,001-396-240-2815x66688

In [35]:
pd.read_sql("SELECT * FROM client_alignment where employee_last_name = 'Moneypenny' ", con=engine)

,employee_id,employee_first_name,employee_last_name,account_id,company,industry,contact_first_name,contact_last_name,contact_email,contact_title,contact_phone
0,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Mary,Vasquez,mary.vasquez@mariott.com,Senior Director,520-618-5303x572

In [36]:
import datetime
import pytz

print(f"Notebook last execution time: {datetime.datetime.now(pytz.timezone('US/Central')).strftime('%a, %d %B %Y %H:%M:%S')}")

Notebook last execution time: Sun, 04 May 2025 20:18:40