# Sample CloudSql Connection

# Need to set up for each instance - Add your VM's IP to the Authorized Networks
**1. Find the external IP of your JupyterLab VM**
https://console.cloud.google.com/compute/instances?project=adsp-34002-on02-sopho-scribe&authuser=1
 * Go to VM Instances
 * Find your JupyterLab VM
 * Copy the External IP address (looks like 34.91.100.45).

**2. Add the VM's IP to your Cloud SQL authorized networks**
https://console.cloud.google.com/sql/instances/currensee-sql/connections/networking?authuser=1&project=adsp-34002-on02-sopho-scribe
* Go to Cloud SQL instances. 
* Click your instance.
* Click Connections in the left sidebar.
* Scroll to Authorized networks → Add network.
* Name: anything like jupyterlab-vm
* Network: paste the external IP you just copied (e.g., 34.91.100.45/32)
* IMPORTANT: Add /32 to allow only that single IP.
* Click Save.

It will take ~30 seconds to update.

In [1]:
#%poetry add -q google-cloud-secret-manager==2.23.3
#%poetry add -q SQLAlchemy==2.0.40

In [2]:
#%poetry add psycopg2-binary sqlalchemy pandas

In [3]:
from google.cloud import secretmanager
import pandas as pd
import numpy as np
from currensee.utils.db_utils import create_pg_engine
from sqlalchemy import text

## IMPORTANT
The cell below will only work if you have a .env file defined at `<fl>_currensee/currensee/.env` with the credentials 
defined in `<fl>_currensee/currensee/.env.example`.

Instructions are located within the `.env.example` file with how to fill out the credentials properly.

#### Create SQLAlchemy engine

In [4]:
# Define DB_NAME
DB_NAME = 'crm'

In [5]:
engine = create_pg_engine(
   db_name=DB_NAME
)

In [6]:
df_result = pd.read_sql("SELECT * FROM Employees limit 10", con=engine)
print(df_result)

                            employee_id first_name   last_name  \
0  31e735f6-cfbe-4107-8aba-4ef45a90e9ae       Jane  Moneypenny
1  a54a28e8-730d-4549-b0f8-7d6628b027b2      Randy       Jones
2  676c055e-25fc-4515-b0cb-80296be73a5f        Amy        Lang
3  18488f14-1dd6-4df0-b170-9d5dc34e40ae     Dakota        Mann
4  88c627c7-19db-4f61-a426-410ca5b954a9       Mark       Weber
5  df1a55a1-15fc-4ffe-a96f-8d7cfcaf27ac      Scott     Gardner
6  95a78c61-8cf7-4613-8c41-18746f2c7bc6       Sean      Carter
7  d01ad10a-1b19-431d-9743-99a7f5fdf502     Denise     Fuentes
8  6bbe023d-2664-4f87-98b0-26f38d427ab1      Brett      Golden
9  9af142d0-4c58-44f9-ab67-43934112e5bc        Ann    Gonzalez

                         title                          email  \
0         Relationship Manager  jane.moneypenny1@bankwell.com
1         Relationship Manager       randy.jones@bankwell.com
2           Product Specialist          amy.lang@bankwell.com
3           Product Specialist       dakota.mann@bankwell.com
4            Financial Advisor        mark.weber@bankwell.com
5           Product Specialist     scott.gardner@bankwell.com
6  Senior Relationship Manager       sean.carter@bankwell.com
7           Product Specialist    denise.fuentes@bankwell.com
8  Senior Relationship Manager      brett.golden@bankwell.com
9  Senior Relationship Manager      ann.gonzalez@bankwell.com

                  phone   hire_date                 department         market
0    971.841.4711x92417  2021-01-14      Enterprise Investment  San Fransisco
1   (875)289-1581x48521  2023-08-20      Enterprise Investment  Washington DC
2    694.297.3228x66492  2021-02-21           Customer Support         Dallas
3    300.477.3896x54588  2020-02-26  Small Business Investment  Washington DC
4  001-388-203-2035x281  2022-11-09                 Operations  Washington DC
5       +1-681-305-4865  2022-02-07      Enterprise Investment          Miami
6          260.356.9999  2024-10-17      Enterprise Investment  New York City
7   +1-436-226-8321x028  2020-01-25                      Sales    Los Angeles
8          449.580.7763  2023-10-17                 Operations         Dallas
9       +1-734-243-3393  2023-02-10      Enterprise Investment  San Fransisco

# Generate Fake Data

In [7]:
# %poetry add faker

In [8]:
import pandas as pd
import random
import os
import re
from faker import Faker

# Initialize Faker instance
#Faker is a Python package that integrates fake data for you.

#Some hard coded data of publicly traded companies to be our mock clients

In [9]:

fake = Faker()

# Helper function to generate synthetic employee data
def generate_employee_data(num_employees=10, ourcompany_name = 'bankwell'):
    company = ourcompany_name
    employees = [
        {
            'employee_id': '31e735f6-cfbe-4107-8aba-4ef45a90e9ae',
            'first_name': "Jane",
            'last_name': "Moneypenny",
            'title': "Relationship Manager",
            'email': "jane.moneypenny1@bankwell.com",
            'phone': "971.841.4711x92417",
            'hire_date': '2021-01-14',
            'department': 'Enterprise Investment',
            'market': 'San Fransisco'
        }
    ]

    for _ in range(num_employees-1):
        employee_id = fake.unique.uuid4()
        first_name = fake.first_name()
        last_name = fake.last_name()
        title = random.choice(['Finance Assistant', 'Financial Advisor', 'Senior Relationship Manager', 'Product Specialist', 'Relationship Manager'])
        phone = fake.phone_number()
        department = random.choice(['Enterprise Investment', 'Small Business Investment', 'Operations', 'Sales', 'Customer Support'])
        hire_date = fake.date_this_decade()
        market = random.choice(['San Fransisco', 'New York City', 'Boston', 'Denver', 'Los Angeles', 'Miami', 'Washington DC', 'Seattle', 'Dallas', 'Chicago'])
        company_clean = re.sub(r'\W+', '', company).lower()
        email = f"{first_name.lower()}.{last_name.lower()}@{company_clean}.com"


        employees.append({
            'employee_id': employee_id,
            'first_name': first_name,
            'last_name': last_name,
            'title': title,
            'email': email,
            'phone': phone,
            'hire_date': hire_date,
            'department': department,
            'market': market
        })
    return pd.DataFrame(employees)

# Helper function to generate point of contact and info for a Company
def generate_point_of_contact(company_name):
    account_id = fake.unique.uuid4()
    first_name = fake.first_name()
    last_name = fake.last_name()
    contact_title = random.choice(["Senior Director", "Manager", "Director", "VP", "Consultant"])
    phone = fake.phone_number()
    Website = fake.url()
    Location = random.choice(['San Fransisco', 'New York City', 'Boston', 'Denver', 'Los Angeles', 'Miami', 'Washington DC', 'Seattle', 'Dallas', 'Chicago'])
    AnnualRevenue = random.randint(1000000, 50000000)
    TotalAccountBal = random.randint(1000000, 50000000)

    # Clean Company name for use in email
    company_clean = re.sub(r'\W+', '', company_name).lower()
    email = f"{first_name.lower()}.{last_name.lower()}@{company_clean}.com"

    return {
        "account_id": account_id,
        "contact_first_name": first_name,
        "contact_last_name": last_name,
        "contact_title": contact_title,
        "phone": phone,
        "email": email,
        "website": Website,
        "location": Location,
        "annual_revenue": AnnualRevenue,
        "total_account_bal": TotalAccountBal
    }


def generate_account_data(num_accounts=5, clients_company = []):
# Build the data
    # Hi Jing - add code here. Love, Lily
    # Hi Lily - added! Love, Jing
    accounts = [
        { "company": 'Mariott',
         "industry": 'Hospitality',
        "account_id": 'd02ccad1-26c4-4768-95a4-833dbc2b2460',
        "contact_first_name": 'Mary',
        "contact_last_name": 'Vasquez',
        "contact_title": 'Senior Director',
        "phone": '520-618-5303x572',
        "email": 'mary.vasquez@mariott.com',
        "website": 'mariott.com',
        "location": 'New York City',
        "annual_revenue": 43000000,
        "total_account_bal": 30000000
        },
        
        { "company": 'AbbVie',
         "industry": 'Healthcare',
        "account_id": 'd02ccad1-26c4-4768-95a4-833dbc2b2461',
        "contact_first_name": 'Cynthia',
        "contact_last_name": 'Hobbs',
        "contact_title": 'Director',
        "phone": '(446)673-8121x90878',
        "email": 'cynthia.hobbs@abbvie.com',
        "website": 'AbbVie.com',
        "location": 'Chicago',
        "annual_revenue": 35000000,
        "total_account_bal": 39000000
        },

        { "company": 'AeroVironment',
         "industry": 'Manufacturing',
        "account_id": 'd02ccad1-26c4-4768-95a4-833dbc2b2462',
        "contact_first_name": 'Jennifer',
        "contact_last_name": 'Phelps',
        "contact_title": 'Senior Director',
        "phone": '797-584-0061x89137',
        "email": 'jennifer.phelps@aerovironment.com',
        "website": 'AeroVironment.com',
        "location": 'Washington DC',
        "annual_revenue": 25000000,
        "total_account_bal": 4000000
        },
         {
        "company": 'Amedisys',
        "industry": 'Healthcare',
        "account_id": 'c42e62e8-e943-47e0-bfd1-651e053c8bc6',  
        "contact_first_name": 'Kyle',
        "contact_last_name": 'Waters',
        "contact_title": 'Senior Director',
        "phone": '590.239.3215x8014',
        "email": 'kyle.waters@amedisys.com',
        "website": 'Amedisys.org',
        "location": 'Washington DC',
        "annual_revenue": 36891234,
        "total_account_bal": 45213789
        },
        {
        "company": 'Celestica',
        "industry": 'Technology',
        "account_id": 'c42e62e8-e943-47e0-bfd1-651e053c8bc5',  
        "contact_first_name": 'Denise',
        "contact_last_name": 'Moore',
        "contact_title": 'Senior Director',
        "phone": '754-579-1511x763',
        "email": 'denise.moore@celestica.com',
        "website": 'celestica.com',
        "location": 'Washington DC',
        "annual_revenue": 36891234,
        "total_account_bal": 45213789
        },
        {
        "company": 'Compass',
        "industry": 'RealEstate',
        "account_id": 'c2352f32-9a89-4f6e-995e-3f1d61da1ef4',  
        "contact_first_name": 'Adam',
        "contact_last_name": 'Clay',
        "contact_title": 'VP',
        "phone": '-2931',
        "email": 'adam.clay@compass.com',
        "website": 'compass.com',
        "location": 'San Francisco',
        "annual_revenue": 17500000,
        "total_account_bal": 21500000
        },
        {
        "company": 'GameStop Corp',
        "industry": 'Retail',
        "account_id": 'd3021a76-bf2c-4f23-9b8c-45323d214920',  
        "contact_first_name": 'Amy',
        "contact_last_name": 'Winters',
        "contact_title": 'Senior Director',
        "phone": '381-842-2729x61450',
        "email": 'amy.winters@gamestopcorp.com',
        "website": 'gamestopcorp.com',
        "location": 'Dallas',
        "annual_revenue": 19000000,
        "total_account_bal": 24000000
        },
        {
        "company": 'Guardant Health',
        "industry": 'Healthcare',
        "account_id": '68c2a459-fc28-4f39-bf27-8721424c6db8',  
        "contact_first_name": 'Roberto',
        "contact_last_name": 'Martin',
        "contact_title": 'VP',
        "phone": '420.200.4573x07741',
        "email": 'roberto.martin@guardanthealth.com',
        "website": 'guardanthealth.com',
        "location": 'Seattle',
        "annual_revenue": 80000000,
        "total_account_bal": 120000000
        },
        {
        "company": 'Hasbro',
        "industry": 'Retail',
        "account_id": '3b911a12-ff3a-4a93-9f44-6454381d76bc', 
        "contact_first_name": 'Jessica',
        "contact_last_name": 'Palmer',
        "contact_title": 'VP',
        "phone": '909.878.8329x31984',
        "email": 'jessica.palmer@hasbro.com',
        "website": 'hasbro.com',
        "location": 'Miami',
        "annual_revenue": 65000000,
        "total_account_bal": 75000000
        },
        {
        "company": 'Hyatt Hotels',
        "industry": 'Hospitality',
        "account_id": 'f43fa598-e705-4908-98ab-e231f0287da9', 
        "contact_first_name": 'Timothy',
        "contact_last_name": 'Ochoa',
        "contact_title": 'Manager',
        "phone": '315-583-8080',
        "email": 'timothy.ochoa@hyatthotels.com',
        "website": 'hyatthotels.com',
        "location": 'Washington DC',
        "annual_revenue": 120000000,
        "total_account_bal": 130000000
        },
        {
        "company": 'Intuitive Surgical',
        "industry": 'Healthcare',
        "account_id": '962f2d76-c51c-4a8b-80c3-ecdb5db59858', 
        "contact_first_name": 'Michelle',
        "contact_last_name": 'Jenkins',
        "contact_title": 'Director',
        "phone": '(612)342-3657x6255',
        "email": 'michelle.jenkins@intuitivesurgical.com',
        "website": 'intuitivesurgical.com',
        "location": 'San Francisco',
        "annual_revenue": 115000000,
        "total_account_bal": 140000000
        },
        {
        "company": 'Ladder Capital Corp',
        "industry": 'RealEstate',
        "account_id": '7599e1bb-df47-44b6-b206-e6b1a0fe62av', 
        "contact_first_name": 'Ronnie',
        "contact_last_name": 'Gray',
        "contact_title": 'Director',
        "phone": '001-750-645-5770x695',
        "email": 'ronnie.gray@laddercapitalcorp.com',
        "website": 'laddercapitalcorp.com',
        "location": 'Chicago',
        "annual_revenue": 27000000,
        "total_account_bal": 33000000
        },
        {
        "company": 'Lockheed Martin Corporation',
        "industry": 'Manufacturing',
        "account_id": 'fca6b8a7-e1f3-4a6d-918b-02d0b2b1c2b0',  
        "contact_first_name": 'Lisa',
        "contact_last_name": 'Kennedy',
        "contact_title": 'Senior Director',
        "phone": '+1-341-221-9798x577',
        "email": 'lisa.kennedy@lockheedmartincorporation.com',
        "website": 'lockheedmartin.com',
        "location": 'Washington DC',
        "annual_revenue": 920000000,
        "total_account_bal": 1100000000
        },
        {
        "company": 'ManpowerGroup',
        "industry": 'Manufacturing',
        "account_id": 'bcc303fb-b897-47ff-b1ae-02e6fdb34c0d',  
        "contact_first_name": 'David',
        "contact_last_name": 'Moreno',
        "contact_title": 'Director',
        "phone": '001-945-497-7155x003',
        "email": 'david.moreno@manpowergroup.com',
        "website": 'manpowergroup.com',
        "location": 'Boston',
        "annual_revenue": 153000000,
        "total_account_bal": 165000000
        },
        {
        "company": 'Matson',
        "industry": 'Manufacturing',
        "account_id": 'c4b9e3e8-2c82-49d4-93ca-050fd83ad6be',  
        "contact_first_name": 'Anna',
        "contact_last_name": 'Lawrence',
        "contact_title": 'Director',
        "phone": '+1-675-665-6673x605',
        "email": 'anna.lawrence@matson.com',
        "website": 'matson.com',
        "location": 'Los Angeles',
        "annual_revenue": 88000000,
        "total_account_bal": 99000000
        },
        {
        "company": 'Medtronic',
        "industry": 'Healthcare',
        "account_id": 'ed22214f-9fbe-4a2d-bf51-46d05f2bba98',  
        "contact_first_name": 'Tracey',
        "contact_last_name": 'Smith',
        "contact_title": 'Director',
        "phone": '+1-952-819-1211x857',
        "email": 'tracey.smith@medtronic.com',
        "website": 'medtronic.com',
        "location": 'Minneapolis',
        "annual_revenue": 500000000,
        "total_account_bal": 600000000
        },
        {
        "company": 'Presidio Property Trust',
        "industry": 'RealEstate',
        "account_id": '0d99abf4-faf2-4885-9c29-9086d944b973', 
        "contact_first_name": 'Kelly',
        "contact_last_name": 'Smith',
        "contact_title": 'Senior Director',
        "phone": '001-671-821-6029',
        "email": 'kelly.smith@presidiopropertytrust.com',
        "website": 'presidiopropertytrust.com',
        "location": 'New York',
        "annual_revenue": 24000000,
        "total_account_bal": 30000000
        }
        
    ]
    for company in clients_company:
        contact = generate_point_of_contact(company["company"])
        record = {
          "company": company["company"],
          "industry": company["industry"],
          **contact
      }
        accounts.append(record)
    return pd.DataFrame(accounts)




# Helper function to generate synthetic opportunity data
def generate_opportunity_data(accounts_df, num_opportunities_per_account=3):
    opportunities = []
    for _, account in accounts_df.iterrows():
        num_opportunities = random.randint(1, num_opportunities_per_account)
        for _ in range(num_opportunities):
            opportunities.append({
                'opportunity_id': fake.unique.uuid4(),
                'account_id': account['account_id'],
                'opportunity_name': fake.bs(),
                'stage': random.choice(['Prospecting', 'Qualification', 'Proposal', 'Negotiation', 'Won', 'Lost', 'Closed']),
                'type': random.choice(['New Business', 'Existing Business', 'Renewal', 'Upsell']),
                'close_date': fake.date_this_year(),
                'amount': random.randint(50000, 500000),
            })
    return pd.DataFrame(opportunities)

# Helper function to generate synthetic employee-contact relationship data
def generate_employee_contact_data(employees_df, accounts_df, num_relationships_per_employee=2):
    # Jing hard code here too.
    relationships = [
       { 'employee_id': '31e735f6-cfbe-4107-8aba-4ef45a90e9ae',
        'employee_first_name': 'Jane',
        'employee_last_name': 'Moneypenny',
        'account_id': 'd02ccad1-26c4-4768-95a4-833dbc2b2460',
        'company': 'Mariott',
        'industry': 'Hospitality',
        'contact_first_name': 'Mary',
        'contact_last_name': 'Vasquez',
        'contact_email': 'mary.vasquez@mariott.com',
        'contact_title': 'Senior Director',
        'contact_phone': '520-618-5303x572'},
        {
        'employee_id': '31e735f6-cfbe-4107-8aba-4ef45a90e9ae',
        'employee_first_name': 'Jane',
        'employee_last_name': 'Moneypenny',
        'account_id': 'd02ccad1-26c4-4768-95a4-833dbc2b2461',
        'company': 'AbbVie',
        'industry': 'Healthcare',
        'contact_first_name': 'Cynthia',
        'contact_last_name': 'Hobbs',
        'contact_email': 'cynthia.hobbs@abbvie.com',
        'contact_title': 'Director',
        'contact_phone': '(446)673-8121x90878'
        },
        {
        'employee_id': '31e735f6-cfbe-4107-8aba-4ef45a90e9ae',
        'employee_first_name': 'Jane',
        'employee_last_name': 'Moneypenny',
        'account_id': 'd02ccad1-26c4-4768-95a4-833dbc2b2462',
        'company': 'AeroVironment',
        'industry': 'Manufacturing',
        'contact_first_name': 'Jennifer',
        'contact_last_name': 'Phelps',
        'contact_email': 'jennifer.phelps@aerovironment.com',
        'contact_title': 'Senior Director',
        'contact_phone': '797-584-0061x89137'
        },
        {
        'employee_id': '31e735f6-cfbe-4107-8aba-4ef45a90e9ae',
        'employee_first_name': 'Jane',
        'employee_last_name': 'Moneypenny',
        'account_id': 'c42e62e8-e943-47e0-bfd1-651e053c8bc6',
        'company': 'Amedisys',
        'industry': 'Healthcare',
        'contact_first_name': 'Kyle',
        'contact_last_name': 'Waters',
        'contact_email': 'kyle.waters@amedisys.com',
        'contact_title': 'Senior Director',
        'contact_phone': '590.239.3215x8014'
        },
        {
        'employee_id': '31e735f6-cfbe-4107-8aba-4ef45a90e9ae',
        'employee_first_name': 'Jane',
        'employee_last_name': 'Moneypenny',
        'account_id': 'c42e62e8-e943-47e0-bfd1-651e053c8bc5',
        'company': 'Celestica',
        'industry': 'Technology',
        'contact_first_name': 'Denise',
        'contact_last_name': 'Moore',
        'contact_email': 'denise.moore@celestica.com',
        'contact_title': 'Senior Director',
        'contact_phone': '754-579-1511x763'
        },
        {
        'employee_id': '31e735f6-cfbe-4107-8aba-4ef45a90e9ae',
        'employee_first_name': 'Jane',
        'employee_last_name': 'Moneypenny',
        'account_id': 'c2352f32-9a89-4f6e-995e-3f1d61da1ef4',
        'company': 'Compass',
        'industry': 'RealEstate',
        'contact_first_name': 'Adam',
        'contact_last_name': 'Clay',
        'contact_email': 'adam.clay@compass.com',
        'contact_title': 'VP',
        'contact_phone': '-2931'
        },
        {
        'employee_id': '31e735f6-cfbe-4107-8aba-4ef45a90e9ae',
        'employee_first_name': 'Jane',
        'employee_last_name': 'Moneypenny',
        'account_id': '68c2a459-fc28-4f39-bf27-8721424c6db8',
        'company': 'Guardant Health',
        'industry': 'Healthcare',
        'contact_first_name': 'Roberto',
        'contact_last_name': 'Martin',
        'contact_email': 'roberto.martin@guardanthealth.com',
        'contact_title': 'VP',
        'contact_phone': '420.200.4573x07741'
        },
        {
        'employee_id': '31e735f6-cfbe-4107-8aba-4ef45a90e9ae',
        'employee_first_name': 'Jane',
        'employee_last_name': 'Moneypenny',
        'account_id': 'fca6b8a7-e1f3-4a6d-918b-02d0b2b1c2b0',
        'company': 'Lockheed Martin Corporation',
        'industry': 'Manufacturing',
        'contact_first_name': 'Lisa',
        'contact_last_name': 'Kennedy',
        'contact_email': 'lisa.kennedy@lockheedmartincorporation.com',
        'contact_title': 'Senior Director',
        'contact_phone': '+1-341-221-9798x577'
        },
        {
        'employee_id': '31e735f6-cfbe-4107-8aba-4ef45a90e9ae',
        'employee_first_name': 'Jane',
        'employee_last_name': 'Moneypenny',
        'account_id': '962f2d76-c51c-4a8b-80c3-ecdb5db59858',
        'company': 'Intuitive Surgical',
        'industry': 'Healthcare',
        'contact_first_name': 'Michelle',
        'contact_last_name': 'Jenkins',
        'contact_email': 'michelle.jenkins@intuitivesurgical.com',
        'contact_title': 'Director',
        'contact_phone': '(612)342-3657x6255'
        },
        {
        'employee_id': '31e735f6-cfbe-4107-8aba-4ef45a90e9ae',
        'employee_first_name': 'Jane',
        'employee_last_name': 'Moneypenny',
        'account_id': 'ed22214f-9fbe-4a2d-bf51-46d05f2bba98',
        'company': 'Medtronic',
        'industry': 'Healthcare',
        'contact_first_name': 'Tracey',
        'contact_last_name': 'Smith',
        'contact_email': 'tracey.smith@medtronic.com',
        'contact_title': 'Director',
        'contact_phone': '+1-952-819-1211x857'
        }
    ]

    employee_nj = employees_df[employees_df['last_name'] != 'Moneypenny']
    for _, employee in employee_nj.iterrows():
        num_relationships = random.randint(1, num_relationships_per_employee)
        for _ in range(num_relationships):
            account = random.choice(accounts_df['account_id'].tolist())
            relationships.append({
                'employee_id': employee['employee_id'],
                'employee_first_name': employee['first_name'],
                'employee_last_name': employee['last_name'],
                'account_id': account,
                'company': accounts_df.loc[accounts_df['account_id'] == account, 'company'].iloc[0],
                'industry': accounts_df.loc[accounts_df['account_id'] == account, 'industry'].iloc[0],
                'contact_first_name': accounts_df.loc[accounts_df['account_id'] == account, 'contact_first_name'].iloc[0],
                'contact_last_name': accounts_df.loc[accounts_df['account_id'] == account, 'contact_last_name'].iloc[0],
                'contact_email': accounts_df.loc[accounts_df['account_id'] == account, 'email'].iloc[0],
                'contact_title': accounts_df.loc[accounts_df['account_id'] == account, 'contact_title'].iloc[0],
                'contact_phone': accounts_df.loc[accounts_df['account_id'] == account, 'phone'].iloc[0],
            })
    return pd.DataFrame(relationships)



def generate_portfolios(df_accounts, max_positions=9, instruments=[]):
    portfolio_records = []

    for _, row in df_accounts.iterrows():
        account_id = row["account_id"]
        company = row["company"]
        total_account_bal = row["total_account_bal"]

        num_positions = random.randint(2, 5)
        positions = random.sample(instruments, num_positions)

        # Generate random proportions that sum to 1
        random_weights = np.random.rand(num_positions)
        random_weights /= random_weights.sum()

        for (symbol, instrument_type), weight in zip(positions, random_weights):
            fund_balance = round(total_account_bal * weight, 2)
            portfolio_records.append({
                "account_id": account_id,
                "company": company,
                "symbol": symbol,
                "fund_type": instrument_type,
                "tot_balance": total_account_bal,
                "fund_balance": fund_balance
            })

    return pd.DataFrame(portfolio_records)

In [10]:
# Right now companies can only be selected from this list of publicly traded companies 
# Likely want this to be random instead..
clients_company_info = [
        {"company": "Broadcom", "industry": "Technology"},
        {"company": "Cisco", "industry": "Technology"},
        {"company": "Palantir Technologies", "industry": "Technology"},
        {"company": "Fiserv", "industry": "Technology"},
        {"company": "Atlassian", "industry": "Technology"},
        {"company": "Leidos", "industry": "Technology"},
        {"company": "Duolingo", "industry": "Technology"},
        {"company": "Logitech", "industry": "Technology"},
        {"company": "Celestica", "industry": "Technology"},
        {"company": "Dropbox", "industry": "Technology"},
        {"company": "Plexus", "industry": "Technology"},
        {"company": "Silicon Laboratories", "industry": "Technology"},
        {"company": "Mobix Labs", "industry": "Technology"},
        {"company": "InterContinental Hotels Group", "industry": "Hospitality"},
        {"company": "Sonder Holdings", "industry": "Hospitality"},
        {"company": "Hyatt Hotels", "industry": "Hospitality"},
        {"company": "Royal Caribbean Cruises", "industry": "Hospitality"},
        {"company": "UnitedHealth", "industry": "Healthcare"},
        {"company": "Johnson & Johnson", "industry": "Healthcare"},
        {"company": "AbbVie", "industry": "Healthcare"},
        {"company": "Novo Nordisk", "industry": "Healthcare"},
        {"company": "Abbott Laboratories", "industry": "Healthcare"},
        {"company": "AstraZeneca", "industry": "Healthcare"},
        {"company": "Merck & Co", "industry": "Healthcare"},
        {"company": "Intuitive Surgical", "industry": "Healthcare"},
        {"company": "Medtronic", "industry": "Healthcare"},
        {"company": "Zoetis", "industry": "Healthcare"},
        {"company": "Humana", "industry": "Healthcare"},
        {"company": "Illumina", "industry": "Healthcare"},
        {"company": "Guardant Health", "industry": "Healthcare"},
        {"company": "Rhythm Pharmaceuticals", "industry": "Healthcare"},
        {"company": "Amedisys", "industry": "Healthcare"},
        {"company": "Rivian Automotive", "industry": "Automotive"},
        {"company": "Fordy", "industry": "Automotive"},
        {"company": "lululemon athletica", "industry": "Retail"},
        {"company": "DICK'S Sporting Goods", "industry": "Retail"},
        {"company": "GameStop Corp", "industry": "Retail"},
        {"company": "Texas Roadhouse", "industry": "Retail"},
        {"company": "Hasbro", "industry": "Retail"},
        {"company": "Mattel", "industry": "Retail"},
        {"company": "Wayfair", "industry": "Retail"},
        {"company": "Peloton", "industry": "Retail"},
        {"company": "Sally Beauty", "industry": "Retail"},
        {"company": "Lifetime Brand", "industry": "Retail"},
        {"company": "Allbirds", "industry": "Retail"},
        {"company": "Walmart", "industry": "Retail"},
        {"company": "Tyson Foods", "industry": "Retail"},
        {"company": "Sprouts Farmers Market", "industry": "Retail"},
        {"company": "Dollar Tree", "industry": "Retail"},
        {"company": "Stride", "industry": "Retail"},
        {"company": "Spectrum Brands", "industry": "Retail"},
        {"company": "Udemy", "industry": "Retail"},
        {"company": "Vital Farms", "industry": "Retail"},
        {"company": "Graham Holdings Company", "industry": "Retail"},
        {"company": "Hims & Hers Health", "industry": "Retail"},
        {"company": "Smithfield Foods", "industry": "Retail"},
        {"company": "Albertsons Companies", "industry": "Retail"},
        {"company": "Albany International", "industry": "Manufacturing"},
        {"company": "IT Tech Packaging", "industry": "Manufacturing"},
        {"company": "Lockheed Martin Corporation", "industry": "Manufacturing"},
        {"company": "Landstar System", "industry": "Manufacturing"},
        {"company": "Hexcel Corporation", "industry": "Manufacturing"},
        {"company": "AeroVironment", "industry": "Manufacturing"},
        {"company": "Matson", "industry": "Manufacturing"},
        {"company": "McGrath RentCorp", "industry": "Manufacturing"},
        {"company": "Mueller Industries", "industry": "Manufacturing"},
        {"company": "Dolby Laboratories", "industry": "Manufacturing"},
        {"company": "ManpowerGroup", "industry": "Manufacturing"},
        {"company": "Welltower", "industry": "RealEstate"},
        {"company": "Iron Mountain Incorporated", "industry": "RealEstate"},
        {"company": "Camden Property", "industry": "RealEstate"},
        {"company": "CubeSmart", "industry": "RealEstate"},
        {"company": "Federal Realty Investment Trust", "industry": "RealEstate"},
        {"company": "Essential Properties Realty", "industry": "RealEstate"},
        {"company": "Compass", "industry": "RealEstate"},
        {"company": "Medical Properties Trust", "industry": "RealEstate"},
        {"company": "Broadstone", "industry": "RealEstate"},
        {"company": "Ladder Capital Corp", "industry": "RealEstate"},
        {"company": "Peakstone Realty Trus", "industry": "RealEstate"},
        {"company": "Fathom Holdings", "industry": "RealEstate"},
        {"company": "Presidio Property Trust", "industry": "RealEstate"},
        {"company": "Service Properties Trust", "industry": "RealEstate"},
    ]


Bond_funds = ['BND', 'MUB', 'MBB', 'VCSH', 'TLT']
Equity_funds = ['VSMPX', 'FXAIX', 'FCNTX', 'FTIEX']
# All symbols with types
instruments = (
    [(sym, 'Bond Fund') for sym in Bond_funds ] +
    [(sym, 'Equity Fund') for sym in Equity_funds]
)

fund_dtl_df = pd.read_excel('equity_fund_example.xlsx')
# Generate synthetic data for the tables
employees_df = generate_employee_data(num_employees=100, ourcompany_name = 'bankwell')
accounts_df = generate_account_data(num_accounts=1000, clients_company = clients_company_info)
opportunities_df = generate_opportunity_data(accounts_df, num_opportunities_per_account=3)
contacts_df = generate_employee_contact_data(employees_df, accounts_df, num_relationships_per_employee=30)
portfolio_df = generate_portfolios(accounts_df, max_positions=10, instruments = instruments)

# Print the first few rows of each DataFrame
print("Employees Data:")
print(employees_df.head())

print("\nAccounts Data:")
print(accounts_df.head())

print("\nOpportunities Data:")
print(opportunities_df.head())

print("\nEmployee-Contact Relationships Data:")
print(contacts_df.head())

print("\nPortfolio Info for Each Account")
print(portfolio_df.head())


print("\nPortfolio detail")
print(fund_dtl_df.head())

Employees Data:
                            employee_id first_name   last_name  \
0  31e735f6-cfbe-4107-8aba-4ef45a90e9ae       Jane  Moneypenny
1  b61a7a99-791a-4b9f-923f-271810defac4     Monica      Melton
2  2f8c004d-e0a6-4bba-956e-2b60af632674    Michael        Long
3  59dcd404-9d5c-47f4-9ba1-2de5156343f8    Breanna      Guerra
4  7a650dd8-34a3-4148-a7f8-631bf5db37d4    Heather       Singh

                         title                          email  \
0         Relationship Manager  jane.moneypenny1@bankwell.com
1           Product Specialist     monica.melton@bankwell.com
2            Finance Assistant      michael.long@bankwell.com
3  Senior Relationship Manager    breanna.guerra@bankwell.com
4            Financial Advisor     heather.singh@bankwell.com

                phone   hire_date                 department         market
0  971.841.4711x92417  2021-01-14      Enterprise Investment  San Fransisco
1        884.541.7837  2021-12-03  Small Business Investment        Chicago
2    478-831-1994x378  2021-12-06                      Sales  Washington DC
3    736-597-4792x589  2024-07-11      Enterprise Investment         Boston
4          7139112404  2020-11-15           Customer Support  Washington DC

Accounts Data:
         company       industry                            account_id  \
0        Mariott    Hospitality  d02ccad1-26c4-4768-95a4-833dbc2b2460
1         AbbVie     Healthcare  d02ccad1-26c4-4768-95a4-833dbc2b2461
2  AeroVironment  Manufacturing  d02ccad1-26c4-4768-95a4-833dbc2b2462
3       Amedisys     Healthcare  c42e62e8-e943-47e0-bfd1-651e053c8bc6
4      Celestica     Technology  c42e62e8-e943-47e0-bfd1-651e053c8bc5

  contact_first_name contact_last_name    contact_title                phone  \
0               Mary           Vasquez  Senior Director     520-618-5303x572
1            Cynthia             Hobbs         Director  (446)673-8121x90878
2           Jennifer            Phelps  Senior Director   797-584-0061x89137
3               Kyle            Waters  Senior Director    590.239.3215x8014
4             Denise             Moore  Senior Director     754-579-1511x763

                               email            website       location  \
0           mary.vasquez@mariott.com        mariott.com  New York City
1           cynthia.hobbs@abbvie.com         AbbVie.com        Chicago
2  jennifer.phelps@aerovironment.com  AeroVironment.com  Washington DC
3           kyle.waters@amedisys.com       Amedisys.org  Washington DC
4         denise.moore@celestica.com      celestica.com  Washington DC

   annual_revenue  total_account_bal
0        43000000           30000000
1        35000000           39000000
2        25000000            4000000
3        36891234           45213789
4        36891234           45213789

Opportunities Data:
                         opportunity_id                            account_id  \
0  dd974b67-8f4a-409d-8a34-104cc84d32b6  d02ccad1-26c4-4768-95a4-833dbc2b2460
1  3ecbbedd-a194-4da4-a6d6-79729d156904  d02ccad1-26c4-4768-95a4-833dbc2b2460
2  e6a72cae-9f84-4c0d-8c2e-8995a668cfff  d02ccad1-26c4-4768-95a4-833dbc2b2460
3  a6279404-cd11-4301-ba6e-5d352c1dbaae  d02ccad1-26c4-4768-95a4-833dbc2b2461
4  8f1f2e22-910e-4aa2-8fcd-9260d621ef3a  d02ccad1-26c4-4768-95a4-833dbc2b2462

                   opportunity_name          stage               type  \
0  visualize efficient applications         Closed             Upsell
1        morph ubiquitous e-markets           Lost       New Business
2             enable compelling ROI            Won       New Business
3       deploy compelling platforms  Qualification       New Business
4    aggregate ubiquitous paradigms    Prospecting  Existing Business

   close_date  amount
0  2025-03-18  148204
1  2025-04-05  112326
2  2025-01-02  302138
3  2025-03-13  328901
4  2025-01-08  178523

Employee-Contact Relationships Data:
                            employee_id employee_first_name  \
0  31e735f6-cfbe-4107-8aba-4ef45a90e9ae                Jane
1  31e735f6-cfbe-4107-8aba-4ef45a90e9ae                Jane
2  31e735f6-cfbe-4107-8aba-4ef45a90e9ae                Jane
3  31e735f6-cfbe-4107-8aba-4ef45a90e9ae                Jane
4  31e735f6-cfbe-4107-8aba-4ef45a90e9ae                Jane

  employee_last_name                            account_id        company  \
0         Moneypenny  d02ccad1-26c4-4768-95a4-833dbc2b2460        Mariott
1         Moneypenny  d02ccad1-26c4-4768-95a4-833dbc2b2461         AbbVie
2         Moneypenny  d02ccad1-26c4-4768-95a4-833dbc2b2462  AeroVironment
3         Moneypenny  c42e62e8-e943-47e0-bfd1-651e053c8bc6       Amedisys
4         Moneypenny  c42e62e8-e943-47e0-bfd1-651e053c8bc5      Celestica

        industry contact_first_name contact_last_name  \
0    Hospitality               Mary           Vasquez
1     Healthcare            Cynthia             Hobbs
2  Manufacturing           Jennifer            Phelps
3     Healthcare               Kyle            Waters
4     Technology             Denise             Moore

                       contact_email    contact_title        contact_phone
0           mary.vasquez@mariott.com  Senior Director     520-618-5303x572
1           cynthia.hobbs@abbvie.com         Director  (446)673-8121x90878
2  jennifer.phelps@aerovironment.com  Senior Director   797-584-0061x89137
3           kyle.waters@amedisys.com  Senior Director    590.239.3215x8014
4         denise.moore@celestica.com  Senior Director     754-579-1511x763

Portfolio Info for Each Account
                             account_id  company symbol    fund_type  \
0  d02ccad1-26c4-4768-95a4-833dbc2b2460  Mariott    BND    Bond Fund
1  d02ccad1-26c4-4768-95a4-833dbc2b2460  Mariott    TLT    Bond Fund
2  d02ccad1-26c4-4768-95a4-833dbc2b2460  Mariott    MBB    Bond Fund
3  d02ccad1-26c4-4768-95a4-833dbc2b2460  Mariott  FTIEX  Equity Fund
4  d02ccad1-26c4-4768-95a4-833dbc2b2461   AbbVie    MUB    Bond Fund

   tot_balance  fund_balance
0     30000000    4267139.69
1     30000000    3270591.09
2     30000000   11859244.95
3     30000000   10603024.27
4     39000000   29019986.25

Portfolio detail
      ticker                       position_name   fund  weight fund_type
0     700 HK                Tencent Holdings Ltd  FTIEX    0.05    equity
1    2330 TT  Taiwan Semiconductor Manufacturing  FTIEX    0.20    equity
2     RHM GR                      Rheinmetall AG  FTIEX    0.05    equity
3     SAP GR                              SAP SE  FTIEX    0.10    equity
4  005930 KS          Samsung Electronics Co Ltd  FTIEX    0.10    equity

In [11]:
portfolio_df.head(10)

,account_id,company,symbol,fund_type,tot_balance,fund_balance
0,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,BND,Bond Fund,30000000,4267139.69
1,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,TLT,Bond Fund,30000000,3270591.09
2,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,MBB,Bond Fund,30000000,11859244.95
3,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,FTIEX,Equity Fund,30000000,10603024.27
4,d02ccad1-26c4-4768-95a4-833dbc2b2461,AbbVie,MUB,Bond Fund,39000000,29019986.25
5,d02ccad1-26c4-4768-95a4-833dbc2b2461,AbbVie,TLT,Bond Fund,39000000,9980013.75
6,d02ccad1-26c4-4768-95a4-833dbc2b2462,AeroVironment,FTIEX,Equity Fund,4000000,1205370.29
7,d02ccad1-26c4-4768-95a4-833dbc2b2462,AeroVironment,FXAIX,Equity Fund,4000000,1528109.33
8,d02ccad1-26c4-4768-95a4-833dbc2b2462,AeroVironment,FCNTX,Equity Fund,4000000,1266520.38
9,c42e62e8-e943-47e0-bfd1-651e053c8bc6,Amedisys,MUB,Bond Fund,45213789,15611406.12

# Load to database

### Employees Table

In [12]:
employees_df.head()

,employee_id,first_name,last_name,title,email,phone,hire_date,department,market
0,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,Relationship Manager,jane.moneypenny1@bankwell.com,971.841.4711x92417,2021-01-14,Enterprise Investment,San Fransisco
1,b61a7a99-791a-4b9f-923f-271810defac4,Monica,Melton,Product Specialist,monica.melton@bankwell.com,884.541.7837,2021-12-03,Small Business Investment,Chicago
2,2f8c004d-e0a6-4bba-956e-2b60af632674,Michael,Long,Finance Assistant,michael.long@bankwell.com,478-831-1994x378,2021-12-06,Sales,Washington DC
3,59dcd404-9d5c-47f4-9ba1-2de5156343f8,Breanna,Guerra,Senior Relationship Manager,breanna.guerra@bankwell.com,736-597-4792x589,2024-07-11,Enterprise Investment,Boston
4,7a650dd8-34a3-4148-a7f8-631bf5db37d4,Heather,Singh,Financial Advisor,heather.singh@bankwell.com,7139112404,2020-11-15,Customer Support,Washington DC

In [13]:
employees_df.shape

(100, 9)

In [14]:
employees_df.to_sql('employees', engine, if_exists='replace', index=False)

100

In [15]:
alter_sql = """
ALTER TABLE "employees"
ADD PRIMARY KEY ("employee_id");
"""

with engine.connect() as connection:
    connection.execute(text(alter_sql))

In [16]:
df = pd.read_sql("SELECT * from employees", con=engine)
df.head()

,employee_id,first_name,last_name,title,email,phone,hire_date,department,market
0,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,Relationship Manager,jane.moneypenny1@bankwell.com,971.841.4711x92417,2021-01-14,Enterprise Investment,San Fransisco
1,b61a7a99-791a-4b9f-923f-271810defac4,Monica,Melton,Product Specialist,monica.melton@bankwell.com,884.541.7837,2021-12-03,Small Business Investment,Chicago
2,2f8c004d-e0a6-4bba-956e-2b60af632674,Michael,Long,Finance Assistant,michael.long@bankwell.com,478-831-1994x378,2021-12-06,Sales,Washington DC
3,59dcd404-9d5c-47f4-9ba1-2de5156343f8,Breanna,Guerra,Senior Relationship Manager,breanna.guerra@bankwell.com,736-597-4792x589,2024-07-11,Enterprise Investment,Boston
4,7a650dd8-34a3-4148-a7f8-631bf5db37d4,Heather,Singh,Financial Advisor,heather.singh@bankwell.com,7139112404,2020-11-15,Customer Support,Washington DC

### Clients Contact table

In [17]:
accounts_df.head()

,company,industry,account_id,contact_first_name,contact_last_name,contact_title,phone,email,website,location,annual_revenue,total_account_bal
0,Mariott,Hospitality,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mary,Vasquez,Senior Director,520-618-5303x572,mary.vasquez@mariott.com,mariott.com,New York City,43000000,30000000
1,AbbVie,Healthcare,d02ccad1-26c4-4768-95a4-833dbc2b2461,Cynthia,Hobbs,Director,(446)673-8121x90878,cynthia.hobbs@abbvie.com,AbbVie.com,Chicago,35000000,39000000
2,AeroVironment,Manufacturing,d02ccad1-26c4-4768-95a4-833dbc2b2462,Jennifer,Phelps,Senior Director,797-584-0061x89137,jennifer.phelps@aerovironment.com,AeroVironment.com,Washington DC,25000000,4000000
3,Amedisys,Healthcare,c42e62e8-e943-47e0-bfd1-651e053c8bc6,Kyle,Waters,Senior Director,590.239.3215x8014,kyle.waters@amedisys.com,Amedisys.org,Washington DC,36891234,45213789
4,Celestica,Technology,c42e62e8-e943-47e0-bfd1-651e053c8bc5,Denise,Moore,Senior Director,754-579-1511x763,denise.moore@celestica.com,celestica.com,Washington DC,36891234,45213789

In [18]:
accounts_df.shape

(99, 12)

In [19]:
accounts_df.to_sql('clients_contact', engine, if_exists='replace', index=False)

99

In [20]:
alter_sql = """
ALTER TABLE "clients_contact"
ADD PRIMARY KEY ("account_id");
"""

with engine.connect() as connection:
    connection.execute(text(alter_sql))

### Client alignment table

In [21]:
contacts_df.head()

,employee_id,employee_first_name,employee_last_name,account_id,company,industry,contact_first_name,contact_last_name,contact_email,contact_title,contact_phone
0,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Mary,Vasquez,mary.vasquez@mariott.com,Senior Director,520-618-5303x572
1,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,d02ccad1-26c4-4768-95a4-833dbc2b2461,AbbVie,Healthcare,Cynthia,Hobbs,cynthia.hobbs@abbvie.com,Director,(446)673-8121x90878
2,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,d02ccad1-26c4-4768-95a4-833dbc2b2462,AeroVironment,Manufacturing,Jennifer,Phelps,jennifer.phelps@aerovironment.com,Senior Director,797-584-0061x89137
3,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,c42e62e8-e943-47e0-bfd1-651e053c8bc6,Amedisys,Healthcare,Kyle,Waters,kyle.waters@amedisys.com,Senior Director,590.239.3215x8014
4,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,c42e62e8-e943-47e0-bfd1-651e053c8bc5,Celestica,Technology,Denise,Moore,denise.moore@celestica.com,Senior Director,754-579-1511x763

In [22]:
query = """
SELECT account_id, employee_id, COUNT(*) as count
FROM client_alignment
GROUP BY account_id, employee_id
HAVING COUNT(*) > 1;
"""

duplicates_df = pd.read_sql(query, engine)
print(duplicates_df)

                             account_id                           employee_id  \
0  7599e1bb-df47-44b6-b206-e6b1a0fe62ab  31e735f6-cfbe-4107-8aba-4ef45a90e9ae
1  962f2d76-c51c-4b87-a72b-34bf43a13f8e  31e735f6-cfbe-4107-8aba-4ef45a90e9ae

   count
0      2
1      2

In [23]:
client_alignment = contacts_df.drop_duplicates()

In [24]:
client_alignment.to_sql('client_alignment', engine, if_exists='replace', index=False)

392

In [25]:
alter_sql = """
ALTER TABLE "client_alignment"
ADD PRIMARY KEY ("account_id", "employee_id");
"""

with engine.connect() as connection:
    connection.execute(text(alter_sql))

### Portfolio Table

In [26]:
portfolio_df.head()

,account_id,company,symbol,fund_type,tot_balance,fund_balance
0,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,BND,Bond Fund,30000000,4267139.69
1,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,TLT,Bond Fund,30000000,3270591.09
2,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,MBB,Bond Fund,30000000,11859244.95
3,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,FTIEX,Equity Fund,30000000,10603024.27
4,d02ccad1-26c4-4768-95a4-833dbc2b2461,AbbVie,MUB,Bond Fund,39000000,29019986.25

In [27]:
portfolio_df.to_sql('portfolio', engine, if_exists='replace', index=False)

350

In [28]:
alter_sql = """
ALTER TABLE "portfolio"
ADD PRIMARY KEY ("account_id", "symbol");
"""

with engine.connect() as connection:
    connection.execute(text(alter_sql))

### Portfolio Detail

In [29]:
fund_dtl_df = pd.read_excel('equity_fund_example.xlsx')

In [30]:
fund_dtl_df.head()

      ticker                       position_name   fund  weight fund_type
0     700 HK                Tencent Holdings Ltd  FTIEX    0.05    equity
1    2330 TT  Taiwan Semiconductor Manufacturing  FTIEX    0.20    equity
2     RHM GR                      Rheinmetall AG  FTIEX    0.05    equity
3     SAP GR                              SAP SE  FTIEX    0.10    equity
4  005930 KS          Samsung Electronics Co Ltd  FTIEX    0.10    equity

In [31]:
fund_dtl_df.to_sql('fund_detail', engine, if_exists='replace', index=False)

55

In [32]:
alter_sql = """
ALTER TABLE "fund_detail"
ADD PRIMARY KEY ("ticker", "fund");
"""

with engine.connect() as connection:
    connection.execute(text(alter_sql))

# Test Results

In [33]:
pd.read_sql("SELECT * FROM portfolio limit 10", con=engine)

,account_id,company,symbol,fund_type,tot_balance,fund_balance
0,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,BND,Bond Fund,30000000,4267139.69
1,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,TLT,Bond Fund,30000000,3270591.09
2,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,MBB,Bond Fund,30000000,11859244.95
3,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,FTIEX,Equity Fund,30000000,10603024.27
4,d02ccad1-26c4-4768-95a4-833dbc2b2461,AbbVie,MUB,Bond Fund,39000000,29019986.25
5,d02ccad1-26c4-4768-95a4-833dbc2b2461,AbbVie,TLT,Bond Fund,39000000,9980013.75
6,d02ccad1-26c4-4768-95a4-833dbc2b2462,AeroVironment,FTIEX,Equity Fund,4000000,1205370.29
7,d02ccad1-26c4-4768-95a4-833dbc2b2462,AeroVironment,FXAIX,Equity Fund,4000000,1528109.33
8,d02ccad1-26c4-4768-95a4-833dbc2b2462,AeroVironment,FCNTX,Equity Fund,4000000,1266520.38
9,c42e62e8-e943-47e0-bfd1-651e053c8bc6,Amedisys,MUB,Bond Fund,45213789,15611406.12

In [34]:
pd.read_sql("SELECT * FROM fund_detail limit 10", con=engine)

      ticker                       position_name   fund  weight fund_type
0     700 HK                Tencent Holdings Ltd  FTIEX    0.05    equity
1    2330 TT  Taiwan Semiconductor Manufacturing  FTIEX    0.20    equity
2     RHM GR                      Rheinmetall AG  FTIEX    0.05    equity
3     SAP GR                              SAP SE  FTIEX    0.10    equity
4  005930 KS          Samsung Electronics Co Ltd  FTIEX    0.10    equity
5     CRH US                             CRH PLC  FTIEX    0.20    equity
6     BA/ LN                     BAE Systems PLC  FTIEX    0.10    equity
7    ASML NA                     ASML Holding NV  FTIEX    0.15    equity
8     LIN US                           Linde PLC  FTIEX    0.04    equity
9        SAF                           Safran SA  FTIEX    0.01    equity

In [35]:
pd.read_sql("SELECT * FROM client_alignment limit 10", con=engine)

,employee_id,employee_first_name,employee_last_name,account_id,company,industry,contact_first_name,contact_last_name,contact_email,contact_title,contact_phone
0,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Mary,Vasquez,mary.vasquez@mariott.com,Senior Director,520-618-5303x572
1,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,d02ccad1-26c4-4768-95a4-833dbc2b2461,AbbVie,Healthcare,Cynthia,Hobbs,cynthia.hobbs@abbvie.com,Director,(446)673-8121x90878
2,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,d02ccad1-26c4-4768-95a4-833dbc2b2462,AeroVironment,Manufacturing,Jennifer,Phelps,jennifer.phelps@aerovironment.com,Senior Director,797-584-0061x89137
3,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,c42e62e8-e943-47e0-bfd1-651e053c8bc6,Amedisys,Healthcare,Kyle,Waters,kyle.waters@amedisys.com,Senior Director,590.239.3215x8014
4,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,c42e62e8-e943-47e0-bfd1-651e053c8bc5,Celestica,Technology,Denise,Moore,denise.moore@celestica.com,Senior Director,754-579-1511x763
5,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,c2352f32-9a89-4f6e-995e-3f1d61da1ef4,Compass,RealEstate,Adam,Clay,adam.clay@compass.com,VP,-2931
6,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,68c2a459-fc28-4f39-bf27-8721424c6db8,Guardant Health,Healthcare,Roberto,Martin,roberto.martin@guardanthealth.com,VP,420.200.4573x07741
7,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,fca6b8a7-e1f3-4a6d-918b-02d0b2b1c2b0,Lockheed Martin Corporation,Manufacturing,Lisa,Kennedy,lisa.kennedy@lockheedmartincorporation.com,Senior Director,+1-341-221-9798x577
8,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,962f2d76-c51c-4a8b-80c3-ecdb5db59858,Intuitive Surgical,Healthcare,Michelle,Jenkins,michelle.jenkins@intuitivesurgical.com,Director,(612)342-3657x6255
9,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,ed22214f-9fbe-4a2d-bf51-46d05f2bba98,Medtronic,Healthcare,Tracey,Smith,tracey.smith@medtronic.com,Director,+1-952-819-1211x857

In [36]:
pd.read_sql("SELECT * FROM client_alignment where employee_last_name = 'Moneypenny' ", con=engine)

,employee_id,employee_first_name,employee_last_name,account_id,company,industry,contact_first_name,contact_last_name,contact_email,contact_title,contact_phone
0,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Mary,Vasquez,mary.vasquez@mariott.com,Senior Director,520-618-5303x572
1,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,d02ccad1-26c4-4768-95a4-833dbc2b2461,AbbVie,Healthcare,Cynthia,Hobbs,cynthia.hobbs@abbvie.com,Director,(446)673-8121x90878
2,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,d02ccad1-26c4-4768-95a4-833dbc2b2462,AeroVironment,Manufacturing,Jennifer,Phelps,jennifer.phelps@aerovironment.com,Senior Director,797-584-0061x89137
3,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,c42e62e8-e943-47e0-bfd1-651e053c8bc6,Amedisys,Healthcare,Kyle,Waters,kyle.waters@amedisys.com,Senior Director,590.239.3215x8014
4,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,c42e62e8-e943-47e0-bfd1-651e053c8bc5,Celestica,Technology,Denise,Moore,denise.moore@celestica.com,Senior Director,754-579-1511x763
5,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,c2352f32-9a89-4f6e-995e-3f1d61da1ef4,Compass,RealEstate,Adam,Clay,adam.clay@compass.com,VP,-2931
6,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,68c2a459-fc28-4f39-bf27-8721424c6db8,Guardant Health,Healthcare,Roberto,Martin,roberto.martin@guardanthealth.com,VP,420.200.4573x07741
7,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,fca6b8a7-e1f3-4a6d-918b-02d0b2b1c2b0,Lockheed Martin Corporation,Manufacturing,Lisa,Kennedy,lisa.kennedy@lockheedmartincorporation.com,Senior Director,+1-341-221-9798x577
8,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,962f2d76-c51c-4a8b-80c3-ecdb5db59858,Intuitive Surgical,Healthcare,Michelle,Jenkins,michelle.jenkins@intuitivesurgical.com,Director,(612)342-3657x6255
9,31e735f6-cfbe-4107-8aba-4ef45a90e9ae,Jane,Moneypenny,ed22214f-9fbe-4a2d-bf51-46d05f2bba98,Medtronic,Healthcare,Tracey,Smith,tracey.smith@medtronic.com,Director,+1-952-819-1211x857

In [37]:
import datetime
import pytz

print(f"Notebook last execution time: {datetime.datetime.now(pytz.timezone('US/Central')).strftime('%a, %d %B %Y %H:%M:%S')}")

Notebook last execution time: Sun, 04 May 2025 21:50:27