In [1]:
from currensee.agents.complete_graph import compiled_graph
from currensee.agents.tools.finance_tools import generate_macro_table
from currensee.utils.output_utils import (
    generate_long_report,
    format_news_summary_to_html,
    format_paragraph_summary_to_html,
    save_html_to_file,
    generate_short_report,
    convert_html_to_pdf,
    generate_med_report,
)
import warnings
import joblib

warnings.filterwarnings("ignore")

2025-07-29 05:08:49,674 - currensee.core.secrets - INFO - PROJECT_ID not found, attempting to load from .env file
2025-07-29 05:08:49,678 - currensee.core.secrets - INFO - Loaded environment from ./.env
2025-07-29 05:08:49,679 - currensee.core.secrets - INFO - SecretManager initialized with project_id: adsp-34002-on02-sopho-scribe

In [2]:
from datetime import date

today = date.today()
today_date = today.strftime("%Y%m%d")
print(today_date)

20250729

## Test Case 1 - Compass

In [3]:
init_state = {
    "user_email" : "jane.moneypenny@bankwell.com",
    "client_name": "Adam Clay",
    "client_email": "adam.clay@compass.com",
    "meeting_timestamp": "2024-03-26 11:00:00",
    "meeting_description": "Compass - Annual Credit Facility Review Meeting",
}

result = compiled_graph.invoke(init_state)
graph_meeting_date = result['meeting_timestamp']
graph_last_meeting_date = result['last_meeting_timestamp']
summary_client_comms = result["summary_client_comms"]
fin_hold_summary_sourced= result["fin_hold_summary_sourced"]
client_news_summary_sourced= result["client_news_summary_sourced"]
recent_all_emails_dict = result["recent_all_emails_dict"]
recent_client_emails_dict = result["recent_client_emails_dict"]
meeting_category = result["meeting_category"]
holdings_detail = result["holdings_detail"]
# full_report = summary + "\n\n### Macro Financial Snapshot\n\n" + macro_table

print("--------------------------------------------------------------")
print("Client Communications Summary: ", summary_client_comms)
print("--------------------------------------------------------------")
print("Financial Holdings News Summary: ", fin_hold_summary_sourced)
print("--------------------------------------------------------------")
print("Client Company News Summary: ", client_news_summary_sourced)
print("--------------------------------------------------------------")

OperationalError: (psycopg2.OperationalError) connection to server at "35.232.92.211", port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [6]:
import pandas as pd
recent_all_emails = pd.DataFrame(recent_all_emails_dict)
recent_all_emails.head()

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2024-01-24 16:10:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi jane,\n\nYes, this needs further thought. I..."
1,2024-01-21 09:17:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Thanks Jane,\n\nThank you for the update. Seem..."
2,2023-12-13 10:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Michelle Jenkins,michelle.jenkins@intuitivesurgical.com,Re: Intuitive Surgical - Discussing FX Service...,"Hi Jane,\n\nYes, let's plan for that in Q1. Ho..."
3,2023-12-12 11:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 F...,"Thanks Jane,\n\nI will follow up if I have any..."
4,2023-12-05 11:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Timothy Ochoa,timothy.ochoa@hyatthotels.com,Re: Hyatt Hotels - 401(k) Advisory Services RFI,"Hi Jane,\n\nThanks for checking in. The RFI pr..."

In [7]:
recent_client_emails = pd.DataFrame(recent_client_emails_dict)
recent_client_emails.head()

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2023-10-02 10:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Re: Compass - Utilizing the Credit Facility,"Hi Jane,\n\nThanks for checking in. Yes, the f..."
1,2022-10-06 11:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Re: Compass - Credit Facility Closed,"Hi Jane,\n\nExcellent! Thanks to you and the B..."
2,2021-09-29 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Re: Compass - Credit Facility Documentation St...,"Hi Jane,\n\nYes, we're nearly there. Final rev..."
3,2020-09-21 11:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Re: Compass - Credit Facility Next Steps,"Hi Jane,\n\nWe received final internal approva..."
4,2019-09-12 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Re: Compass - Credit Facility Term Sheet,"Hi Jane,\n\nThanks for sending the term sheet ..."

## Test Case 2 - Hasbro Portfolio Diversification

In [5]:
init_state = {
    "user_email" : "jane.moneypenny@bankwell.com",
    "client_name": "Jessica Palmer",
    "client_email": "jessica.palmer@hasbro.com",
    "meeting_timestamp": "2024-02-04 14:30:00",
    "meeting_description": "Hasbro - Discuss Portfolio Diversification and Bond Strategy",
}

result = compiled_graph.invoke(init_state)
summary_client_comms = result["summary_client_comms"]
fin_hold_summary_sourced= result["fin_hold_summary_sourced"]
client_news_summary_sourced= result["client_news_summary_sourced"]
meeting_category = result["meeting_category"]
# full_report = summary + "\n\n### Macro Financial Snapshot\n\n" + macro_table
print("Client Communications Summary: ", summary_client_comms)
print("--------------------------------------------------------------")
print("Financial Holdings News Summary: ", fin_hold_summary_sourced)
print("--------------------------------------------------------------")
print("Client Company News Summary: ", client_news_summary_sourced)

===============================
Generating report with the following preferences:
 Holdings Detail: short
 Client News Detail: full
 Macro News Detail: none
 Past Meeting Detail: full
 Meeting topic: Risk Management
===============================

Client Communications Summary:  **Hasbro - Portfolio Diversification and Bond Strategy: Briefing Document**

**1. Past Email Summary**

Bankwell Financial and Hasbro have a history of collaboration, primarily focused on FX risk management.  Initial discussions centered on hedging Hasbro's EUR and GBP exposures from international sales.  A comparison of forward contracts and options led to Hasbro primarily utilizing forward contracts for H1 2021 and H2 2022 hedging, supplemented by options as needed.  The H1 2022 hedge performance review demonstrated the forwards' effectiveness in providing budget certainty.  Recent communication highlighted underperformance in small-cap consumer entertainment stocks, contrasted with the positive performance of structured notes linked to diversified consumer indexes.  This underperformance, coupled with concerns about the current bond allocation in light of inflation, prompted a request for a meeting to discuss portfolio diversification and bond strategy.


**2. Recent Email Topics**

* Further diversification of Hasbro's investment portfolio is recommended.
* Hasbro's investment strategy requires reevaluation due to an upcoming change in senior leadership.
* Underperformance of small-cap consumer entertainment stocks relative to the S&P benchmark necessitates a discussion on reallocating assets to lower-beta instruments or employing sector-rotation strategies.
* Hasbro's bond fund allocation requires review due to inflation's potential impact on the bond market;  a complete shift away from bonds has been suggested.
* Hasbro's recent divestitures are complete.


**3. Recent Client Questions**

1.  "Do you believe that current market trends will continue regarding small-cap consumer entertainment?"
2.  "Also, I am curious about our allocation in bond funds. Given current inflation, what is the likely impact on the bond market, i.e. should we consider moving further out of bonds?"
--------------------------------------------------------------
Financial Holdings News Summary:  •  Jessica Palmer's holdings in Amazon, Microsoft, and Meta show strong performance, linked to AI investments and growth strategies, although Meta faces EU regulatory pressure.<sup><a href="https://finance.yahoo.com/news/meta-platforms-inc-meta-unlikely-131122915.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/meta-platforms-inc-meta-jim-183651211.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/meta-platforms-meta-beat-estimates-161002364.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup> Intel's stock shows potential for short-term gains but also faces restructuring.<sup><a href="https://ca.finance.yahoo.com/news/intel-shares-could-squeeze-higher-125409729.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://uk.finance.yahoo.com/news/tesla-alphabet-intel-lloyds-jd-wetherspoon-stocks-to-watch-135328292.html?.tsrc=rss" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/know-ahead-intels-earnings-release-112831007.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>

• Walmart demonstrates strong performance, exceeding $550 billion in sales, despite potential price increases due to tariffs.<sup><a href="https://finance.yahoo.com/news/winners-losers-q1-walmart-nyse-033337109.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/top-stock-reports-walmart-coca-203100481.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/top-research-reports-walmart-hsbc-223600856.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>

• The overall economic climate is uncertain, with concerns about recession and inflation, although Q1 2025 earnings were better than expected.  Tariffs are a significant factor impacting consumer prices.

•  The "Magnificent Seven" tech companies, including some of Jessica's holdings, appear to be faring better than other sectors during the economic uncertainty.
--------------------------------------------------------------
Client Company News Summary:  Hasbro's recent performance has been a mixed bag, reflecting broader industry trends.<sup><a href="https://www.forbes.com/sites/joanverdon/2025/04/24/hasbro-delivers-upside-surprise-says-new-game-plan-is-working/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.forbes.com/sites/joanverdon/2025/03/02/the-toy-industry-is-hoping-for-a-bounce-back-year-as-toy-fair-opens/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.forbes.com/sites/joanverdon/2024/10/24/hasbro-sales-down-15-profits-up-as-turnaround-challenge-continues/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  The company's first-quarter 2025 earnings significantly exceeded expectations, leading to a surge in stock price and easing investor concerns regarding tariffs.<sup><a href="https://www.forbes.com/sites/joanverdon/2025/04/24/hasbro-delivers-upside-surprise-says-new-game-plan-is-working/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.reuters.com/business/retail-consumer/hasbros-quarterly-revenue-beats-digital-gaming-demand-2025-04-24/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup> This success was largely attributed to strong growth in the Wizards of the Coast segment (digital and tabletop games).<sup><a href="https://finance.yahoo.com/news/hasbro-winning-hand-wizards-bucking-trend-184923779.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.reuters.com/business/retail-consumer/hasbros-quarterly-revenue-beats-digital-gaming-demand-2025-04-24/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  However, this positive result follows a period of challenges.<sup><a href="https://www.forbes.com/sites/joanverdon/2024/10/24/hasbro-sales-down-15-profits-up-as-turnaround-challenge-continues/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.reuters.com/business/retail-consumer/hasbro-posts-bigger-than-expected-quarterly-sales-drop-weak-toy-demand-2024-10-24/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.forbes.com/sites/joanverdon/2024/04/24/investors-reward-hasbro-mattel-for-cost-cuts-inventory-reductions/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  In 2024, Hasbro faced declining sales, though cost-cutting measures helped maintain profitability.<sup><a href="https://www.forbes.com/sites/joanverdon/2024/10/24/hasbro-sales-down-15-profits-up-as-turnaround-challenge-continues/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.reuters.com/business/retail-consumer/hasbro-posts-bigger-than-expected-quarterly-sales-drop-weak-toy-demand-2024-10-24/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.forbes.com/sites/joanverdon/2024/04/24/investors-reward-hasbro-mattel-for-cost-cuts-inventory-reductions/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  The company implemented a $1 billion cost-savings plan and reduced its workforce by 3% in June 2025,  further cuts having occurred in late 2023.  These actions reflect a broader industry trend of subdued toy demand, particularly in the United States where sales were down 7% in 2023.<sup><a href="https://www.forbes.com/sites/joanverdon/2025/03/02/the-toy-industry-is-hoping-for-a-bounce-back-year-as-toy-fair-opens/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  While the industry anticipates a rebound in 2025, the threat of increased tariffs remains a significant concern, potentially leading to higher toy prices.<sup><a href="https://www.forbes.com/sites/joanverdon/2025/03/02/the-toy-industry-is-hoping-for-a-bounce-back-year-as-toy-fair-opens/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.reuters.com/business/retail-consumer/hasbro-cuts-3-its-total-workforce-wsj-reports-2025-06-17/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.cnn.com/2025/07/09/business/hasbro-ceo-tariffs/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  Hasbro's strategic focus on digital gaming, products for older consumers (13+), and licensing partnerships aims to mitigate these challenges and drive future growth.<sup><a href="https://www.forbes.com/sites/joanverdon/2025/02/20/hasbro-stock-soars-as-toymaker-cuts-costs-reveals-new-game-plan/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.reuters.com/business/retail-consumer/toymaker-hasbro-forecasts-annual-revenue-below-estimates-2025-02-20/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>

## Test Case 3 - Hasbro H1 FX Hedging Strategy

In [3]:
init_state = {
    "user_email" : "jane.moneypenny@bankwell.com",
    "client_name": "Jessica Palmer",
    "client_email": "jessica.palmer@hasbro.com",
    "meeting_timestamp": "2023-12-11 11:00:00",
    "meeting_description": "Hasbro - Finalize H1 2024 FX Hedging Strategy",
}

result = compiled_graph.invoke(init_state)
summary_client_comms = result["summary_client_comms"]
fin_hold_summary_sourced= result["fin_hold_summary_sourced"]
client_news_summary_sourced= result["client_news_summary_sourced"]
meeting_category = result["meeting_category"]
# full_report = summary + "\n\n### Macro Financial Snapshot\n\n" + macro_table

print("meeting_category: ", meeting_category)
print("--------------------------------------------------------------")
print("Client Communications Summary: ", summary_client_comms)
print("--------------------------------------------------------------")
print("Financial Holdings News Summary: ", fin_hold_summary_sourced)
print("--------------------------------------------------------------")
print("Client Company News Summary: ", client_news_summary_sourced)

===============================
Generating report with the following preferences:
 Holdings Detail: short
 Client News Detail: full
 Macro News Detail: none
 Past Meeting Detail: none
 Meeting topic: Risk Management
===============================

meeting_category:  Risk Management
--------------------------------------------------------------
Client Communications Summary:
--------------------------------------------------------------
Financial Holdings News Summary:  • Walmart Inc.: Stock prices are up 97% in two years, demonstrating strong performance.<sup><a href="https://finance.yahoo.com/news/97-2-years-walmart-no-082000110.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  The Walton family, major shareholders, sold $329 million worth of stock in June 2025.<sup><a href="https://finance.yahoo.com/news/walton-family-unloads-walmart-stock-181516242.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>

• Intel Corp.: Experienced a 7.23% stock price increase in one day following a restructuring plan, but also underwent significant layoffs (over 1,600 in the US) and sold a large portion of its Mobileye stake ($1 billion).<sup><a href="https://finance.yahoo.com/news/intel-corp-intc-surges-7-182245536.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://ca.finance.yahoo.com/news/intel-offloads-1-billion-mobileye-203428835.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/intel-layoffs-surpass-1600-across-us-120012221.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>

• Meta Platforms Inc.: Stock prices have risen 30% since the last earnings release and 36% in the past three months, reflecting strong growth and an aggressive growth strategy.<sup><a href="https://finance.yahoo.com/news/why-netflix-and-meta-are-the-next-tech-catalysts-opening-bid-top-takeaways-151632607.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/meta-platforms-inc-meta-looking-210552742.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/meta-platforms-inc-meta-still-074059333.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  The company plans to raise $29 billion for AI data centers.<sup><a href="https://finance.yahoo.com/news/meta-platforms-inc-meta-looking-210552742.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>

• Amazon.com Inc.: Shows mixed signals with some analysts remaining bullish despite concerns about past performance and the presence of bargains.<sup><a href="https://finance.yahoo.com/news/amazon-com-inc-amzn-bargains-183631080.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/jpmorgan-lifts-pt-amazon-com-192515524.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  Further investment in AI firm Anthropic is being considered.<sup><a href="https://finance.yahoo.com/news/amazon-amzn-considers-additional-investment-153747053.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>
--------------------------------------------------------------
Client Company News Summary:  Recent news indicates Hasbro has undertaken significant cost-cutting measures, including a $1 billion cost-savings plan and workforce reductions of 3% in June 2025, following a previous 15% reduction in 2023.<sup><a href="https://www.reuters.com/business/retail-consumer/hasbro-cuts-3-its-total-workforce-wsj-reports-2025-06-17/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/hasbro-cuts-3-workforce-122100769.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.reuters.com/business/retail-consumer/hasbro-lay-off-20-workforce-wsj-2023-12-11/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  These actions, while impacting employment, aim to navigate subdued demand and improve profitability.<sup><a href="https://www.reuters.com/business/retail-consumer/hasbro-cuts-3-its-total-workforce-wsj-reports-2025-06-17/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.reuters.com/business/retail-consumer/toymaker-hasbro-forecasts-annual-revenue-below-estimates-2025-02-20/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  While the toy sales segment has experienced declines (15% in Q3 2024, 23% in Q4 2024)<sup><a href="https://www.forbes.com/sites/joanverdon/2024/10/24/hasbro-sales-down-15-profits-up-as-turnaround-challenge-continues/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.forbes.com/sites/joanverdon/2024/02/13/hasbro-sales-down-23-in-fourth-quarter-ceo-says-turnarounds-take-time/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>,  Hasbro's first-quarter 2025 earnings surpassed expectations, driven by the strength of its digital gaming business.<sup><a href="https://www.forbes.com/sites/joanverdon/2025/04/24/hasbro-delivers-upside-surprise-says-new-game-plan-is-working/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.reuters.com/business/retail-consumer/hasbros-quarterly-revenue-beats-digital-gaming-demand-2025-04-24/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/hasbro-winning-hand-wizards-bucking-184923779.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  The company's stock performance has fluctuated, reflecting both the challenges in the traditional toy market and the success in other areas.<sup><a href="https://www.forbes.com/sites/joanverdon/2025/04/24/hasbro-delivers-upside-surprise-says-new-game-plan-is-working/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.forbes.com/sites/joanverdon/2024/10/24/hasbro-sales-down-15-profits-up-as-turnaround-challenge-continues/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.forbes.com/sites/joanverdon/2024/04/24/investors-reward-hasbro-mattel-for-cost-cuts-inventory-reductions/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  The overall industry is anticipating a rebound in 2025 after a difficult period in 2023 and 2024.<sup><a href="https://www.forbes.com/sites/joanverdon/2025/03/02/the-toy-industry-is-hoping-for-a-bounce-back-year-as-toy-fair-opens/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>

## Test Case 4 - Ryan Holloway

In [6]:
init_state = {
    "user_email" : "ryan.holloway@bankwell.com",
    "client_name": "Adam Clay",
    "client_email": "adam.clay@compass.com",
    "meeting_timestamp": "2024-03-26 11:00:00",
    "meeting_description": "Compass - Annual Credit Facility Review Meeting",
}

result = compiled_graph.invoke(init_state)
summary_client_comms = result["summary_client_comms"]
fin_hold_summary_sourced= result["fin_hold_summary_sourced"]
client_news_summary_sourced= result["client_news_summary_sourced"]
meeting_category = result["meeting_category"]
# full_report = summary + "\n\n### Macro Financial Snapshot\n\n" + macro_table

print("meeting_category: ", meeting_category)
print("--------------------------------------------------------------")
print("Client Communications Summary: ", summary_client_comms)
print("--------------------------------------------------------------")
print("Financial Holdings News Summary: ", fin_hold_summary_sourced)
print("--------------------------------------------------------------")
print("Client Company News Summary: ", client_news_summary_sourced)

===============================
Generating report with the following preferences:
 Holdings Detail: none
 Client News Detail: none
 Macro News Detail: none
 Past Meeting Detail: short
 Meeting topic: Annual Review
===============================

meeting_category:  Annual Review
--------------------------------------------------------------
Client Communications Summary:  • Compass finds the credit facility's drawdown and reporting processes straightforward and satisfactory.
• The $25M revolving credit facility from Bankwell Financial has officially closed and funded.
• Bankwell Financial is providing ongoing support and assistance for Compass's use of the facility.
•  Review of Compass's satisfaction with the drawdown and reporting processes is a key agenda item.
• Discuss future facility needs and potential adjustments.
--------------------------------------------------------------
Financial Holdings News Summary:
--------------------------------------------------------------
Client Company News Summary:

In [9]:
init_state = {
    "user_email" : "jane.moneypenny@bankwell.com",
    "client_name": "Adam Clay",
    "client_email": "adam.clay@compass.com",
    "meeting_timestamp": "2025-05-25 14:00:00",
    "meeting_description": "Compass - ESG Ratings Dashboard Review",
}

result = compiled_graph.invoke(init_state)
summary_client_comms = result["summary_client_comms"]
fin_hold_summary_sourced= result["fin_hold_summary_sourced"]
client_news_summary_sourced= result["client_news_summary_sourced"]
meeting_category = result["meeting_category"]
# full_report = summary + "\n\n### Macro Financial Snapshot\n\n" + macro_table

print("meeting_category: ", meeting_category)
print("--------------------------------------------------------------")
print("Client Communications Summary: ", summary_client_comms)
print("--------------------------------------------------------------")
print("Financial Holdings News Summary: ", fin_hold_summary_sourced)
print("--------------------------------------------------------------")
print("Client Company News Summary: ", client_news_summary_sourced)

===============================
Generating report with the following preferences:
 Holdings Detail: full
 Client News Detail: none
 Macro News Detail: full
 Past Meeting Detail: full
 Meeting topic: ESG Investing
===============================

meeting_category:  ESG Investing
--------------------------------------------------------------
Client Communications Summary:  **Compass - ESG Ratings Dashboard Review: Meeting Briefing Document**

**1. Past Email Summary**

Bankwell Financial and Compass have a strong collaborative history, culminating in Compass securing a $25M revolving line of credit.  The process involved initial contact from Bankwell regarding Compass's expansion capital needs, followed by term sheet delivery, internal Compass approvals, loan agreement finalization, and successful funding. Post-funding, communication focused on facility functionality and drawdowns.  Recent email exchanges have broadened the scope of collaboration to include stress testing, risk management, capital allocation, milestone mapping, treasury KPI alignment, year-end tax planning, ESG fund portfolio and benchmark review, and carbon score implications.


**2. Recent Email Topics**

* Carbon score implications of a specific Compass investment or portfolio.
* Review of an ESG fund portfolio and its benchmark.
* Year-end tax planning options for Compass.


**3. Recent Client Questions**

1. Carbon score implications?
2. Year-end tax planning options?
--------------------------------------------------------------
Financial Holdings News Summary:  Mr. Clay's portfolio includes several companies exhibiting diverse performance and future prospects.  Taiwan Semiconductor Manufacturing (TSM) is expected to report record second-quarter profits, driven by its strong position in the AI chip market.<sup><a href="https://finance.yahoo.com/news/tsmc-quarterly-profit-seen-hitting-220157812.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/tsmc-tsm-named-top-pick-061948355.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/trending-stock-taiwan-semiconductor-manufacturing-130005824.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  While no specific ESG initiatives are mentioned, TSM's significant investment of $10 billion in its overseas unit could be interpreted as a strategic move to mitigate risks associated with geopolitical instability and currency fluctuations, indirectly reflecting a consideration of broader sustainability factors.<sup><a href="https://finance.yahoo.com/news/taiwan-semiconductor-manufacturing-company-limited-211134142.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup> CRH PLC shows strong performance with analysts maintaining buy ratings and raising price targets, fueled by EBITDA growth and significant insider buying.<sup><a href="https://finance.yahoo.com/news/morgan-stanley-raises-crh-crh-044639147.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/citi-maintains-buy-crh-plc-153133115.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/insider-stock-buying-reaches-us-110021905.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  Information regarding CRH's ESG performance is not available in the provided data. ASML Holding NV reported strong Q2 earnings but issued a cautious outlook for 2026 due to geopolitical and tariff uncertainties, resulting in a share price drop.<sup><a href="https://ca.finance.yahoo.com/quote/ASML/news/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://ca.finance.yahoo.com/quote/ASML.AS/news/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://ca.finance.yahoo.com/quote/ASMLF/news/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  No ESG-related information is provided.  Regarding Samsung Electronics Co Ltd, recent news focuses on legal matters rather than financial performance or ESG initiatives.<sup><a href="https://finance.yahoo.com/news/south-koreas-top-court-clears-023913336.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  Finally, SAP SE demonstrates positive momentum with strong AI and cloud growth, and maintains buy ratings from analysts.<sup><a href="https://finance.yahoo.com/news/sap-se-sap-bull-case-150453911.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/sap-named-top-emea-pick-151314453.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/sap-se-sap-maintains-buy-225104465.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  There is no information on SAP's ESG performance in the provided text.  Overall, the portfolio shows a mix of strong performers and companies facing headwinds, with limited information available regarding ESG performance for most holdings.
--------------------------------------------------------------
Client Company News Summary:

In [10]:
init_state = {
    "user_email" : "ryan.holloway@bankwell.com",
    "client_name": "Adam Clay",
    "client_email": "adam.clay@compass.com",
    "meeting_timestamp": "2025-05-25 14:00:00",
    "meeting_description": "Compass - ESG Ratings Dashboard Review",
}

result = compiled_graph.invoke(init_state)
summary_client_comms = result["summary_client_comms"]
fin_hold_summary_sourced= result["fin_hold_summary_sourced"]
client_news_summary_sourced= result["client_news_summary_sourced"]
meeting_category = result["meeting_category"]
# full_report = summary + "\n\n### Macro Financial Snapshot\n\n" + macro_table

print("meeting_category: ", meeting_category)
print("--------------------------------------------------------------")
print("Client Communications Summary: ", summary_client_comms)
print("--------------------------------------------------------------")
print("Financial Holdings News Summary: ", fin_hold_summary_sourced)
print("--------------------------------------------------------------")
print("Client Company News Summary: ", client_news_summary_sourced)

===============================
Generating report with the following preferences:
 Holdings Detail: none
 Client News Detail: none
 Macro News Detail: none
 Past Meeting Detail: short
 Meeting topic: ESG Investing
===============================

meeting_category:  ESG Investing
--------------------------------------------------------------
Client Communications Summary:  • Review of Compass's ESG fund portfolio performance against its benchmark.
• Discussion of structured timing and treatment options within the ESG investment strategy.
• Analysis of capital allocation and milestone mapping for ESG investments.
• Examination of stress testing scenarios relevant to the ESG portfolio.
• Confirmation that the current facility is operating smoothly.
--------------------------------------------------------------
Financial Holdings News Summary:
--------------------------------------------------------------
Client Company News Summary:

In [3]:
init_state = {
    "user_email" : "jane.moneypenny@bankwell.com",
    "client_name": "Lisa Kennedy",
    "client_email": "lisa.kennedy@lockheedmartincorporation.com",
    "meeting_timestamp": "2022-04-04 11:00:00",
    "meeting_description": "Lockheed Martin - Updated ESG Capabilities Presentation",
}

result = compiled_graph.invoke(init_state)
summary_client_comms = result["summary_client_comms"]
fin_hold_summary_sourced= result["fin_hold_summary_sourced"]
client_news_summary_sourced= result["client_news_summary_sourced"]
meeting_category = result["meeting_category"]
# full_report = summary + "\n\n### Macro Financial Snapshot\n\n" + macro_table

print("meeting_category: ", meeting_category)
print("--------------------------------------------------------------")
print("Client Communications Summary: ", summary_client_comms)
print("--------------------------------------------------------------")
print("Financial Holdings News Summary: ", fin_hold_summary_sourced)
print("--------------------------------------------------------------")
print("Client Company News Summary: ", client_news_summary_sourced)

===============================
Generating report with the following preferences:
 Holdings Detail: full
 Client News Detail: full
 Macro News Detail: full
 Past Meeting Detail: full
 Meeting topic: ESG Investing
===============================

meeting_category:  ESG Investing
--------------------------------------------------------------
Client Communications Summary:  **Lockheed Martin - Updated ESG Capabilities Presentation: Briefing Document**

**1. Past Email Summary**

Bankwell Financial and Lockheed Martin have engaged in several email exchanges regarding pension fund investments.  Bankwell initially proposed assistance with liability-driven investing (LDI), prompting interest from Lockheed Martin and a Bankwell presentation.  While Lockheed Martin didn't have an immediate need, they added Bankwell to their list of potential future LDI managers. Subsequent communication included Bankwell sharing an economic outlook report emphasizing ESG considerations and alternative investments, which Lockheed Martin noted as a growing concern. Finally, Bankwell provided an update on interest rate shifts' impact on LDI, information which Lockheed Martin circulated internally.  This indicates Lockheed Martin's interest in Bankwell's expertise, particularly concerning ESG integration, even without an immediate LDI mandate.


**2. Recent Email Topics**

* Update on the impact of significant interest rate shifts on pension LDI strategies, including effects on funded status and liability valuations.
* Reports and commentary on current pension fund management trends, focusing on ESG considerations and alternative investments.
* Lockheed Martin's confirmation of receipt and inclusion of Bankwell Financial on their list of potential future LDI managers.


**3. Recent Client Questions**

1. What are the potential implications for pension LDI strategies given recent significant interest rate shifts?
2.  What are the factors that would lead to Lockheed Martin engaging Bankwell as their LDI manager in the future? (Implicit question regarding future engagement criteria)
--------------------------------------------------------------
Financial Holdings News Summary:  Lisa Kennedy's portfolio includes holdings in Nvidia (NVDA), Exxon Mobil (XOM), Intel (INTC), Bank of America (BAC), and Walmart (WMT).  Nvidia has shown exceptional growth, with shares climbing 83% since early April, driven by resumed chip sales to China, although concerns about future competition exist.<sup><a href="https://uk.finance.yahoo.com/news/nvda-nvidia-ai-boom-sparks-122012543.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/analyst-says-nvidia-nvda-see-120219949.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/nvidia-nvda-gets-green-light-193656433.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup> Exxon Mobil, despite underperforming the S&P 500 over the past year, boasts robust production growth and high-value assets.<sup><a href="https://finance.yahoo.com/news/top-analyst-reports-exxon-mobil-204800571.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/top-research-reports-exxon-mobil-202600539.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/exxonmobil-one-largest-energy-companies-194500925.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup> Intel's stock has declined 33.8% over the past 52 weeks but shows signs of a potential short-term rally.<sup><a href="https://finance.yahoo.com/news/what-you-need-to-know-ahead-of-intels-earnings-release-112831007.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://ca.finance.yahoo.com/news/intel-shares-could-squeeze-higher-125409729.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup> Bank of America reported stronger-than-expected Q2 2025 results, though analyst opinions remain mixed following a large stake sale.<sup><a href="https://finance.yahoo.com/news/market-missing-bank-americas-strong-173644687.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://uk.finance.yahoo.com/news/bank-america-corp-bac-q2-070236049.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.wsj.com/finance/banking/bank-of-america-reports-increase-in-second-quarter-profit-585dbe50" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  Walmart demonstrates strong performance, described by some as "the Nvidia of retail," despite recent stock offloading by the Walton family. The overall economic climate presents mixed signals, with concerns about recession, inflation (core CPI at 2.7% annually), and tariffs offset by positive indicators like record retail sales.<sup><a href="https://finance.yahoo.com/news/the-real-risk-of-a-recession-and-other-key-points-about-the-us-economy-right-now-164822925.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.bloomberg.com/news/newsletters/2025-07-18/markets-may-be-too-complacent-about-inflation-money-distilled?srnd=homepage-europe" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/us-economy-dangerously-vulnerable-to-recession-wall-street-reacts-to-tariff-fallout-155837444.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  This creates an uncertain environment for the performance of her investments.
--------------------------------------------------------------
Client Company News Summary:  Recent news highlights Lockheed Martin's strong financial performance and significant industry activity.<sup><a href="https://finance.yahoo.com/news/lockheed-martin-too-big-fail-085453048.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.reuters.com/markets/companies/LMT.N/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/lockheed-martin-strong-dividend-stock-140253827.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  The company reported better-than-expected first-quarter 2025 results, with a 4% year-over-year revenue increase to $18 billion.<sup><a href="https://finance.yahoo.com/news/lockheed-martin-too-big-fail-085453048.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  This positive financial performance is underscored by a recently declared quarterly dividend of $3.30 per share.<sup><a href="https://finance.yahoo.com/news/lockheed-martin-strong-dividend-stock-140253827.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  Lockheed Martin continues to be a major player in the defense sector, delivering 72 F-35 jets (though facing some upgrade delays), and securing a substantial $11.76 billion contract for the production and delivery of an additional 145 F-35 jets.<sup><a href="https://www.reuters.com/markets/companies/LMT.N/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://ca.finance.yahoo.com/news/lockheed-martin-delivers-72-f-230117192.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://finance.yahoo.com/news/lockheed-martin-secures-11-8-130900014.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  Furthermore,  the company is expanding its production capabilities, including a new facility to expand F-35 component production and a planned missile and rocket manufacturing center in Germany in collaboration with Rheinmetall.<sup><a href="https://www.reuters.com/article/business/lockheed-martin-says-to-expand-production-for-components-of-f-35-lightning-ii-idUSFWN1H00IT/" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup><sup><a href="https://www.morningstar.com/news/dow-jones/202504303260/rheinmetall-lockheed-martin-team-up-to-produce-missiles-in-germany" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  Increased demand for defense products in Europe is anticipated to further drive growth.<sup><a href="https://finance.yahoo.com/news/analyst-says-buying-lockheed-martin-192406456.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>  While some analysts express concerns about potential future challenges, the overall trend suggests continued strong performance and significant activity within the aerospace and defense industry.<sup><a href="https://finance.yahoo.com/news/lockheed-martin-corporation-nyse-lmt-171840959.html" target="_blank" title="Open Source" style="text-decoration:none; font-size:0.6em; color:inherit; margin-left:0.5px;">🔗</a></sup>