In [7]:
from google.cloud import secretmanager
import pandas as pd
import numpy as np
from currensee.utils.db_utils import create_pg_engine
from sqlalchemy import text

import pandas as pd
import random
import os
import re
from faker import Faker

In [8]:
# Update dates to all be in 2025
# Update preference changes to all be more recent to still show variation

In [3]:
# Define DB_NAME
DB_NAME = "crm_outlook"

In [4]:
engine = create_pg_engine(db_name=DB_NAME)

In [5]:
pd.set_option('display.max_colwidth', None)

In [23]:
df1 = pd.read_sql("""SELECT * FROM meeting_data 
where host_email ='jane.moneypenny@bankwell.com' 
order by meeting_timestamp desc Limit 20""", con=engine)
df1.head(20)

,index,meeting_timestamp,host,host_email,invitees,invitee_emails,meeting_subject
0,94.0,2025-07-10 14:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss Portfolio Diversification and Risk Strategy
1,NaN,2025-06-29 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Operational Risk Case Study Analysis
2,NaN,2025-06-28 15:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Guardant Health - Social Governance Strategy Benchmarking
3,NaN,2025-06-28 15:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Michelle Jenkins,michelle.jenkins@intuitivesurgical.com,Intuitive Surgical - Alternative Investment Tax Structures
4,NaN,2025-06-28 09:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - Financial Goals & Resource Planning
5,NaN,2025-06-27 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - Innovative Funds & Investment Outlook
6,NaN,2025-06-27 09:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Amy Winters,amy.winters@gamestopcorp.com,GameStop Corp - Treasury Strategy & Finance Objectives
7,NaN,2025-06-25 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Emerging Market Growth vs. Headwinds
8,NaN,2025-06-24 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Guardant Health - Diversified Fund Comparison Walkthrough
9,NaN,2025-06-24 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Liquidity & Daily Redemption Strategies
10,NaN,2025-06-23 12:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - ESG Trends & Fund Flow Insights
11,NaN,2025-06-22 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Mid-Year Objective Adjustment Review
12,NaN,2025-06-22 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Kyle Waters,kyle.waters@amedisys.com,Amedisys - Impact Investing & Green Bond Opportunities
13,NaN,2025-06-18 09:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jennifer Phelps,jennifer.phelps@aerovironment.com,AeroVironment - FX & Interest Rate Risk Strategy Review
14,NaN,2025-06-18 09:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Amy Winters,amy.winters@gamestopcorp.com,GameStop Corp - State-Level Regulatory Insights
15,NaN,2025-06-16 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - Tax Across Jurisdictions Alignment
16,NaN,2025-06-16 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - AML Requirements & Policy Developments
17,NaN,2025-06-15 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Alternative Credit & Private Credit Strategy
18,NaN,2025-06-14 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jennifer Phelps,jennifer.phelps@aerovironment.com,AeroVironment - Inflation & Rate Forecast Scenario
19,NaN,2025-06-14 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - Implementation Timeline & Fit Review

## Hasbro

In [39]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE meeting_data 
        SET meeting_timestamp = '2025-12-11 11:00:00'
        WHERE host_email = 'jane.moneypenny@bankwell.com'
          AND invitee_emails = 'jessica.palmer@hasbro.com'
          AND TRIM(meeting_timestamp) = '2023-12-11 11:00:00' 
    """))

In [54]:
df1 = pd.read_sql("""SELECT * FROM meeting_data 
where host_email ='jane.moneypenny@bankwell.com' and invitee_emails = 'jessica.palmer@hasbro.com'
order by meeting_timestamp desc""", con=engine)
df1.head(30)

,index,meeting_timestamp,host,host_email,invitees,invitee_emails,meeting_subject
0,94.0,2025-07-10 14:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss Portfolio Diversification and Risk Strategy
1,NaN,2025-05-17 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - ESG Integration Framework & Screening
2,NaN,2025-05-01 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Strategic Targets Rollout Discussion
3,NaN,2025-03-29 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Operational Risk Case Study Analysis
4,81.0,2025-02-11 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Finalize H1 2024 FX Hedging Strategy
5,NaN,2024-06-25 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Emerging Market Growth vs. Headwinds
6,NaN,2024-06-24 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Liquidity & Daily Redemption Strategies
7,NaN,2024-05-16 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Fit vs. Mandate: Benchmark Transition
8,NaN,2024-05-03 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Bonus Deferral & Reporting Optimization
9,NaN,2024-05-01 12:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Disclosure Timeline Revision Review
10,67.0,2023-01-10 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss H1 2023 FX Hedging Strategy
11,8.0,2018-11-14 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss FX Risk Management Strategies (Forwards vs. Options)

In [86]:
with engine.begin() as connection:  # to jane from jessica
    connection.execute(text("""
        UPDATE email_data
        SET email_timestamp = '2025-05-13 09:13:00' 
        , email_subject = 'Hasbro - ESG Integration Framework & Screening'
        , to_names = 'Jane Moneypenny'
        , to_emails = 'jane.moneypenny@bankwell.com' 
        , from_name = 'Jessica Palmer'
        , from_email = 'jessica.palmer@hasbro.com'
        , email_body = 'Hi Jane, Great thank you for diving into this for us. Look forward to discussing further.  --Jessica'
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com')
          AND from_email in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com')
          AND TRIM(email_timestamp) = '2025-04-29 20:00:00' 
    """))

In [89]:
with engine.begin() as connection:  # to jessica from jane
    connection.execute(text("""
        UPDATE email_data
        SET email_timestamp = '2025-04-26 20:00:00' 
        , email_subject = 'Hasbro - ESG Integration Framework & Screening'
        , to_names = 'Jessica Palmer'
        , to_emails = 'jessica.palmer@hasbro.com'
        , from_name = 'Jane Moneypenny'
        , from_email = 'jane.moneypenny@bankwell.com' 
        , email_body = 'Hi Jessica, I hope you are doing well. I am reaching out to schedule time to discuss the Strategic Targets Rollout in the context of Hasbros current investment strategy and recent shifts in the market landscape.  With continued volatility across rates, supply chains showing signs of stabilization, and sector rotations picking up momentum, its an opportune moment to revisit allocation targets and identify areas where we can position more proactively for the next 6–12 months. During our conversation, I would like to walk through a few potential adjustments based on current macro indicators—particularly around consumer cyclicals, credit exposure, and emerging market positioning. I will also bring updated risk/return projections to support any discussions with the board. Would early next week work for a 45-minute call? Happy to tailor the agenda if there are specific themes you would like to prioritize. Looking forward to catching up.  Best, Jane'
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com')
          AND from_email in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com')
          AND TRIM(email_timestamp) = '2025-04-29 20:00:00' 
    """))

In [90]:
df = pd.read_sql("""SELECT *
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com') 
        order by email_timestamp desc""", con=engine)
df.head(30)

,index,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,258.0,2025-07-10 09:10:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica, Great, I will schedule us for 2:30 on the 10th. Best regards, Jane Moneypenny; Financial Advisor; Bankwell Financial; Phone: (555) 123-4567; Email: jane.moneypenny@outlook.com"
1,257.0,2025-07-09 16:10:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi jane, Yes, this needs further thought. I can do 1-5pm tomorrow, or 9am on the 13th. Let me know which works for you. Regards, Jessica Palmer, VP Hasbro Email: jessica.palmer@hasbro.com Phone: 909.878.8329x31984"
2,256.0,2025-07-09 13:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica, I will have our research team further look into small-cap consumer entertainment trends, but from what I have seen in the news I dont believe conditions will shift impactfully before end of year. I suggest we meet soon to have an in depth discussion of the impact of Hasbros risk strategy post divestiture and bond fund allocation. Best, Jane"
3,255.0,2025-07-08 09:40:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Thanks Jane,\n\nThank you for the update. Seems like we need to reevaluate our strategy. I am hesitant to change much at this moment given the likely update to senior leadership. Do you believe that current market trends will continue regarding small-cap consumer entertainment? \n\n Also, I am curious about our allocation in bond funds. Given current inflation, what is the likely impact on the bond market, i.e. should we consider moving further out of bonds? \n\nRegards,\n\n--\nJessica Palmer\nVP\nHasbro\nEmail: jessica.palmer@hasbro.com\nPhone: 909.878.8329x31984\n"
4,254.0,2025-07-06 08:05:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica, I am reaching out regarding Hasbros Q3 goals. I understand that the recent divestitures have been completed. I ran a quick comparative performance check across your key equity positions. Your exposure to small-cap consumer entertainment stocks underperformed the S&P benchmark by roughly 2.3% over the last 6 weeks. That said, your positions in structured notes tied to diversified consumer indexes helped buffer some of the downside. We can explore reallocating a portion of your discretionary sector holdings to lower beta instruments or consider sector-rotation strategies if you would like. We can wait further to see how things evolve, but worth considering an adjustment in the nearterm based on market trends. Best regards, Jane Moneypenny, Financial Advisor, Bankwell Financial, Phone: (555) 123-4567, Email: jane.moneypenny@outlook.com"
5,NaN,2025-05-13 09:13:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - ESG Integration Framework & Screening,"Hi Jane, Great thank you for diving into this for us. Look forward to discussing further. --Jessica"
6,NaN,2025-05-12 15:04:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - ESG Integration Framework & Screening,"Hi Jessica, Okay great, I believe most of those will be easy to include off-the-shelf from our current report portfolio, but some will need to be custom developed, particularly the YoY emissions trends. I can set up a meeting for us to discuss further. Best, Jane"
7,NaN,2025-05-12 12:46:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - ESG Integration Framework & Screening,"Hi Jane, Thank you for the update on the carbon impact dashboard—its exactly the type of transparency and data-driven approach we have been looking for. I would like to include a few specific KPIs that would be particularly relevant for Hasbros board review: 1) Portfolio carbon intensity vs. industry benchmarks (especially within consumer products and manufacturing sectors). 2) Progress toward science-based emissions reduction targets (aligned with SBTi, if available). 3) Percentage of investments in companies with net-zero or formal ESG commitments. 4) Year-over-year emissions trend analysis at both the portfolio and sector level. Additionally, I think routine monitoring and reporting will be key. Could we set up a quarterly summary that we can present to the board? Ideally, it would include both a dashboard snapshot and a brief narrative on any significant changes or high-impact areas. Many thanks, Jessica"
8,NaN,2025-05-10 17:55:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - ESG Integration Framework & Screening,"Hi Jessica, Great to hear that the strategic rollout went over well with the board. We can absolutely set up a dashboard focused on Carbon impacts of your investments, this is one of Bankwells specialties. Our dashboards allow you to view metrics like carbon intensity per $1M invested, sector-level breakdowns, and historical emissions trends. This will help inform future allocation decisions and align your portfolio more closely with your sustainability objectives. Let me know if there are any specific KPIs or thresholds you would like us to include. Best, Jane"
9,NaN,2025-05-10 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - ESG Integration Framework & Screening,"Hi Jane, Great chatting with you last week. The strategic targets went over well with the board, except for a lack of focus on ESG priorities. I think we need to support from bankwell in how to monitor how carbon friendly our investments are. I remember in the past we spoke about ESG dashboards that you make for other clients. What research does bankwell have on carbon impacts of our funds? Many thanks, Jessica"
10,NaN,2025-05-01 20:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Bonus Deferral & Reporting Optimization,"Dear Jessica Palmer,\n\nStructured timing and treatment options overview.\n\nBest,\nJane"
11,NaN,2025-05-01 00:15:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Strategic Targets Rollout Discussion,"Hi Jessica Palmer,\n\nCapital allocation and milestone mapping.\n\nCheers,\nJane"
12,NaN,2025-04-26 20:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - ESG Integration Framework & Screening,"Hi Jessica, I hope you are doing well. I am reaching out to schedule time to discuss the Strategic Targets Rollout in the context of Hasbros current investment strategy and recent shifts in the market landscape. With continued volatility across rates, supply chains showing signs of stabilization, and sector rotations picking up momentum, its an opportune moment to revisit allocation targets and identify areas where we can position more proactively for the next 6–12 months. During our conversation, I would like to walk through a few potential adjustments based on current macro indicators—particularly around consumer cyclicals, credit exposure, and emerging market positioning. I will also bring updated risk/return projections to support any discussions with the board. Would early next week work for a 45-minute call? Happy to tailor the agenda if there are specific themes you would like to prioritize. Looking forward to catching up. Best, Jane"
13,259.0,2023-12-12 11:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Thanks Jane,\n\nI will follow up if I have any issues. Happy holidays! \n\nRegards,\n\n--\nJessica Palmer\nVP\nHasbro\nEmail: jessica.palmer@hasbro.com\nPhone: 909.878.8329x31984\n"
14,253.0,2023-12-12 10:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Hi Jessica,\n\nGreat to speak with you yesterday. I have executed the FX Hedging strategy we discussed, and adjusting for a more conservativre risk profile. Please elt me know if you have any further questions. You can see the adjusted portfolio in your customer portal. I reccomend we check in again in Q1 next year to evaluate strategy after Hasbro's potential divestitures have been completed. \n\n Hope you enjoy time off over the holiday season! \n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
15,246.0,2023-11-22 10:45:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Hi Jessica,\n\nDecember 11th at 11 AM ET works. I'll send the invite and prepare some strategy considerations.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
16,245.0,2023-11-22 10:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Hi Jane,\n\nYes, let's connect. How about December 11th at 11 AM ET?\n\nRegards,\n\n--\nJessica Palmer\nVP\nHasbro\nEmail: jessica.palmer@hasbro.com\nPhone: 909.878.8329x31984\n"
17,244.0,2023-11-21 15:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Hi Jessica,\n\nFollowing up on our call earlier this month regarding the H1 2023 hedge performance. Let's schedule time to finalize the FX hedging strategy for H1 2024.\n\nMarket conditions continue to evolve, so we should review Hasbro's objectives and risk tolerance. Please let me know your availability in early December.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
18,NaN,2023-06-29 07:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Operational Risk Case Study Analysis,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nWould you prepare for FX exposure discussion?\n\nThanks,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
19,NaN,2023-06-29 07:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Operational Risk Case Study Analysis,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nWould you prepare for FX exposure discussion?\n\nThanks,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
20,NaN,2023-06-25 12:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Emerging Market Growth vs. Headwinds,"Dear Jane,\n\nThank you for your email. Jane,\n\nGeopolitical risk implications?\n\nBest,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
21,NaN,2023-06-25 12:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Emerging Market Growth vs. Headwinds,"Dear Jane,\n\nThank you for your email. Jane,\n\nGeopolitical risk implications?\n\nBest,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
22,NaN,2023-06-24 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Liquidity & Daily Redemption Strategies,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nDetails on growth fund launches?\n\nThanks,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
23,NaN,2023-06-24 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Liquidity & Daily Redemption Strategies,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nDetails on growth fund launches?\n\nThanks,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
24,NaN,2023-05-17 12:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - ESG Integration Framework & Screening,"Dear Jane,\n\nThank you for your email. Dear Jane,\n\nInsights on sustainability mandates?\n\nRegards,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
25,NaN,2023-05-17 12:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - ESG Integration Framework & Screening,"Dear Jane,\n\nThank you for your email. Dear Jane,\n\nInsights on sustainability mandates?\n\nRegards,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
26,NaN,2023-05-16 08:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Fit vs. Mandate: Benchmark Transition,"Dear Jane,\n\nThank you for your email. Hello Jane,\n\nComparison of new vs old benchmarks?\n\nThanks,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
27,NaN,2023-05-16 08:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Fit vs. Mandate: Benchmark Transition,"Dear Jane,\n\nThank you for your email. Hello Jane,\n\nComparison of new vs old benchmarks?\n\nThanks,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
28,NaN,2023-05-02 12:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Bonus Deferral & Reporting Optimization,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nSuggestions for bonus deferral reporting?\n\nCheers,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
29,NaN,2023-05-02 12:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Bonus Deferral & Reporting Optimization,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nSuggestions for bonus deferral reporting?\n\nCheers,\nJessica Palmer\n\nBest regards,\nJessica Palmer"

In [13]:
df = pd.read_sql("""SELECT email_timestamp
        , to_names	
        , to_emails
        , from_name
        , from_email
        , email_subject
        , email_body
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'roberto.martin@guardanthealth.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'roberto.martin@guardanthealth.com') 
        order by email_timestamp desc
        """, con=engine)
df.head(10)

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2025-06-28 14:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Re: Guardant Health - Social Governance Strategy Benchmarking,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nCan we review ESG fund performance?\n\nThanks,\nRoberto Martin\n\nBest regards,\nRoberto Martin"
1,2025-06-28 14:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Re: Guardant Health - Social Governance Strategy Benchmarking,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nCan we review ESG fund performance?\n\nThanks,\nRoberto Martin\n\nBest regards,\nRoberto Martin"
2,2025-06-28 11:00:00,Roberto Martin,roberto.martin@guardanthealth.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Guardant Health - Social Governance Strategy Benchmarking,"Dear Roberto Martin,\n\nReviewing ESG fund portfolio and benchmark.\n\nBest,\nJane"
3,2025-06-24 09:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Re: Guardant Health - Diversified Fund Comparison Walkthrough,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nLiquidity terms for new funds?\n\nCheers,\nRoberto Martin\n\nBest regards,\nRoberto Martin"
4,2025-06-24 09:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Re: Guardant Health - Diversified Fund Comparison Walkthrough,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nLiquidity terms for new funds?\n\nCheers,\nRoberto Martin\n\nBest regards,\nRoberto Martin"
5,2025-06-23 03:00:00,Roberto Martin,roberto.martin@guardanthealth.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Guardant Health - Diversified Fund Comparison Walkthrough,"Hi Roberto Martin,\n\nLow-volatility fund enhancements.\n\nCheers,\nJane"
6,2025-06-10 08:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Re: Guardant Health - Liquidity Risk & Funding Contingencies,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nAny market risk scenario updates?\n\nCheers,\nRoberto Martin\n\nBest regards,\nRoberto Martin"
7,2025-06-10 08:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Re: Guardant Health - Liquidity Risk & Funding Contingencies,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nAny market risk scenario updates?\n\nCheers,\nRoberto Martin\n\nBest regards,\nRoberto Martin"
8,2025-06-10 05:00:00,Roberto Martin,roberto.martin@guardanthealth.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Guardant Health - Liquidity Risk & Funding Contingencies,"Hello Roberto Martin,\n\nStress testing scenarios walkthrough.\n\nRegards,\nJane"
9,2025-06-09 22:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Re: Guardant Health - Cross-Asset Volatility & Correlation,"Dear Jane,\n\nThank you for your email. Hello Jane,\n\nCommodity price forecasts?\n\nThanks,\nRoberto Martin\n\nBest regards,\nRoberto Martin"

## Compass

In [53]:
df1 = pd.read_sql("""SELECT * FROM meeting_data 
where host_email ='jane.moneypenny@bankwell.com' and invitee_emails = 'adam.clay@compass.com'
order by meeting_timestamp desc Limit 20""", con=engine)
df1.head(20)

,index,meeting_timestamp,host,host_email,invitees,invitee_emails,meeting_subject
0,NaN,2025-06-16 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - AML Requirements & Policy Developments
1,NaN,2025-05-25 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - ESG Ratings Dashboard Review
2,NaN,2025-05-21 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Charitable Deduction & Gift Strategy
3,NaN,2025-05-17 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Capital Allocation & Milestone Mapping
4,NaN,2025-05-17 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Strategic Risk Metrics & Tolerance Review
5,NaN,2025-03-17 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Geopolitical Risks & Global Supply Effects
6,NaN,2025-03-16 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Tracking Error & Volatility Shift Study
7,NaN,2025-02-06 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Low-Volatility Fund Enhancements
8,93.0,2024-03-26 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Annual Credit Facility Review Meeting
9,51.0,2021-10-01 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Credit Facility Documentation Final Review Call
10,34.0,2020-09-15 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Credit Facility Term Sheet Follow-up Discussion
11,18.0,2019-09-17 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Credit Facility Term Sheet Review
12,5.0,2018-09-25 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Discuss Expansion Financing Needs

In [47]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE meeting_data 
        SET meeting_timestamp = '2025-02-06 10:00:00'
        WHERE host_email = 'jane.moneypenny@bankwell.com'
          AND invitee_emails = 'adam.clay@compass.com'
          AND TRIM(meeting_timestamp) = '2025-06-01 13:00:00' 
    """))

In [52]:
df = pd.read_sql("""SELECT *
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'adam.clay@compass.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'adam.clay@compass.com') 
        --and email_timestamp < '2025-05-30 11:00:00'
        order by email_timestamp desc
        """, con=engine)
df.head(30)

,index,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,NaN,2025-06-14 20:15:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - AML Requirements & Policy Developments,"Hi Adam, I am happy to discuss. I will have our research team pull together a briefing on AML requirements. I know there is increased scrutiny around Real Estate in particular. I will set a meeting shortly for us to go over Compass policy together. Thanks, Jane"
1,1.0,2025-06-14 18:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - AML Requirements & Policy Developments,"Jane, I saw an update in regulations from the SEC on AML. Compass legal team has some updated policies on funds documentation to comply that I would like to make sure we are using going forward. Have you heard of any other AML regulation updates we should be aware of? Thanks, Adam"
2,NaN,2025-06-11 08:15:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Tracking Error & Volatility Shift Study,"Hi Adam, Wanted to let you know that we resolved the tracking error in the Volatility Shift Study. Apologies for any inconvenience. Many thanks, Jane"
3,NaN,2025-06-09 16:30:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Geopolitical Risks & Global Supply Effects,"Hello Adam Clay,\n\nFed policy divergence and trajectory review.\n\nRegards,\nJane"
4,NaN,2025-05-30 16:00:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Low-Volatility Fund Enhancements,"Hi Adam, Please see attached our Volatility Shift Study. We see reduced volatility compared to Q1 now that the new administration has calmed down. We have added to our offerings of low-volatility funds, which may be of interest to Compass. Many thanks, Jane"
5,NaN,2025-05-23 22:45:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - ESG Ratings Dashboard Review,"Hi Adam, I will gather a list of updated stocks in the CSI index for us to review when we meet. Im asking Ryan to get you an updated link to the dashboard as well. Look forward to speaking soon, Jane"
6,1.0,2025-05-21 09:47:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - ESG Ratings Dashboard Review,"Hi Jane, Thank you for bringing this to my attention. I know our board is particularly concerned with the Carbon Score index on the dashboard. Which stocks have been added to the CSI index that were not there previously? Thanks, Adam"
7,NaN,2025-05-21 06:15:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - ESG Ratings Dashboard Review,"Hi Adam, Hope you are doing well. I wanted to reach out to alert you to changes in the S&P 500 Carbon Efficient Index that may impact our ESG dashboard. I know you have been a frequent user of the dashboard in the past. I scheduled a meeting to walk through how Carbon Index is reflected on the ESG Ratings Dashboard, and discuss other ESG concerns. Many thanks, Jane"
8,NaN,2025-05-17 03:15:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Capital Allocation & Milestone Mapping,"Hi Adam Clay,\n\nCapital allocation and milestone mapping.\n\nCheers,\nJane"
9,NaN,2025-05-15 19:00:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Strategic Risk Metrics & Tolerance Review,"Hello Adam Clay,\n\nStress testing scenarios walkthrough.\n\nRegards,\nJane"
10,237.0,2023-09-29 14:00:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Utilizing the Credit Facility,"Hi Adam,\n\nHope you're well. Just checking in now that the credit facility has been in place for a while.\n\nAre you finding the process for drawdowns and reporting satisfactory? Please let me know if you or your team need any assistance or have feedback on using the line.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
11,194.0,2022-10-06 10:00:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Credit Facility Closed,"Hi Adam,\n\nGreat news - confirming that the $25M revolving credit facility for Compass officially closed and funded this morning.\n\nIt was a pleasure working with you and your team to get this finalized. Please don't hesitate to reach out if any questions arise as you begin utilizing the facility. Our loan operations team is also available for any administrative support.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
12,151.0,2021-09-29 10:15:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Compass - Credit Facility Documentation Status,"Hi Adam,\n\nSounds good. We'll prepare for a potential closing next Wednesday and await your final confirmation.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
13,149.0,2021-09-28 15:30:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Credit Facility Documentation Status,"Hi Adam,\n\nHope the documentation review for the credit facility is progressing well on your side. Our legal team has incorporated the comments from your counsel's last turn.\n\nAre there any final points to address before we target execution and closing, perhaps next week?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
14,104.0,2020-09-21 11:45:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Compass - Credit Facility Next Steps,"Hi Adam,\n\nExcellent news. I'll instruct our legal counsel and loan operations team to begin drafting immediately. Typically, we can provide initial drafts within 5-7 business days. I'll keep you updated on the progress.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
15,102.0,2020-09-17 15:00:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Credit Facility Next Steps,"Hi Adam,\n\nFollowing up on our call last week regarding the proposed credit facility term sheet. You mentioned needing to finalize internal approvals.\n\nJust checking in on the status and if there are any outstanding questions from your legal or finance teams that I can help address. We're ready to move to definitive documentation when you are.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
16,61.0,2019-09-10 14:45:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Credit Facility Term Sheet,"Hi Adam,\n\nFollowing our discussions and review of Compass's preliminary financials, please find attached the indicative term sheet for the proposed $25M revolving line of credit.\n\nThis outlines the key terms, conditions, indicative pricing, and proposed covenants. Please review with your team, and I'm available to discuss any points in detail.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
17,14.0,2018-09-18 13:30:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Meeting Request: Compass Expansion Financing,"Hi Adam,\n\nExcellent. Tuesday at 10 AM ET is confirmed. I'll send a calendar invite. I look forward to learning more about Compass's plans.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
18,13.0,2018-09-18 13:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Re: Meeting Request: Compass Expansion Financing,"Hi Jane,\n\nGood timing. Yes, we are evaluating options for a new credit facility. I can chat next Tuesday morning. Does 10 AM ET work?\n\nRegards,\n\n--\nAdam Clay\nVP\nCompass\nEmail: adam.clay@compass.com\nPhone: -2931\n"
19,12.0,2018-09-18 09:00:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Meeting Request: Compass Expansion Financing,"Hi Adam,\n\nHope you're having a good week. I wanted to follow up on our brief chat at the Real Estate Finance conference last month regarding Compass's potential need for expansion capital.\n\nBankwell Financial offers various financing solutions, including lines of credit and term loans tailored for growth companies. Would you be available for a call next week to discuss your potential needs and how we might assist?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"

In [51]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE email_data
        SET email_body = 'Hi Adam, Please see attached our Volatility Shift Study. We see reduced volatility compared to Q1 now that the new administration has calmed down. We have added to our offerings of low-volatility funds, which may be of interest to Compass.  Many thanks, Jane'
        WHERE to_emails = 'adam.clay@compass.com'
          AND from_email = 'jane.moneypenny@bankwell.com'
          AND TRIM(email_timestamp) = '2025-05-30 16:00:00' 
    """))

In [44]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE email_data
        SET email_body = 'Jane, I saw an update in regulations from the SEC on AML. Compass legal team has some updated policies on funds documentation to comply that I would like to make sure we are using going forward. Have you heard of any other AML regulation updates we should be aware of? Thanks, Adam'
        WHERE to_emails = 'jane.moneypenny@bankwell.com'
          AND from_email = 'adam.clay@compass.com'
          AND TRIM(email_timestamp) = '2025-06-14 18:15:00' 
    """))

In [33]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""INSERT INTO email_data (index	
    , email_timestamp
    , to_names
    , to_emails
    , from_name	
    , from_email
    , email_subject	
    , email_body)
VALUES (1
, '2025-05-21 09:47:00'
, 'Jane Moneypenny'
, 'jane.moneypenny@bankwell.com'
, 'Adam Clay'
, 'adam.clay@compass.com'
, 'Compass - ESG Ratings Dashboard Review'
, 'Hi Jane, Thank you for bringing this to my attention. I know our board is particularly concerned with the Carbon Score index on the dashboard. Which stocks have been added to the CSI index that were not there previously? Thanks, Adam'
)"""))

In [15]:
df2 = pd.read_sql("""SELECT email_timestamp
        , to_names	
        , to_emails
        , from_name
        , from_email
        , email_subject
        , email_body
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'lisa.kennedy@lockheedmartincorporation.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'lisa.kennedy@lockheedmartincorporation.com') 
        order by email_timestamp desc
        """, con=engine)
df2.head(20)

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2023-03-15 14:00:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Lockheed Martin - Inquiry: Bankwell ESG Investment Capabilities,"Hi Lisa,\n\nCertainly. For early April, how about April 4th at 11 AM ET or April 6th at 1 PM ET?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
1,2023-03-15 13:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Lockheed Martin - Inquiry: Bankwell ESG Investment Capabilities,"Hi Jane,\n\nYes, an updated presentation focused on your ESG capabilities would be timely, as our committee continues to evaluate this area. Can you propose some times in early April?\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
2,2023-03-14 11:00:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Lockheed Martin - Inquiry: Bankwell ESG Investment Capabilities,"Hi Lisa,\n\nHope you're well. Following up on our brief discussion last year about ESG considerations in pension management.\n\nBankwell has continued to expand its capabilities in ESG-integrated investment strategies across various asset classes. Would you be open to a brief, updated presentation focused specifically on our ESG offerings for institutional clients like Lockheed Martin's pension plan?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
3,2022-03-09 10:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Lockheed Martin - Update on Interest Rate Environment & LDI,"Hi Jane,\n\nThank you for sharing the update on the rate environment. It's certainly a dynamic period for LDI management. I'll share this with our internal team and consultants.\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
4,2022-03-08 14:30:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Lockheed Martin - Update on Interest Rate Environment & LDI,"Hi Lisa,\n\nGiven the recent significant shifts in the interest rate outlook, I wanted to provide a brief update on the potential implications for pension LDI strategies.\n\nHigher rates can impact funded status and liability valuations. The attached note provides some commentary. Happy to discuss specific implications for Lockheed Martin's plan if helpful, although I know you work with several dedicated managers.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
5,2021-02-12 13:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Lockheed Martin - Economic Update & Pension Trends,"Hi Jane,\n\nThanks for sharing these reports. I'll take a look when I have a moment. ESG is certainly a growing topic of discussion for our committee.\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
6,2021-02-11 11:30:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Lockheed Martin - Economic Update & Pension Trends,"Hi Lisa,\n\nHope you're having a good start to the year. I wanted to share our latest Bankwell economic outlook report and a piece our institutional team put together on recent trends in pension fund management, particularly around ESG considerations and alternative investments.\n\nNo action needed, just thought these might be of interest given your role. Happy to discuss any points if you'd like.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
7,2020-02-19 10:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Follow Up: Lockheed Martin LDI Presentation,"Hi Jane,\n\nThanks for following up. The presentation was informative. We don't have an active LDI manager search at this precise moment, but we've added Bankwell to our list of potential managers for future consideration when the need arises. We appreciate the information shared.\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
8,2020-02-18 14:00:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Follow Up: Lockheed Martin LDI Presentation,"Hi Lisa,\n\nI wanted to follow up after our LDI presentation earlier this month. I hope it provided a helpful overview of Bankwell's capabilities in managing fixed-income strategies for pension plans.\n\nPlease let me know if you or the pension committee have any further questions or if you'd like any additional information as you continue your manager reviews.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
9,2019-02-06 14:00:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Lockheed Martin - Pension Fund Investment Strategy,"Hi Lisa,\n\nCertainly. How about March 5th at 1 PM ET or March 7th at 10 AM ET for the presentation?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
10,2019-02-06 11:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Lockheed Martin - Pension Fund Investment Strategy,"Hi Jane,\n\nThank you for following up. LDI is a key focus for our pension committee. We typically engage with managers through formal searches, but I'm open to an introductory presentation on Bankwell's capabilities in this specific area. Can you suggest some times in early March?\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
11,2019-02-05 09:30:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Lockheed Martin - Pension Fund Investment Strategy,"Hi Lisa,\n\nFollowing our introductory discussion regarding Bankwell's institutional asset management capabilities, I wanted to explore further how we might assist with specific segments of Lockheed Martin's pension fund investments.\n\nWe have particular expertise in managing fixed-income mandates focused on liability-driven investing (LDI) principles. Would you be open to a more detailed presentation on our LDI strategies and performance?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"

# Update preference dates

In [17]:
pd.read_sql("SELECT * FROM preferences where email = 'jane.moneypenny@bankwell.com' ", con=engine)

,as_of_date,employee_first_name,employee_last_name,email,title,finance_detail,news_detail,macro_news_detail,past_meeting_detail
0,2023-01-23 10:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,full,full,full,full
1,2023-04-02 10:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,short,full,full,short
2,2023-07-26 14:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,none,none,full,short
3,2023-11-04 10:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,short,full,none,none
4,2024-01-30 10:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,short,full,none,full
5,2024-03-10 09:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,full,none,full,full
6,2025-04-03 09:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,full,full,full,full
7,2025-05-19 05:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,short,full,none,full
8,2025-06-12 09:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,full,full,full,full

In [19]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""INSERT INTO preferences (as_of_date
    , employee_first_name
    , employee_last_name
    , email
    , title
    , finance_detail
    , news_detail
    , macro_news_detail
    , past_meeting_detail)
VALUES ( '2025-05-02 09:00:00'
, 'Jane'
, 'Moneypenny'
, 'jane.moneypenny@bankwell.com'
, 'Relationship Manager'
, 'short'
, 'full'
, 'none'
, 'full'
)"""))

In [17]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""INSERT INTO preferences (as_of_date
    , employee_first_name
    , employee_last_name
    , email
    , title
    , finance_detail
    , news_detail
    , macro_news_detail
    , past_meeting_detail)
VALUES ( '2025-05-25 05:00:00'
, 'Jane'
, 'Moneypenny'
, 'jane.moneypenny@bankwell.com'
, 'Relationship Manager'
, 'full'
, 'none'
, 'full'
, 'none'
)"""))

In [19]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE preferences 
        SET finance_detail = 'full', past_meeting_detail = 'short', macro_news_detail= 'full'
        WHERE email = 'jane.moneypenny@bankwell.com'
          AND TRIM(as_of_date) = '2025-06-12 09:00:00' 
    """))

In [22]:
pd.read_sql("""SELECT as_of_date,  email
    , past_meeting_detail
    , news_detail
    , finance_detail
    , macro_news_detail
     FROM preferences where email = 'jane.moneypenny@bankwell.com' 
     and as_of_date >= '2025-04-03 09:00:00'
     order by as_of_date desc""", con=engine)

,as_of_date,email,past_meeting_detail,news_detail,finance_detail,macro_news_detail
0,2025-06-12 09:00:00,jane.moneypenny@bankwell.com,short,full,full,full
1,2025-05-25 05:00:00,jane.moneypenny@bankwell.com,none,none,full,full
2,2025-05-19 05:00:00,jane.moneypenny@bankwell.com,none,full,full,full
3,2025-05-02 09:00:00,jane.moneypenny@bankwell.com,full,full,none,none
4,2025-04-03 09:00:00,jane.moneypenny@bankwell.com,full,full,full,full

In [ ]:
# april preferences are all full 
# may 18 ish preferences are short on stuff
# mid june go back to full

# Change hasbro meetings and past emails