In [1]:
from google.cloud import secretmanager
import pandas as pd
import numpy as np
from currensee.utils.db_utils import create_pg_engine
from sqlalchemy import text

import pandas as pd
import random
import os
import re
from faker import Faker

2025-08-03 03:53:00,269 - currensee.core.secrets - INFO - PROJECT_ID not found, attempting to load from .env file
2025-08-03 03:53:00,273 - currensee.core.secrets - INFO - Loaded environment from ./.env
2025-08-03 03:53:00,274 - currensee.core.secrets - INFO - SecretManager initialized with project_id: adsp-34002-on02-sopho-scribe

In [2]:
# Update dates to all be in 2025
# Update preference changes to all be more recent to still show variation

In [3]:
# Define DB_NAME
DB_NAME = "crm_outlook"

In [4]:
engine = create_pg_engine(db_name=DB_NAME)

In [5]:
pd.set_option('display.max_colwidth', None)

In [24]:
df1 = pd.read_sql("""SELECT * FROM meeting_data 
where host_email ='jane.moneypenny@bankwell.com' 
order by meeting_timestamp desc Limit 20""", con=engine)
df1.head(20)

,index,meeting_timestamp,host,host_email,invitees,invitee_emails,meeting_subject
0,94.0,2025-07-10 14:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss Portfolio Diversification and Risk Strategy
1,NaN,2025-06-28 15:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Guardant Health - Social Governance Strategy Benchmarking
2,NaN,2025-06-28 15:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Michelle Jenkins,michelle.jenkins@intuitivesurgical.com,Intuitive Surgical - Alternative Investment Tax Structures
3,NaN,2025-06-28 09:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - Financial Goals & Resource Planning
4,NaN,2025-06-27 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - Innovative Funds & Investment Outlook
5,NaN,2025-06-27 09:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Amy Winters,amy.winters@gamestopcorp.com,GameStop Corp - Treasury Strategy & Finance Objectives
6,NaN,2025-06-24 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Guardant Health - Diversified Fund Comparison Walkthrough
7,NaN,2025-06-23 12:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - ESG Trends & Fund Flow Insights
8,NaN,2025-06-22 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Mid-Year Objective Adjustment Review
9,NaN,2025-06-22 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Kyle Waters,kyle.waters@amedisys.com,Amedisys - Impact Investing & Green Bond Opportunities
10,NaN,2025-06-18 09:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Amy Winters,amy.winters@gamestopcorp.com,GameStop Corp - State-Level Regulatory Insights
11,NaN,2025-06-18 09:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jennifer Phelps,jennifer.phelps@aerovironment.com,AeroVironment - FX & Interest Rate Risk Strategy Review
12,NaN,2025-06-16 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - Tax Across Jurisdictions Alignment
13,NaN,2025-06-16 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - AML Requirements & Policy Developments
14,NaN,2025-06-15 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Alternative Credit & Private Credit Strategy
15,NaN,2025-06-14 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jennifer Phelps,jennifer.phelps@aerovironment.com,AeroVironment - Inflation & Rate Forecast Scenario
16,NaN,2025-06-14 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - Implementation Timeline & Fit Review
17,NaN,2025-06-14 09:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - International Regulatory Coordination Update
18,NaN,2025-06-13 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - Annual Plan & Strategic Priorities
19,NaN,2025-06-12 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Kyle Waters,kyle.waters@amedisys.com,Amedisys - Fed Policy Divergence & Trajectory

## Hasbro

In [39]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE meeting_data 
        SET meeting_timestamp = '2025-12-11 11:00:00'
        WHERE host_email = 'jane.moneypenny@bankwell.com'
          AND invitee_emails = 'jessica.palmer@hasbro.com'
          AND TRIM(meeting_timestamp) = '2023-12-11 11:00:00' 
    """))

In [36]:
df1 = pd.read_sql("""SELECT * FROM meeting_data 
where host_email ='jane.moneypenny@bankwell.com' and invitee_emails = 'jessica.palmer@hasbro.com'
order by meeting_timestamp desc""", con=engine)
df1.head(30)

,index,meeting_timestamp,host,host_email,invitees,invitee_emails,meeting_subject
0,94.0,2025-07-10 14:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss Portfolio Diversification and Risk Strategy
1,NaN,2025-05-17 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - ESG Integration Framework & Screening
2,NaN,2025-05-01 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Strategic Targets Rollout Discussion
3,NaN,2025-03-29 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Operational Risk Case Study Analysis
4,81.0,2025-02-11 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Finalize H1 2024 FX Hedging Strategy
5,NaN,2024-06-25 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Emerging Market Growth vs. Headwinds
6,NaN,2024-06-24 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Liquidity & Daily Redemption Strategies
7,NaN,2024-05-16 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Fit vs. Mandate: Benchmark Transition
8,NaN,2024-05-03 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Bonus Deferral & Reporting Optimization
9,NaN,2024-05-01 12:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Disclosure Timeline Revision Review
10,67.0,2023-01-10 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss H1 2023 FX Hedging Strategy
11,8.0,2018-11-14 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss FX Risk Management Strategies (Forwards vs. Options)

In [8]:
with engine.begin() as connection:  # to jane from jessica
    connection.execute(text("""
        UPDATE email_data
        SET email_timestamp = '2025-04-27 11:43:00' 
        , email_subject = 'Hasbro - ESG Integration Framework & Screening'
        , to_names = 'Jane Moneypenny'
        , to_emails = 'jane.moneypenny@bankwell.com' 
        , from_name = 'Jessica Palmer'
        , from_email = 'jessica.palmer@hasbro.com'
        , email_body = 'Hi Jane, Thank you for reaching out. Our CFO team is starting to plan for upcoming capital needs, so I would like to review our Liquidity ratios. Given the recent volatility and our internal capital planning cycles, it’s important we understand where we might need to build flexibility or reassess exposures. Are you able to give us a updated projection of market risk of our holdings?   Thanks, Jessica'
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com')
          AND from_email in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com')
          AND TRIM(email_timestamp) = '2025-05-01 00:15:00' 
    """))

In [10]:
with engine.begin() as connection:  # to jessica from jane
    connection.execute(text("""
        UPDATE email_data
        SET email_timestamp = '2025-04-28 09:26:00' 
        , email_subject = 'Hasbro - ESG Integration Framework & Screening'
        , to_names = 'Jessica Palmer'
        , to_emails = 'jessica.palmer@hasbro.com'
        , from_name = 'Jane Moneypenny'
        , from_email = 'jane.moneypenny@bankwell.com' 
        , email_body = 'Hi Jessica,  Following our last check-in, I have completed a review of Hasbros allocation drift relative to your target weights. Given the outperformance in U.S. large-cap tech and some underperformance in international value, we are now seeing a ~3% overweight in growth assets. I would recommend a modest rebalance to bring equity exposures back in line and to free up capital for upcoming opportunities in short-duration credit. I have attached a draft summary with suggested moves—happy to walk through these with you this week if you are available.  Best Jane'
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com')
          AND from_email in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com')
          AND TRIM(email_timestamp) = '2025-05-01 20:30:00' 
    """))

In [20]:
with engine.begin() as connection:  # to jessica from jane
    connection.execute(text("""
        UPDATE email_data
        SET email_subject = 'Hasbro - Portfolio Rebalancing Review – Q2 Recommendations'
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com')
          AND from_email in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com')
          AND TRIM(email_timestamp) = '2025-03-21 09:48:00' 
    """))

In [23]:
df = pd.read_sql("""SELECT *
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com') 
        order by email_timestamp desc""", con=engine)
df.head(30)

,index,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,258.0,2025-07-10 09:10:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica, Great, I will schedule us for 2:30 on the 10th. Best regards, Jane Moneypenny; Financial Advisor; Bankwell Financial; Phone: (555) 123-4567; Email: jane.moneypenny@outlook.com"
1,257.0,2025-07-09 16:10:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi jane, Yes, this needs further thought. I can do 1-5pm tomorrow, or 9am on the 13th. Let me know which works for you. Regards, Jessica Palmer, VP Hasbro Email: jessica.palmer@hasbro.com Phone: 909.878.8329x31984"
2,256.0,2025-07-09 13:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica, I will have our research team further look into small-cap consumer entertainment trends, but from what I have seen in the news I dont believe conditions will shift impactfully before end of year. I suggest we meet soon to have an in depth discussion of the impact of Hasbros risk strategy post divestiture and bond fund allocation. Best, Jane"
3,255.0,2025-07-08 09:40:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Thanks Jane,\n\nThank you for the update. Seems like we need to reevaluate our strategy. I am hesitant to change much at this moment given the likely update to senior leadership. Do you believe that current market trends will continue regarding small-cap consumer entertainment? \n\n Also, I am curious about our allocation in bond funds. Given current inflation, what is the likely impact on the bond market, i.e. should we consider moving further out of bonds? \n\nRegards,\n\n--\nJessica Palmer\nVP\nHasbro\nEmail: jessica.palmer@hasbro.com\nPhone: 909.878.8329x31984\n"
4,254.0,2025-07-06 08:05:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica, I am reaching out regarding Hasbros Q3 goals. I understand that the recent divestitures have been completed. I ran a quick comparative performance check across your key equity positions. Your exposure to small-cap consumer entertainment stocks underperformed the S&P benchmark by roughly 2.3% over the last 6 weeks. That said, your positions in structured notes tied to diversified consumer indexes helped buffer some of the downside. We can explore reallocating a portion of your discretionary sector holdings to lower beta instruments or consider sector-rotation strategies if you would like. We can wait further to see how things evolve, but worth considering an adjustment in the nearterm based on market trends. Best regards, Jane Moneypenny, Financial Advisor, Bankwell Financial, Phone: (555) 123-4567, Email: jane.moneypenny@outlook.com"
5,NaN,2025-05-13 09:13:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - ESG Integration Framework & Screening,"Hi Jane, Great thank you for diving into this for us. Look forward to discussing further. --Jessica"
6,NaN,2025-05-12 15:04:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - ESG Integration Framework & Screening,"Hi Jessica, Okay great, I believe most of those will be easy to include off-the-shelf from our current report portfolio, but some will need to be custom developed, particularly the YoY emissions trends. I can set up a meeting for us to discuss further. Best, Jane"
7,NaN,2025-05-12 12:46:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - ESG Integration Framework & Screening,"Hi Jane, Thank you for the update on the carbon impact dashboard—its exactly the type of transparency and data-driven approach we have been looking for. I would like to include a few specific KPIs that would be particularly relevant for Hasbros board review: 1) Portfolio carbon intensity vs. industry benchmarks (especially within consumer products and manufacturing sectors). 2) Progress toward science-based emissions reduction targets (aligned with SBTi, if available). 3) Percentage of investments in companies with net-zero or formal ESG commitments. 4) Year-over-year emissions trend analysis at both the portfolio and sector level. Additionally, I think routine monitoring and reporting will be key. Could we set up a quarterly summary that we can present to the board? Ideally, it would include both a dashboard snapshot and a brief narrative on any significant changes or high-impact areas. Many thanks, Jessica"
8,NaN,2025-05-10 17:55:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - ESG Integration Framework & Screening,"Hi Jessica, Great to hear that the strategic rollout went over well with the board. We can absolutely set up a dashboard focused on Carbon impacts of your investments, this is one of Bankwells specialties. Our dashboards allow you to view metrics like carbon intensity per $1M invested, sector-level breakdowns, and historical emissions trends. This will help inform future allocation decisions and align your portfolio more closely with your sustainability objectives. Let me know if there are any specific KPIs or thresholds you would like us to include. Best, Jane"
9,NaN,2025-05-10 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - ESG Integration Framework & Screening,"Hi Jane, Great chatting with you last week. The strategic targets went over well with the board, except for a lack of focus on ESG priorities. I think we need to support from bankwell in how to monitor how carbon friendly our investments are. I remember in the past we spoke about ESG dashboards that you make for other clients. What research does bankwell have on carbon impacts of our funds? Many thanks, Jessica"
10,NaN,2025-04-28 09:26:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Strategic Targets Rollout Discussion,"Hi Jessica, Absolutely, I will prepare a review of your liquidity ratio and risk exposure along with a comprehensive review of Hasbros strategy. Look forward to speaking soon. Many thanks, Jane"
11,NaN,2025-04-27 11:43:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Strategic Targets Rollout Discussion,"Hi Jane, Thank you for reaching out. Our CFO team is starting to plan for upcoming capital needs, so I would like to review our Liquidity ratios. Given the recent volatility and our internal capital planning cycles, it’s important we understand where we might need to build flexibility or reassess exposures. Are you able to give us a updated projection of market risk of our holdings? Thanks, Jessica"
12,NaN,2025-04-26 20:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Strategic Targets Rollout Discussion,"Hi Jessica, I hope you are doing well. I am reaching out to schedule time to discuss the Strategic Targets Rollout in the context of Hasbros current investment strategy and recent shifts in the market landscape. With continued volatility across rates, supply chains showing signs of stabilization, and sector rotations picking up momentum, its an opportune moment to revisit allocation targets and identify areas where we can position more proactively for the next 6–12 months. During our conversation, I would like to walk through a few potential adjustments based on current macro indicators—particularly around consumer cyclicals, credit exposure, and emerging market positioning. I will also bring updated risk/return projections to support any discussions with the board. Would early next week work for a 45-minute call? Happy to tailor the agenda if there are specific themes you would like to prioritize. Looking forward to catching up. Best, Jane"
13,4.0,2025-03-24 15:18:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Portfolio Rebalancing Review – Q2 Recommendations,"Hi Jane, Thanks for the update on the portfolio. Before we meet Friday, can you include some color on the fixed income side—particularly how you are thinking about positioning in light of recent Fed language? We are getting questions internally about duration risk and reinvestment strategy as part of our cash management review, so any perspective you can share on short vs. intermediate yields would be helpful. Appreciate it, Jessica"
14,3.0,2025-03-21 09:48:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Portfolio Rebalancing Review – Q2 Recommendations,"Hi Jessica, Following our last check-in, I have completed a review of Hasbros allocation drift relative to your target weights. Given the outperformance in U.S. large-cap tech and some underperformance in international value, we are now seeing a ~3% overweight in growth assets. I would recommend a modest rebalance to bring equity exposures back in line and to free up capital for upcoming opportunities in short-duration credit. I have attached a draft summary with suggested moves—happy to walk through these with you this week if you are available. Best Jane"
15,259.0,2023-12-12 11:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Thanks Jane,\n\nI will follow up if I have any issues. Happy holidays! \n\nRegards,\n\n--\nJessica Palmer\nVP\nHasbro\nEmail: jessica.palmer@hasbro.com\nPhone: 909.878.8329x31984\n"
16,253.0,2023-12-12 10:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Hi Jessica,\n\nGreat to speak with you yesterday. I have executed the FX Hedging strategy we discussed, and adjusting for a more conservativre risk profile. Please elt me know if you have any further questions. You can see the adjusted portfolio in your customer portal. I reccomend we check in again in Q1 next year to evaluate strategy after Hasbro's potential divestitures have been completed. \n\n Hope you enjoy time off over the holiday season! \n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
17,246.0,2023-11-22 10:45:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Hi Jessica,\n\nDecember 11th at 11 AM ET works. I'll send the invite and prepare some strategy considerations.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
18,245.0,2023-11-22 10:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Hi Jane,\n\nYes, let's connect. How about December 11th at 11 AM ET?\n\nRegards,\n\n--\nJessica Palmer\nVP\nHasbro\nEmail: jessica.palmer@hasbro.com\nPhone: 909.878.8329x31984\n"
19,244.0,2023-11-21 15:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Hi Jessica,\n\nFollowing up on our call earlier this month regarding the H1 2023 hedge performance. Let's schedule time to finalize the FX hedging strategy for H1 2024.\n\nMarket conditions continue to evolve, so we should review Hasbro's objectives and risk tolerance. Please let me know your availability in early December.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
20,NaN,2023-06-29 07:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Operational Risk Case Study Analysis,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nWould you prepare for FX exposure discussion?\n\nThanks,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
21,NaN,2023-06-29 07:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Operational Risk Case Study Analysis,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nWould you prepare for FX exposure discussion?\n\nThanks,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
22,NaN,2023-06-25 12:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Emerging Market Growth vs. Headwinds,"Dear Jane,\n\nThank you for your email. Jane,\n\nGeopolitical risk implications?\n\nBest,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
23,NaN,2023-06-25 12:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Emerging Market Growth vs. Headwinds,"Dear Jane,\n\nThank you for your email. Jane,\n\nGeopolitical risk implications?\n\nBest,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
24,NaN,2023-06-24 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Liquidity & Daily Redemption Strategies,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nDetails on growth fund launches?\n\nThanks,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
25,NaN,2023-06-24 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Liquidity & Daily Redemption Strategies,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nDetails on growth fund launches?\n\nThanks,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
26,NaN,2023-05-17 12:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - ESG Integration Framework & Screening,"Dear Jane,\n\nThank you for your email. Dear Jane,\n\nInsights on sustainability mandates?\n\nRegards,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
27,NaN,2023-05-17 12:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - ESG Integration Framework & Screening,"Dear Jane,\n\nThank you for your email. Dear Jane,\n\nInsights on sustainability mandates?\n\nRegards,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
28,NaN,2023-05-16 08:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Fit vs. Mandate: Benchmark Transition,"Dear Jane,\n\nThank you for your email. Hello Jane,\n\nComparison of new vs old benchmarks?\n\nThanks,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
29,NaN,2023-05-16 08:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Fit vs. Mandate: Benchmark Transition,"Dear Jane,\n\nThank you for your email. Hello Jane,\n\nComparison of new vs old benchmarks?\n\nThanks,\nJessica Palmer\n\nBest regards,\nJessica Palmer"

In [12]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""INSERT INTO email_data (index	
    , email_timestamp
    , to_names
    , to_emails
    , from_name	
    , from_email
    , email_subject	
    , email_body)
VALUES (3
, '2025-03-21 09:48:00'
, 'Jessica Palmer'
, 'jessica.palmer@hasbro.com'
, 'Jane Moneypenny'
, 'jane.moneypenny@bankwell.com'
, 'Hasbro - Portfolio Rebalancing Review – Q2 Recommendations'
, 'Hi Jessica,  Following our last check-in, I have completed a review of Hasbros allocation drift relative to your target weights. Given the outperformance in U.S. large-cap tech and some underperformance in international value, we are now seeing a ~3% overweight in growth assets. I would recommend a modest rebalance to bring equity exposures back in line and to free up capital for upcoming opportunities in short-duration credit. I have attached a draft summary with suggested moves—happy to walk through these with you this week if you are available.  Best Jane'
)"""))

In [22]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""INSERT INTO email_data (index	
    , email_timestamp
    , to_names
    , to_emails
    , from_name	
    , from_email
    , email_subject	
    , email_body)
VALUES (4
, '2025-03-24 15:18:00'
, 'Jane Moneypenny'
, 'jane.moneypenny@bankwell.com'
, 'Jessica Palmer'
, 'jessica.palmer@hasbro.com'
, 'Hasbro - Portfolio Rebalancing Review – Q2 Recommendations'
, 'Hi Jane, Thanks for the update on the portfolio. Before we meet Friday, can you include some color on the fixed income side—particularly how you are thinking about positioning in light of recent Fed language? We are getting questions internally about duration risk and reinvestment strategy as part of our cash management review, so any perspective you can share on short vs. intermediate yields would be helpful.   Appreciate it, Jessica '
)"""))

## Celestica

In [ ]:
# Denise Moore Celestica - Mid-Year Objective Adjustment Review 2025-06-22 16:00:00 - Finance
# Denise Moore Celestica - Denise Moore Celestica - Cross-Border Regulation & Jurisdiction Briefing 2025-05-25 10:00:00 - Legal
# Denise Moore Celestica - Carbon Score & ESG Exclusion Analysis 2025-05-18 10:00:00 - ESG

In [51]:
df1 = pd.read_sql("""SELECT * FROM meeting_data 
where host_email ='jane.moneypenny@bankwell.com' and invitee_emails = 'denise.moore@celestica.com'
order by meeting_timestamp desc""", con=engine)
df1.head(30)

,index,meeting_timestamp,host,host_email,invitees,invitee_emails,meeting_subject
0,NaN,2025-06-22 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Mid-Year Objective Adjustment Review
1,NaN,2025-05-25 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Cross-Border Regulation & Jurisdiction Briefing
2,NaN,2025-05-18 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Carbon Score & ESG Exclusion Analysis
3,NaN,2025-03-15 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Alternative Credit & Private Credit Strategy
4,NaN,2025-01-20 12:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Counterparty Risk Assessment Update
5,NaN,2024-11-19 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Sector Weight Shift & Exposure Review
6,NaN,2024-09-30 15:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Commodity Trends & Forecast Update
7,NaN,2024-05-19 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - IRS & State Tax Guidance Impacts
8,87.0,2024-02-13 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Discuss CD Maturity and Reinvestment Options
9,50.0,2023-10-30 15:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Discuss Investment Strategy (Rising Rates)
10,33.0,2023-10-15 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Mid-Year Investment Portfolio Check-in
11,4.0,2023-08-12 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Initial Discussion on Liquidity Management

In [50]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE meeting_data 
        SET meeting_timestamp = '2023-08-12 14:00:00'
        WHERE host_email = 'jane.moneypenny@bankwell.com'
          AND invitee_emails = 'denise.moore@celestica.com'
          AND TRIM(meeting_timestamp) = '2018-08-29 14:00:00' 
    """))

### emails celestica

In [100]:
with engine.begin() as connection:  # to jane from denise
    connection.execute(text("""
        UPDATE email_data
        SET email_timestamp = '2025-05-13 09:19:00' 
        , email_subject = 'Re: Celestica - Carbon Score & ESG Exclusion Analysis'
        , to_names = 'Jane Moneypenny'
        , to_emails = 'jane.moneypenny@bankwell.com' 
        , from_name = 'Denise Moore'
        , from_email = 'denise.moore@celestica.com'
        , email_body = 'Jane,  Yes—this is right in line with where we would like to take the portfolio over the next few quarters. We have had growing interest internally in carbon metrics, especially as procurement and treasury functions begin to coordinate on broader climate disclosures.  Please do send the draft allocation proposal. As we move forward, I would like to make sure that any tilts or screens do not meaningfully reduce liquidity, especially given our capital commitments later this year.  Best, Denise'
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'denise.moore@celestica.com')
          AND from_email in ('jane.moneypenny@bankwell.com', 'denise.moore@celestica.com')
          AND TRIM(email_timestamp) = '2025-05-17 11:45:00' 
    """))

In [98]:
with engine.begin() as connection:  # to denise from jane
    connection.execute(text("""
        UPDATE email_data
        SET email_timestamp = '2025-05-12 06:45:00' 
        , email_subject = 'Celestica - Carbon Score & ESG Exclusion Analysis'
        , to_names = 'Denise Moore'
        , to_emails = 'denise.moore@celestica.com'
        , from_name = 'Jane Moneypenny'
        , from_email = 'jane.moneypenny@bankwell.com' 
        , email_body = 'Hi Denise, I wanted to reach out with some recommendations following our prior conversations around carbon intensity metrics and exclusion screens. As part of the portfolio diagnostic, we have analyzed Celesticas holdings through a carbon lens and identified a few areas where modest restructuring could reduce footprint without materially impacting return targets. There are three primary levers we can explore: Replacing high-emitting industrials with lower-intensity alternatives in the same sector; Tightening ESG exclusion filters, particularly around fossil fuels and deforestation-linked supply chains; Introducing low-carbon tilts through strategic ETF overlays or actively managed transition funds. Would you be open to reviewing a draft allocation proposal later this week? I have included projected impact metrics alongside the structural trade-offs.  Best, Jane'
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'denise.moore@celestica.com')
          AND from_email in ('jane.moneypenny@bankwell.com', 'denise.moore@celestica.com')
          AND TRIM(email_timestamp) = '2025-05-17 06:45:00' 
    """))

In [116]:
with engine.begin() as connection:  # to jessica from jane
    connection.execute(text("""
        UPDATE email_data
        SET email_timestamp = '2025-01-10 14:23:00' 
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'denise.moore@celestica.com')
          AND from_email in ('jane.moneypenny@bankwell.com', 'denise.moore@celestica.com')
          AND TRIM(email_timestamp) = '2023-09-12 09:45:00' 
    """))

In [124]:
with engine.begin() as connection:  # to denise from jane
    connection.execute(text("""INSERT INTO email_data (index	
    , email_timestamp
    , to_names
    , to_emails
    , from_name	
    , from_email
    , email_subject	
    , email_body)
VALUES (12
, '2024-10-06 10:12:00'
, 'Denise Moore'
, 'denise.moore@celestica.com'
, 'Jane Moneypenny'
, 'jane.moneypenny@bankwell.com'
, 'Celestica - Bond Strategy Review'
, 'Hi Denise,  We are seeing several clients lean back into intermediate duration, especially in the 4–7 year range, as the Fed signals a pause and real yields normalize. On the credit side, IG corporate spreads remain attractive on a risk-adjusted basis. For clients with a moderate risk budget, we are recommending selective exposure to A-rated issuers and seasoned structured credit, particularly CLOs with solid senior tranche protection. I can send a model allocation and some yield scenarios if thats helpful. Best regards, Jane Moneypenny'
)"""))

In [122]:
with engine.begin() as connection:  # to jane from denise
    connection.execute(text("""INSERT INTO email_data (index	
    , email_timestamp
    , to_names
    , to_emails
    , from_name	
    , from_email
    , email_subject	
    , email_body)
VALUES (13
, '2024-10-05 10:12:00'
, 'Jane Moneypenny'
, 'jane.moneypenny@bankwell.com'
, 'Denise Moore'
, 'denise.moore@celestica.com'
, 'Bond Strategy Review'
, 'Hi Jane, As part of our quarterly asset allocation review, we are revisiting our fixed income positioning, particularly in light of the recent curve movements. Can you share your view on duration and whether theres merit in extending slightly now that rates appear to be stabilizing? We are also debating whether to add modest credit risk through IG corporates or structured credit to boost income. Would be helpful to get your take.  Best, Denise'
)"""))

In [125]:
df = pd.read_sql("""SELECT *
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'denise.moore@celestica.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'denise.moore@celestica.com') 
        order by email_timestamp desc""", con=engine)
df.head(30)

,index,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,NaN,2025-06-20 16:45:00,Denise Moore,denise.moore@celestica.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Celestica - Mid-Year Objective Adjustment Review,"Hi Denise, Thanks, I will get something on the schedule for us. I will include updated compliance metrics (sector exposures, liquidity flags, regional allocations), and I will also pull together a few anonymized peer benchmarks from clients with similar investment governance profiles. Let me know if you would like any follow-up materials prepared for your internal review committee. Best Jane"
1,5.0,2025-06-17 09:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Mid-Year Objective Adjustment Review,"Jane, Thanks for the note—yes, lets get something on the calendar for next week. Tuesday or Thursday morning works best on my end. I would like to dedicate part of the review to compliance-related portfolio metrics. The legal team has been revisiting our exposure thresholds and reporting obligations in anticipation of some Q3 audit prep, so anything you can provide that helps us get ahead of those conversations would be appreciated. Also, if you have any visibility into how peer firms are managing allocations under the current regulatory climate, that context would be helpful. Looking forward to the conversation. Best, Denise"
2,NaN,2025-06-15 09:00:00,Denise Moore,denise.moore@celestica.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Celestica - Mid-Year Objective Adjustment Review,"Hi Denise, As we approach the mid-point of the year, I would like to schedule a time to conduct our mid-year financial review for Celesticas portfolio. Given the pace of market developments and some of the regulatory shifts we discussed earlier this year—particularly around transparency and capital disclosures—it is a good time to revisit strategy and ensure everything remains aligned with your compliance framework and risk appetite. I suggest we cover: YTD performance relative to benchmarks, Shifts in sector exposures and macro outlook, Updates on any upcoming regulatory considerations (especially related to reporting), and Recommended tactical adjustments if needed. Would you be available next week for a 60-minute session? I am happy to tailor the discussion to anything else top-of-mind for your team. Best Jane"
3,NaN,2025-05-22 08:33:00,Denise Moore,denise.moore@celestica.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Celestica - Cross-Border Regulation & Jurisdiction Briefing,"Hi Denise, All noted- I will include the currency breakdown in both CAD and local denominations, along with structural commentary on fund types and jurisdictional preferences. I will also flag any regulatory hotspots that may warrant preemptive disclosures or board-level discussion. This should give us a solid compliance foundation heading into the mid-year review. I will circulate materials Monday so you have time to preview ahead of our call. Best, Jane"
4,5.0,2025-05-21 15:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Re: Celestica - Cross-Border Regulation & Jurisdiction Briefing,"Jane, Thanks—that agenda sounds spot on. Please include any views on fund structures that have triggered scrutiny (e.g., feeder vs. direct fund access) and whether certain wrappers are seen more favorably in local regulatory filings. Also, a quick request: If you can summarize risk exposure by jurisdiction in both CAD and local currency, that will make it easier for our compliance team to cross-reference with our internal reports. Best, Denise"
5,NaN,2025-05-20 10:05:00,Denise Moore,denise.moore@celestica.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Celestica - Cross-Border Regulation & Jurisdiction Briefing,"Hi Denise, I will set up a call for the 25th. I will bring: A jurisdiction-by-jurisdiction matrix for your current EM holdings, Reporting overlaps we have observed across key APAC markets, and Examples of how similar institutions are navigating divergent capital treatment and local registration issues. I will also include commentary from our compliance strategy group regarding pending changes to outbound capital flow disclosures in Singapore and India. Best, Jane"
6,NaN,2025-05-20 09:17:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Cross-Border Regulation & Jurisdiction Briefing,"Jane, Thanks for flagging this. We have been getting early alerts from our legal team about potential reporting conflicts across some of our Asia-based holdings, particularly with overlapping standards in Singapore and Japan. Lets set up a call— I would like to understand where we may be at risk of duplicate reporting or regulatory mismatch. Also, if you can share anything on how other corporate plans are managing those regional compliance thresholds, that would be valuable context for our team. Best, Denise"
7,NaN,2025-05-19 03:00:00,Denise Moore,denise.moore@celestica.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Celestica - Cross-Border Regulation & Jurisdiction Briefing,"Hi Denise, Following up on our conversation yesterday about compliance tightening across regions, I wanted to share a few updates that may be relevant to Celesticas oversight teams—particularly around cross-border asset holdings. We are seeing increased regulatory scrutiny from several jurisdictions, notably in Europe and APAC, related to disclosure requirements, repatriation rules, and risk capital treatment. I believe it would be helpful to review how current exposures align with these evolving frameworks and whether any adjustments should be considered ahead of your internal audit cycle. Would you be open to a short call next week to walk through a few jurisdictional risk summaries and reporting implications? Best, Jane"
8,8.0,2025-05-15 11:02:00,Denise Moore,denise.moore@celestica.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Celestica - Carbon Score & ESG Exclusion Analysis,"Hi Denise, Great point— I will include a section on retain-and-engage strategies for sectors where full exclusion may reduce influence or conflict with operational needs. I will also flag managers with established stewardship programs so you can see where active engagement is already part of the process. Once you have reviewed the allocation adjustments, we can refine further based on capital availability and board preferences. Looking forward to your feedback. Best regards, Jane"
9,7.0,2025-05-14 10:52:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Re: Celestica - Carbon Score & ESG Exclusion Analysis,"Hi Jane, Perfect—thank you. As you are finalizing the materials, can you also highlight any sectors where we may want to retain exposure but work through engagement rather than full exclusion? I imagine that may apply to some of the diversified industrials and logistics holdings. We have been getting questions from the board about how exclusions balance with shareholder influence, so I would like to bring that nuance into our next review. Best, Denise"
10,6.0,2025-05-13 16:32:00,Denise Moore,denise.moore@celestica.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Celestica - Carbon Score & ESG Exclusion Analysis,"Hi Denise, Thanks—understood on the liquidity front. The restructured draft I will send includes: A carbon intensity snapshot before and after the proposed changes (tCO2e/$M invested); Impacts on benchmark tracking error and sector neutrality; Exclusion overlays that target coal mining, arctic drilling, and non-aligned transition plans. I have also flagged a few transition-aligned funds that maintain daily liquidity and could serve as substitutes for certain legacy exposures. You will have the materials in your inbox by Thursday EOD. Best, Jane"
11,NaN,2025-05-13 09:19:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Re: Celestica - Carbon Score & ESG Exclusion Analysis,"Jane, Yes—this is right in line with where we would like to take the portfolio over the next few quarters. We have had growing interest internally in carbon metrics, especially as procurement and treasury functions begin to coordinate on broader climate disclosures. Please do send the draft allocation proposal. As we move forward, I would like to make sure that any tilts or screens do not meaningfully reduce liquidity, especially given our capital commitments later this year. Best, Denise"
12,NaN,2025-05-12 06:45:00,Denise Moore,denise.moore@celestica.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Celestica - Carbon Score & ESG Exclusion Analysis,"Hi Denise, I wanted to reach out with some recommendations following our prior conversations around carbon intensity metrics and exclusion screens. As part of the portfolio diagnostic, we have analyzed Celesticas holdings through a carbon lens and identified a few areas where modest restructuring could reduce footprint without materially impacting return targets. There are three primary levers we can explore: Replacing high-emitting industrials with lower-intensity alternatives in the same sector; Tightening ESG exclusion filters, particularly around fossil fuels and deforestation-linked supply chains; Introducing low-carbon tilts through strategic ETF overlays or actively managed transition funds. Would you be open to reviewing a draft allocation proposal later this week? I have included projected impact metrics alongside the structural trade-offs. Best, Jane"
13,10.0,2025-03-05 18:20:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Alternative Credit & Private Credit Strategy,"Hi Jane, Thanks—next Tuesday afternoon would work well. Please include pacing expectations, typical drawdown timelines, and any nuances around capital treatment or balance sheet implications we should flag for our finance team. We would also like to see how these allocations might fit within the broader credit sleeve—so if you can prepare a sample integration model showing how this complements our core fixed income book, that would be helpful. Looking forward to the discussion. Best, Denise"
14,11.0,2025-03-04 15:12:00,Denise Moore,denise.moore@celestica.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Celestica - Alternative Credit & Private Credit Strategy,"Hi Denise, Great timing—theres been renewed interest across institutional clients in exactly those segments, particularly senior secured lending and non-bank originations in specialty credit. I can pull together a short list of managers across direct lending, real estate credit, and niche ABS that offer strong fundamentals and conservative underwriting. Some are evergreen structures with quarterly liquidity; others follow a more traditional drawdown model. Lets aim for a 30-minute working session early next week—I will walk you through the current landscape, recent vintages, and the risk-return tradeoffs. Best regards, Jane Moneypenny"
15,10.0,2025-03-03 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Alternative Credit & Private Credit Strategy,"Hi Jane, I wanted to revisit our prior discussion around expanding Celesticas allocation to alternative and private credit. Given the rate environment and some of the constraints in public fixed income, we are exploring ways to enhance yield without taking on excessive illiquidity. Do you have a sense of where similar corporate plans are leaning? We are especially interested in senior direct lending, specialty finance, and asset-backed strategies. I would like to understand the range of structures available and any considerations around pacing, capital calls, and reporting. Lets plan a time to dig into this further. Best, Denise Moore"
16,236.0,2025-01-12 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Re: Celestica - Investment Execution: 6-Month CD,"Hi Jane,\n\nThanks for confirming the CD purchase. Appreciate locking in that rate.\n\nBest,\n\n--\nDenise Moore\nSenior Director\nCelestica\nEmail: denise.moore@celestica.com\nPhone: 754-579-1511x763\n"
17,235.0,2025-01-10 14:23:00,Denise Moore,denise.moore@celestica.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Celestica - Investment Execution: 6-Month CD,"Hi Denise,\n\nFollowing our discussion last week and your approval, this email confirms the investment of $10M into a 6-month Bankwell Certificate of Deposit (CD) for Celestica, executed this morning at the agreed rate.\n\nThe confirmation details are attached. Please let me know if you have any questions.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
18,10.0,2024-12-05 10:12:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Re: Celestica - ESG Integration Strategy – Initial Discussion,"Hi Jane, Yes—this is a timely topic. While we have applied some exclusions historically, we have not yet taken the step toward a more structured ESG policy at the portfolio level. Theres growing internal interest, especially as sustainability reporting gains visibility at the enterprise level. Please do send over a short summary, and I would be happy to carve out time next week to discuss how we might start layering ESG into manager oversight, reporting, and board engagement. Best, Denise"
19,12.0,2024-12-04 15:12:00,Denise Moore,denise.moore@celestica.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Celestica - ESG Integration Strategy – Initial Discussion,"Hi Denise, I hope you are well. I wanted to touch base on a topic thats increasingly coming up across our institutional client base—formalizing ESG integration across portfolios. I realize Celestica already applies some baseline screens, but there may be opportunities to move from basic exclusions to a more strategic ESG framework that balances risk, reputation, and return. I would be happy to share what we are seeing in terms of: Approaches to integrating ESG scoring in manager selection, Sector-specific considerations (especially for industrials and tech supply chains), Balancing financial materiality with values-based mandates. Let me know if this is something you would like to explore further—I can prepare a short summary of the ESG approaches most relevant to your current asset mix. Best regards, Jane Moneypenny"
20,12.0,2024-10-06 10:12:00,Denise Moore,denise.moore@celestica.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Celestica - Bond Strategy Review,"Hi Denise, We are seeing several clients lean back into intermediate duration, especially in the 4–7 year range, as the Fed signals a pause and real yields normalize. On the credit side, IG corporate spreads remain attractive on a risk-adjusted basis. For clients with a moderate risk budget, we are recommending selective exposure to A-rated issuers and seasoned structured credit, particularly CLOs with solid senior tranche protection. I can send a model allocation and some yield scenarios if thats helpful. Best regards, Jane Moneypenny"
21,13.0,2024-10-05 10:12:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Bond Strategy Review,"Hi Jane, As part of our quarterly asset allocation review, we are revisiting our fixed income positioning, particularly in light of the recent curve movements. Can you share your view on duration and whether theres merit in extending slightly now that rates appear to be stabilizing? We are also debating whether to add modest credit risk through IG corporates or structured credit to boost income. Would be helpful to get your take. Best, Denise"
22,NaN,2023-06-21 09:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Re: Celestica - Mid-Year Objective Adjustment Review,"Dear Jane,\n\nThank you for your email. Jane,\n\nCould we involve long-term capital planning?\n\nThanks,\nDenise Moore\n\nBest regards,\nDenise Moore"
23,NaN,2023-06-21 09:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Re: Celestica - Mid-Year Objective Adjustment Review,"Dear Jane,\n\nThank you for your email. Jane,\n\nCould we involve long-term capital planning?\n\nThanks,\nDenise Moore\n\nBest regards,\nDenise Moore"
24,NaN,2023-06-15 12:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Re: Celestica - Alternative Credit & Private Credit Strategy,"Dear Jane,\n\nThank you for your email. Dear Jane,\n\nSustainable yield fund insights?\n\nRegards,\nDenise Moore\n\nBest regards,\nDenise Moore"
25,NaN,2023-06-15 12:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Re: Celestica - Counterparty Risk Assessment Update,"Dear Jane,\n\nThank you for your email. Dear Jane,\n\nCould you include counterparty risk position?\n\nRegards,\nDenise Moore\n\nBest regards,\nDenise Moore"
26,NaN,2023-06-15 12:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Re: Celestica - Counterparty Risk Assessment Update,"Dear Jane,\n\nThank you for your email. Dear Jane,\n\nCould you include counterparty risk position?\n\nRegards,\nDenise Moore\n\nBest regards,\nDenise Moore"
27,NaN,2023-06-15 12:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Re: Celestica - Alternative Credit & Private Credit Strategy,"Dear Jane,\n\nThank you for your email. Dear Jane,\n\nSustainable yield fund insights?\n\nRegards,\nDenise Moore\n\nBest regards,\nDenise Moore"
28,NaN,2023-05-24 22:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Re: Celestica - Cross-Border Regulation & Jurisdiction Briefing,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nAre there cross-border disclosure rule changes?\n\nBest,\nDenise Moore\n\nBest regards,\nDenise Moore"
29,NaN,2023-05-24 22:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Re: Celestica - Cross-Border Regulation & Jurisdiction Briefing,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nAre there cross-border disclosure rule changes?\n\nBest,\nDenise Moore\n\nBest regards,\nDenise Moore"

## AbbVie

In [ ]:
# Cynthia Hobbs AbbVie - Annual Plan & Strategic Priorities 2025-06-13 16:00:00 - Finance
# Cynthia Hobbs AbbVie - Growth & Fixed Income Launch Overview 2025-05-24 15:00:00 - finance
# Cynthia Hobbs AbbVie - ESG Fund Portfolio & Benchmark Review 2025-05-03 10:00:00 - ESG

In [156]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE meeting_data 
        SET meeting_timestamp = '2024-01-10 13:00:00'
        WHERE host_email = 'jane.moneypenny@bankwell.com'
          AND invitee_emails = 'cynthia.hobbs@abbvie.com'
          AND TRIM(meeting_timestamp) = '2023-07-25 14:00:00' 
    """))

In [157]:
df1 = pd.read_sql("""SELECT * FROM meeting_data 
where host_email ='jane.moneypenny@bankwell.com' and invitee_emails = 'cynthia.hobbs@abbvie.com'
order by meeting_timestamp desc""", con=engine)
df1.head(30)

,index,meeting_timestamp,host,host_email,invitees,invitee_emails,meeting_subject
0,NaN,2025-06-13 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - Annual Plan & Strategic Priorities
1,NaN,2025-05-24 15:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - Growth & Fixed Income Launch Overview
2,NaN,2025-05-03 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - ESG Fund Portfolio & Benchmark Review
3,NaN,2025-03-07 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - Global Macro Outlook & Policy Impact
4,NaN,2025-02-27 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - Proposed Benchmark Re-alignment Overview
5,NaN,2024-12-04 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - Tax Deferral Strategy & Harvesting
6,NaN,2024-08-24 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - Risk Exposure & Counterparty Controls
7,0.0,2024-07-22 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - Introductory Call & Bankwell Services Overview
8,29.0,2024-07-04 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - Q2 2020 Relationship Review
9,NaN,2024-05-09 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - SEC Policy Briefing & Discussion
10,45.0,2024-03-04 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - IAT Payment Setup Process Review
11,84.0,2024-01-25 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - Q4 2023 Relationship Review
12,74.0,2024-01-10 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - Q3 2023 Relationship Review

### AbbVie Emails

In [212]:
with engine.begin() as connection:  # to jane from cynthia
    connection.execute(text("""
        UPDATE email_data
        SET email_timestamp = '2025-03-02 16:43:00' 
        , email_subject = 'AbbVie - Global Macro Outlook & Policy Impact'
        , to_names = 'Jane Moneypenny'
        , to_emails = 'jane.moneypenny@bankwell.com' 
        , from_name = 'Cynthia Hobbs'
        , from_email = 'cynthia.hobbs@abbvie.com'
        , email_body = 'Hi Jane,  Hope you are well. As we wrap up Q1, I would appreciate your take on the broader macro landscape. We have been watching the shifting rate narratives and some of the geopolitical noise, but internally there is still a lot of uncertainty around how to position for the rest of the year. What is your current view on global growth, central bank trajectories, and how we should be thinking about risk in the context of continued inflation stickiness and regional divergence? Appreciate any thoughts you can share—informal is fine.  Best, Cynthia '
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'cynthia.hobbs@abbvie.com')
          AND from_email in ('jane.moneypenny@bankwell.com', 'cynthia.hobbs@abbvie.com')
          AND TRIM(email_timestamp) = '2023-07-07 13:45:00' 
    """))

In [208]:
with engine.begin() as connection:  # to cynthia from jane
    connection.execute(text("""
        UPDATE email_data
        SET email_timestamp = '2025-06-09 12:01:00' 
        , email_subject = 'Re: AbbVie - Annual Plan & Strategic Priorities'
        , to_names = 'Cynthia Hobbs'
        , to_emails = 'cynthia.hobbs@abbvie.com'
        , from_name = 'Jane Moneypenny'
        , from_email = 'jane.moneypenny@bankwell.com' 
        , email_body = 'That sounds like a solid foundation. I will prepare a portfolio alignment deck that maps your stated priorities to current asset exposures, including: Liquidity by asset class and structure, Innovation exposure (e.g., health tech, automation, digital infrastructure), and Areas of potential de-risking (based on risk-adjusted return projections). I will also include our capital markets outlook through 2026, including key assumptions around central bank policy, credit markets, and global equity sector leadership.  Best, Jane'
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'cynthia.hobbs@abbvie.com')
          AND from_email in ('jane.moneypenny@bankwell.com', 'cynthia.hobbs@abbvie.com')
          AND TRIM(email_timestamp) = '2025-05-23 20:15:00' 
    """))

In [220]:
with engine.begin() as connection:  # to cynthia from jane
    connection.execute(text("""INSERT INTO email_data (index	
    , email_timestamp
    , to_names
    , to_emails
    , from_name	
    , from_email
    , email_subject	
    , email_body)
VALUES (12
, '2024-11-17 08:33:00'
, 'Cynthia Hobbs'
, 'cynthia.hobbs@abbvie.com'
, 'Jane Moneypenny'
, 'jane.moneypenny@bankwell.com'
, 'AbbVie - documentation review'
, 'Hi Cynthia,  Hope the documentation review for the credit facility is progressing well on your side. Our legal team has incorporated the comments from your counsels last turn.Are there any final points to address before we target execution and closing, perhaps next week?  Best regards, Jane Moneypenny'
)"""))

In [217]:
with engine.begin() as connection:  # to jane from cynthia
    connection.execute(text("""INSERT INTO email_data (index	
    , email_timestamp
    , to_names
    , to_emails
    , from_name	
    , from_email
    , email_subject	
    , email_body)
VALUES (15
, '2025-01-14 09:39:00'
, 'Jane Moneypenny'
, 'jane.moneypenny@bankwell.com'
, 'Cynthia Hobbs'
, 'cynthia.hobbs@abbvie.com'
, 'Re: AbbVie - Proposed Benchmark Re-alignment Overview'
, 'Hi Jane,  KPIs on macro benchmarks look good, but i would like to see more depth on YoY and MoM returns.   Best, Cynthia Hobbs'
)"""))

In [243]:
with engine.begin() as connection:  # to jessica from jane 
    connection.execute(text("""
        UPDATE email_data
        -- SET email_timestamp = '2024-03-20 10:35:00'
        SET email_subject = 'AbbVie - Quarterly Relationship Review - Q3 2024'
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'cynthia.hobbs@abbvie.com')
          AND from_email in ('jane.moneypenny@bankwell.com', 'cynthia.hobbs@abbvie.com')
          AND TRIM(email_timestamp) = '2024-07-06 11:00:00' 
    """))

In [244]:
df = pd.read_sql("""SELECT *
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'cynthia.hobbs@abbvie.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'cynthia.hobbs@abbvie.com') 
        --and email_timestamp > '2019-01-12 09:45:00'
        order by email_timestamp desc""", con=engine)
df.head(30)

,index,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,NaN,2025-06-09 16:43:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Annual Plan & Strategic Priorities,"Hi Jane, June 13th works well—please go ahead and block the time. I appreciate you layering in the innovation and liquidity analytics, as we expect more board-level interest in those dimensions this year. Also, if possible, please include a slide on policy bandwidth—highlighting how much room we have within the IPS to make tactical adjustments if needed during the second half of the year. Looking forward to the session. Best, Cynthia"
1,NaN,2025-06-09 12:01:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: AbbVie - Annual Plan & Strategic Priorities,"That sounds like a solid foundation. I will prepare a portfolio alignment deck that maps your stated priorities to current asset exposures, including: Liquidity by asset class and structure, Innovation exposure (e.g., health tech, automation, digital infrastructure), and Areas of potential de-risking (based on risk-adjusted return projections). I will also include our capital markets outlook through 2026, including key assumptions around central bank policy, credit markets, and global equity sector leadership. Best, Jane"
2,18.0,2025-06-09 11:19:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Annual Plan & Strategic Priorities,"Hi Jane, We are beginning to shape the high-level priorities now. It would be helpful if you could prepare a portfolio alignment summary, highlighting where our current exposures support or diverge from these areas. We will also need your view on capital market assumptions heading into 2026, including rate forecasts and sector outlooks. Best, Cynthia Hobbs"
3,NaN,2025-06-08 11:19:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,AbbVie - Annual Plan & Strategic Priorities,"Hi Cynthia, I wanted to reach out as we begin preparations for AbbVies Annual Plan & Strategic Priorities meeting. Based on our discussions earlier this month, I understand this session will help set directional themes for capital allocation, risk management, and long-term positioning. To support that process, I would like to propose a working session in the next few weeks where we can review: 1) Current portfolio alignment vs. strategic objectives 2) Thematic opportunities tied to innovation, resilience, and income generation 3) Long-horizon planning scenarios (e.g., rate normalization, deglobalization, climate-linked transitions) 4) Any adjustments to benchmarks or policy guardrails. Let me know if you have an initial draft of this year’s strategic themes, and I will shape our inputs accordingly. I will also coordinate with your broader finance and treasury team if there are other data points we should be incorporating. Best, Jane"
4,18.0,2025-05-21 10:03:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Growth & Fixed Income Launch Overview,"Hi Jane, Sounds good— I appreciate you tailoring the analysis. Please also include a volatility overlay showing the expected change in portfolio risk with the mid-cap and credit adjustments. That will help us frame the trade-offs more clearly for the committee. Looking forward to reviewing the materials. Best, Cynthia Hobbs"
5,NaN,2025-05-19 11:47:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: AbbVie - Growth & Fixed Income Launch Overview,"Hi Cynthia, Great questions— I just updated the working draft to address both points: On growth, we still see targeted upside in select mid-cap and innovation-focused sectors, but broader equity valuations are starting to look full. Many clients are rotating within equity sleeves rather than increasing total risk. On fixed income, our view is that extending into 5–7 year IG credit offers meaningful carry, especially as Fed policy flattens. I will model a scenario where we shift about 10% from cash to intermediate credit while maintaining a 90-day liquidity buffer above 80%. I will have the full materials in your inbox by Wednesday EOD. Best, Jane"
6,18.0,2025-05-18 09:20:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Growth & Fixed Income Launch Overview,"Hi Jane, This topic is front and center for us right now, especially as we reassess the role of growth strategies within the broader risk budget. A couple of specific questions for the deck: On the equity side, do you think it still makes sense to lean into growth, or has most of the upside been priced in already? For fixed income, if we were to extend duration modestly or take on more credit, what is your view on managing the liquidity trade-offs? We are aiming to maintain our flexibility while not leaving too much return on the table. Looking forward to seeing your recommendations. Best, Cynthia Hobbs"
7,NaN,2025-05-17 14:45:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,AbbVie - Growth & Fixed Income Launch Overview,"Hi Cynthia, As I mentioned during our last check-in, I wanted to follow up with a few thoughts on growth allocation and fixed income positioning, especially as we finalize materials for your upcoming investment committee session. Given recent strength in equity markets and signs of stabilization in the rate environment, we are seeing many clients reassess both sides of their portfolios. I would like to share: a few updated scenarios for growth allocations (with sector and regional tilts), a revised view on duration and credit positioning, including a potential shift from short-duration cash to intermediate-term IG and a sample barbell structure that balances capital flexibility with long-end yield pickup. Let me know if there are specific angles you would like me to prioritize. I can have a slide deck over by midweek if helpful for internal discussion prep. Best, Jane"
8,NaN,2025-05-04 03:30:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: AbbVie - ESG Fund Portfolio & Benchmark Review,"Hi Cynthia, Great touching base with you yesterday. Attached is the ESG dashboard link as discussed. I will reach out soon on Fixed Income strategy. Best, Jane Moneypenny"
9,13.0,2025-05-02 14:40:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - ESG Fund Portfolio & Benchmark Review,"Hi Jane, Thanks—those additions sound good. Please also include a short note on how any benchmark revisions might affect board-level reporting, especially around our quarterly ESG impact disclosures. If the revised framework holds up well, I would like to propose integrating it into our full portfolio performance review in Q3. Appreciate all your help with this. Best, Cynthia"
10,NaN,2025-05-01 08:57:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: AbbVie - ESG Fund Portfolio & Benchmark Review,"Hi Cynthia, Perfect—lets go with Thursday at 2:30pm CST. I will prepare a revised benchmark proposal that reflects: 1) Increased emphasis on carbon trajectory (vs. static footprint) 2) Tighter screening around thermal coal and high-emitting sectors 3) Manager engagement scoring as part of the weighting approach. I will also include dashboard updates showing side-by-side comparisons of the current fund mix and a hypothetical tilt scenario. You will have the materials in your inbox by Wednesday EOD. Looking forward to the discussion. Best, Jane Moneypenny"
11,13.0,2025-04-30 13:35:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - ESG Fund Portfolio & Benchmark Review,"Hi Jane, Thanks for reaching out. I have actually been reviewing the ESG dashboard with our sustainability and finance teams, and it has been really useful in giving us clarity on fund-level metrics—especially the emissions exposure by sector. Lets definitely set up a time to review. I would like to spend some time on the benchmark itself—I think we may want to revise it to better reflect our internal priorities, including a higher weight on transition-oriented funds. I am free Tuesday or Thursday afternoon next week—just let me know what works best. Best, Cynthia Hobbs"
12,NaN,2025-04-29 05:15:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: AbbVie - ESG Fund Portfolio & Benchmark Review,"Hi Cynthia, I hope you are doing well. I wanted to check in to revisit the ESG fund lineup and benchmark framework we have been using for AbbVies portfolio. Now that we have had the ESG dashboard live for a full quarter, it is a good time to review fund-level alignment, performance vs. ESG targets, and any benchmark tracking deviations. I have run a preliminary attribution using the dashboard, and there are a few points worth flagging—particularly around carbon intensity differentials and manager engagement scores. I would recommend we walk through: 1) ESG alignment of current fund lineup vs. custom benchmark 2) Relative performance of Article 8/9 funds over the past 6 months 3) Opportunities to refine benchmark methodology (e.g., adding an emissions intensity floor). Would you have time next week to meet? I can send a snapshot summary in advance. Best regards, Jane Moneypenny"
13,12.0,2025-03-03 08:33:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: AbbVie - Global Macro Outlook & Policy Impact,"Hi Cynthia, That is coming up in nearly every client conversation right now. Big picture, we are seeing a fairly uneven global story. The U.S. remains more resilient than expected, though there are signs that consumer strength is starting to soften. Europe looks fragile, with a drag from industrial production and tight credit, while Asia is still adjusting to a slower post-reopening recovery in China. Central banks are nearing the end of their tightening cycles, but I do not think we are in for aggressive easing just yet. The messaging remains cautious, and most are watching inflation data closely before committing to any policy pivot. That said, the probability of rate cuts in the back half of the year has definitely increased. From a positioning standpoint, there is still room to take risk selectively, but I would be keeping a close eye on liquidity and duration exposure, particularly as market volatility could pick up again if growth downgrades materialize. Best regards, Jane Moneypenny"
14,228.0,2025-03-02 16:43:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - Global Macro Outlook & Policy Impact,"Hi Jane, Hope you are well. As we wrap up Q1, I would appreciate your take on the broader macro landscape. We have been watching the shifting rate narratives and some of the geopolitical noise, but internally there is still a lot of uncertainty around how to position for the rest of the year. What is your current view on global growth, central bank trajectories, and how we should be thinking about risk in the context of continued inflation stickiness and regional divergence? Appreciate any thoughts you can share—informal is fine. Best, Cynthia"
15,15.0,2025-01-14 09:39:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Proposed Benchmark Re-alignment Overview,"Hi Jane, KPIs on macro benchmarks look good, but i would like to see more depth on YoY and MoM returns. Best, Cynthia Hobbs"
16,12.0,2025-01-12 08:33:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,AbbVie - Proposed Benchmark Re-alignment Overview,"Hi Cynthia, Just want to touch base on the KPIs that our reporting team updated. Lets set up a time to dicuss soon. Best regards, Jane Moneypenny"
17,12.0,2024-11-17 08:33:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,AbbVie - documentation review,"Hi Cynthia, Hope the documentation review for the credit facility is progressing well on your side. Our legal team has incorporated the comments from your counsels last turn.Are there any final points to address before we target execution and closing, perhaps next week? Best regards, Jane Moneypenny"
18,227.0,2024-07-07 13:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,AbbVie - Quarterly Relationship Review - Q3 2024,"Hi Jane,\n\nYes, let's schedule the Q3 review. How about July 25th at 1 PM CT?\n\nBest,\n\n--\nCynthia Hobbs\nDirector\nAbbVie\nEmail: cynthia.hobbs@abbvie.com\nPhone: (446)673-8121x90878\n"
19,226.0,2024-07-06 11:00:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,AbbVie - Quarterly Relationship Review - Q3 2024,"Hi Cynthia,\n\nTime to schedule our Q3 relationship review call. Can we aim for sometime in the second half of July?\n\nWe can cover the performance of the cash management and IAT services, discuss any upcoming initiatives at AbbVie, and provide a market/economic update.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
20,52.0,2024-06-08 11:05:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Cash Management Implementation Update,"Hi Jane,\n\nThanks for checking in. So far, everything looks good from our end. The initial sweeps occurred as expected this morning. We'll monitor it closely over the next few days, but the transition seems smooth. Appreciate your team's support.\n\nBest,\n\n--\nCynthia Hobbs\nDirector\nAbbVie\nEmail: cynthia.hobbs@abbvie.com\nPhone: (446)673-8121x90878\n"
21,51.0,2024-06-07 11:05:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,AbbVie - Cash Management Implementation Update,"Hi Cynthia,\n\nI hope the implementation of the new cash concentration structure is proceeding smoothly. Our operations team confirmed the final account linkages went live yesterday.\n\nPlease let me know if you or your team have encountered any issues or have any questions as you start using the new setup. We want to ensure a seamless transition.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
22,92.0,2024-05-08 16:05:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Quarterly Relationship Review,"Hi Jane,\n\nA quarterly review sounds good. How about July 7th at 11 AM CT?\n\nBest,\n\n--\nCynthia Hobbs\nDirector\nAbbVie\nEmail: cynthia.hobbs@abbvie.com\nPhone: (446)673-8121x90878\n"
23,91.0,2024-05-08 11:05:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,AbbVie - Quarterly Relationship Review,"Hi Cynthia,\n\nI'd like to schedule our standard quarterly relationship review call for sometime in early July.\n\nWe can review the performance of the cash management structure, discuss any upcoming financial needs or projects at AbbVie, and provide a brief market update. Please let me know what dates/times work best for you.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
24,140.0,2024-03-20 10:35:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: AbbVie - Information on International ACH (IAT) Payments,"Hi Cynthia,\n\nWill do. I've attached our IAT service overview, which includes country details and a general comparison to wire transfer fees. Happy to discuss specifics for your payment flows when you're ready.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
25,139.0,2024-03-19 17:05:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Information on International ACH (IAT) Payments,"Hi Jane,\n\nYes, potentially. We have a number of recurring payments to suppliers in Canada and some EU countries where IAT might be applicable. Please send over some information on the service and typical cost savings compared to wires.\n\nBest,\n\n--\nCynthia Hobbs\nDirector\nAbbVie\nEmail: cynthia.hobbs@abbvie.com\nPhone: (446)673-8121x90878\n"
26,NaN,2023-06-13 08:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Annual Plan & Strategic Priorities,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nCan we discuss quarterly targets aligned with liquidity goals?\n\nBest,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
27,NaN,2023-06-13 08:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Annual Plan & Strategic Priorities,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nCan we discuss quarterly targets aligned with liquidity goals?\n\nBest,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
28,NaN,2023-06-06 08:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Global Macro Outlook & Policy Impact,"Dear Jane,\n\nThank you for your email. Dear Jane,\n\nThoughts on Fed policy trajectory?\n\nRegards,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
29,NaN,2023-06-06 08:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Global Macro Outlook & Policy Impact,"Dear Jane,\n\nThank you for your email. Dear Jane,\n\nThoughts on Fed policy trajectory?\n\nRegards,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"

In [237]:
df = pd.read_sql("""SELECT *
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'cynthia.hobbs@abbvie.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'cynthia.hobbs@abbvie.com') 
        and email_timestamp > '2019-01-12 09:45:00'
        order by email_timestamp""", con=engine)
df.head(30)

,index,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,93.0,2020-06-16 13:15:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: AbbVie - Quarterly Relationship Review,"Hi Cynthia,\n\nJuly 7th at 11 AM CT is confirmed. I'll send the meeting invite.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
1,138.0,2021-06-10 14:00:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,AbbVie - Information on International ACH (IAT) Payments,"Hi Cynthia,\n\nDuring our last review, you briefly mentioned exploring more efficient ways to handle certain recurring international payments. Bankwell offers International ACH (IAT) capabilities, which can often be more cost-effective than wires for specific types of cross-border payments.\n\nWould you be interested in learning more about our IAT service, including country coverage and processing requirements?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
2,139.0,2021-06-11 09:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Information on International ACH (IAT) Payments,"Hi Jane,\n\nYes, potentially. We have a number of recurring payments to suppliers in Canada and some EU countries where IAT might be applicable. Please send over some information on the service and typical cost savings compared to wires.\n\nBest,\n\n--\nCynthia Hobbs\nDirector\nAbbVie\nEmail: cynthia.hobbs@abbvie.com\nPhone: (446)673-8121x90878\n"
3,140.0,2021-06-11 11:30:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: AbbVie - Information on International ACH (IAT) Payments,"Hi Cynthia,\n\nWill do. I've attached our IAT service overview, which includes country details and a general comparison to wire transfer fees. Happy to discuss specifics for your payment flows when you're ready.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
4,183.0,2022-06-22 11:30:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,AbbVie - Setting up IAT Payments,"Hi Cynthia,\n\nFollowing up on the International ACH (IAT) information I sent. If AbbVie would like to proceed with setting up IAT payments for specific beneficiaries (e.g., in Canada or Europe), there's a brief setup process involved.\n\nWe would need the beneficiary bank details in the required format and would activate the IAT capability on your Treasury Management platform. Would you like to schedule a call with our operations team to walk through the setup?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
5,184.0,2022-06-23 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Setting up IAT Payments,"Hi Jane,\n\nYes, we'd like to start using IAT for our Canadian dollar payments initially. A call with your operations team to understand the setup and required beneficiary information would be helpful. Can they propose some times next week?\n\nBest,\n\n--\nCynthia Hobbs\nDirector\nAbbVie\nEmail: cynthia.hobbs@abbvie.com\nPhone: (446)673-8121x90878\n"
6,185.0,2022-06-23 10:15:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: AbbVie - Setting up IAT Payments,"Hi Cynthia,\n\nExcellent. I'll have our IAT specialist reach out to you directly with their availability for next week to schedule the setup call.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
7,NaN,2023-05-03 05:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - ESG Fund Portfolio & Benchmark Review,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nUpdates on ESG rating methodologies?\n\nCheers,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
8,NaN,2023-05-03 05:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - ESG Fund Portfolio & Benchmark Review,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nUpdates on ESG rating methodologies?\n\nCheers,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
9,NaN,2023-05-09 04:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Risk Exposure & Counterparty Controls,"Dear Jane,\n\nThank you for your email. Jane,\n\nCan you review interest rate hedges?\n\nBest,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
10,NaN,2023-05-09 04:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Risk Exposure & Counterparty Controls,"Dear Jane,\n\nThank you for your email. Jane,\n\nCan you review interest rate hedges?\n\nBest,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
11,NaN,2023-05-09 09:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - SEC Policy Briefing & Discussion,"Dear Jane,\n\nThank you for your email. Dear Jane,\n\nLooking forward to state-level compliance updates.\n\nRegards,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
12,NaN,2023-05-09 09:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - SEC Policy Briefing & Discussion,"Dear Jane,\n\nThank you for your email. Dear Jane,\n\nLooking forward to state-level compliance updates.\n\nRegards,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
13,NaN,2023-05-12 18:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Tax Deferral Strategy & Harvesting,"Dear Jane,\n\nThank you for your email. Hello Jane,\n\nAny updates on IRS guidance?\n\nThanks,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
14,NaN,2023-05-12 18:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Tax Deferral Strategy & Harvesting,"Dear Jane,\n\nThank you for your email. Hello Jane,\n\nAny updates on IRS guidance?\n\nThanks,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
15,NaN,2023-05-17 23:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Proposed Benchmark Re-alignment Overview,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nImpacts of benchmark realignment?\n\nThanks,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
16,NaN,2023-05-17 23:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Proposed Benchmark Re-alignment Overview,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nImpacts of benchmark realignment?\n\nThanks,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
17,NaN,2023-05-24 00:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Growth & Fixed Income Launch Overview,"Dear Jane,\n\nThank you for your email. Jane,\n\nPrivate credit options?\n\nBest,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
18,NaN,2023-05-24 00:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Growth & Fixed Income Launch Overview,"Dear Jane,\n\nThank you for your email. Jane,\n\nPrivate credit options?\n\nBest,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
19,NaN,2023-06-06 08:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Global Macro Outlook & Policy Impact,"Dear Jane,\n\nThank you for your email. Dear Jane,\n\nThoughts on Fed policy trajectory?\n\nRegards,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
20,NaN,2023-06-06 08:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Global Macro Outlook & Policy Impact,"Dear Jane,\n\nThank you for your email. Dear Jane,\n\nThoughts on Fed policy trajectory?\n\nRegards,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
21,NaN,2023-06-13 08:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Annual Plan & Strategic Priorities,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nCan we discuss quarterly targets aligned with liquidity goals?\n\nBest,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
22,NaN,2023-06-13 08:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Annual Plan & Strategic Priorities,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nCan we discuss quarterly targets aligned with liquidity goals?\n\nBest,\nCynthia Hobbs\n\nBest regards,\nCynthia Hobbs"
23,91.0,2024-05-08 11:05:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,AbbVie - Quarterly Relationship Review,"Hi Cynthia,\n\nI'd like to schedule our standard quarterly relationship review call for sometime in early July.\n\nWe can review the performance of the cash management structure, discuss any upcoming financial needs or projects at AbbVie, and provide a brief market update. Please let me know what dates/times work best for you.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
24,92.0,2024-05-08 16:05:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Quarterly Relationship Review,"Hi Jane,\n\nA quarterly review sounds good. How about July 7th at 11 AM CT?\n\nBest,\n\n--\nCynthia Hobbs\nDirector\nAbbVie\nEmail: cynthia.hobbs@abbvie.com\nPhone: (446)673-8121x90878\n"
25,51.0,2024-06-07 11:05:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,AbbVie - Cash Management Implementation Update,"Hi Cynthia,\n\nI hope the implementation of the new cash concentration structure is proceeding smoothly. Our operations team confirmed the final account linkages went live yesterday.\n\nPlease let me know if you or your team have encountered any issues or have any questions as you start using the new setup. We want to ensure a seamless transition.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
26,52.0,2024-06-08 11:05:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Cash Management Implementation Update,"Hi Jane,\n\nThanks for checking in. So far, everything looks good from our end. The initial sweeps occurred as expected this morning. We'll monitor it closely over the next few days, but the transition seems smooth. Appreciate your team's support.\n\nBest,\n\n--\nCynthia Hobbs\nDirector\nAbbVie\nEmail: cynthia.hobbs@abbvie.com\nPhone: (446)673-8121x90878\n"
27,226.0,2024-07-06 11:00:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,AbbVie - Quarterly Relationship Review - Q3 2023,"Hi Cynthia,\n\nTime to schedule our Q3 relationship review call. Can we aim for sometime in the second half of July?\n\nWe can cover the performance of the cash management and IAT services, discuss any upcoming initiatives at AbbVie, and provide a market/economic update.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
28,227.0,2024-07-07 13:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Re: AbbVie - Quarterly Relationship Review - Q3 2023,"Hi Jane,\n\nYes, let's schedule the Q3 review. How about July 25th at 1 PM CT?\n\nBest,\n\n--\nCynthia Hobbs\nDirector\nAbbVie\nEmail: cynthia.hobbs@abbvie.com\nPhone: (446)673-8121x90878\n"
29,12.0,2024-11-17 08:33:00,Cynthia Hobbs,cynthia.hobbs@abbvie.com,Jane Moneypenny,jane.moneypenny@bankwell.com,AbbVie - documentation review,"Hi Cynthia, Hope the documentation review for the credit facility is progressing well on your side. Our legal team has incorporated the comments from your counsels last turn.Are there any final points to address before we target execution and closing, perhaps next week? Best regards, Jane Moneypenny"

## Compass

In [53]:
df1 = pd.read_sql("""SELECT * FROM meeting_data 
where host_email ='jane.moneypenny@bankwell.com' and invitee_emails = 'adam.clay@compass.com'
order by meeting_timestamp desc Limit 20""", con=engine)
df1.head(20)

,index,meeting_timestamp,host,host_email,invitees,invitee_emails,meeting_subject
0,NaN,2025-06-16 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - AML Requirements & Policy Developments
1,NaN,2025-05-25 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - ESG Ratings Dashboard Review
2,NaN,2025-05-21 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Charitable Deduction & Gift Strategy
3,NaN,2025-05-17 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Capital Allocation & Milestone Mapping
4,NaN,2025-05-17 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Strategic Risk Metrics & Tolerance Review
5,NaN,2025-03-17 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Geopolitical Risks & Global Supply Effects
6,NaN,2025-03-16 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Tracking Error & Volatility Shift Study
7,NaN,2025-02-06 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Low-Volatility Fund Enhancements
8,93.0,2024-03-26 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Annual Credit Facility Review Meeting
9,51.0,2021-10-01 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Credit Facility Documentation Final Review Call
10,34.0,2020-09-15 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Credit Facility Term Sheet Follow-up Discussion
11,18.0,2019-09-17 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Credit Facility Term Sheet Review
12,5.0,2018-09-25 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - Discuss Expansion Financing Needs

In [47]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE meeting_data 
        SET meeting_timestamp = '2025-02-06 10:00:00'
        WHERE host_email = 'jane.moneypenny@bankwell.com'
          AND invitee_emails = 'adam.clay@compass.com'
          AND TRIM(meeting_timestamp) = '2025-06-01 13:00:00' 
    """))

In [52]:
df = pd.read_sql("""SELECT *
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'adam.clay@compass.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'adam.clay@compass.com') 
        --and email_timestamp < '2025-05-30 11:00:00'
        order by email_timestamp desc
        """, con=engine)
df.head(30)

,index,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,NaN,2025-06-14 20:15:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - AML Requirements & Policy Developments,"Hi Adam, I am happy to discuss. I will have our research team pull together a briefing on AML requirements. I know there is increased scrutiny around Real Estate in particular. I will set a meeting shortly for us to go over Compass policy together. Thanks, Jane"
1,1.0,2025-06-14 18:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - AML Requirements & Policy Developments,"Jane, I saw an update in regulations from the SEC on AML. Compass legal team has some updated policies on funds documentation to comply that I would like to make sure we are using going forward. Have you heard of any other AML regulation updates we should be aware of? Thanks, Adam"
2,NaN,2025-06-11 08:15:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Tracking Error & Volatility Shift Study,"Hi Adam, Wanted to let you know that we resolved the tracking error in the Volatility Shift Study. Apologies for any inconvenience. Many thanks, Jane"
3,NaN,2025-06-09 16:30:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Geopolitical Risks & Global Supply Effects,"Hello Adam Clay,\n\nFed policy divergence and trajectory review.\n\nRegards,\nJane"
4,NaN,2025-05-30 16:00:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Low-Volatility Fund Enhancements,"Hi Adam, Please see attached our Volatility Shift Study. We see reduced volatility compared to Q1 now that the new administration has calmed down. We have added to our offerings of low-volatility funds, which may be of interest to Compass. Many thanks, Jane"
5,NaN,2025-05-23 22:45:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - ESG Ratings Dashboard Review,"Hi Adam, I will gather a list of updated stocks in the CSI index for us to review when we meet. Im asking Ryan to get you an updated link to the dashboard as well. Look forward to speaking soon, Jane"
6,1.0,2025-05-21 09:47:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - ESG Ratings Dashboard Review,"Hi Jane, Thank you for bringing this to my attention. I know our board is particularly concerned with the Carbon Score index on the dashboard. Which stocks have been added to the CSI index that were not there previously? Thanks, Adam"
7,NaN,2025-05-21 06:15:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - ESG Ratings Dashboard Review,"Hi Adam, Hope you are doing well. I wanted to reach out to alert you to changes in the S&P 500 Carbon Efficient Index that may impact our ESG dashboard. I know you have been a frequent user of the dashboard in the past. I scheduled a meeting to walk through how Carbon Index is reflected on the ESG Ratings Dashboard, and discuss other ESG concerns. Many thanks, Jane"
8,NaN,2025-05-17 03:15:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Capital Allocation & Milestone Mapping,"Hi Adam Clay,\n\nCapital allocation and milestone mapping.\n\nCheers,\nJane"
9,NaN,2025-05-15 19:00:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Strategic Risk Metrics & Tolerance Review,"Hello Adam Clay,\n\nStress testing scenarios walkthrough.\n\nRegards,\nJane"
10,237.0,2023-09-29 14:00:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Utilizing the Credit Facility,"Hi Adam,\n\nHope you're well. Just checking in now that the credit facility has been in place for a while.\n\nAre you finding the process for drawdowns and reporting satisfactory? Please let me know if you or your team need any assistance or have feedback on using the line.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
11,194.0,2022-10-06 10:00:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Credit Facility Closed,"Hi Adam,\n\nGreat news - confirming that the $25M revolving credit facility for Compass officially closed and funded this morning.\n\nIt was a pleasure working with you and your team to get this finalized. Please don't hesitate to reach out if any questions arise as you begin utilizing the facility. Our loan operations team is also available for any administrative support.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
12,151.0,2021-09-29 10:15:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Compass - Credit Facility Documentation Status,"Hi Adam,\n\nSounds good. We'll prepare for a potential closing next Wednesday and await your final confirmation.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
13,149.0,2021-09-28 15:30:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Credit Facility Documentation Status,"Hi Adam,\n\nHope the documentation review for the credit facility is progressing well on your side. Our legal team has incorporated the comments from your counsel's last turn.\n\nAre there any final points to address before we target execution and closing, perhaps next week?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
14,104.0,2020-09-21 11:45:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Compass - Credit Facility Next Steps,"Hi Adam,\n\nExcellent news. I'll instruct our legal counsel and loan operations team to begin drafting immediately. Typically, we can provide initial drafts within 5-7 business days. I'll keep you updated on the progress.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
15,102.0,2020-09-17 15:00:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Credit Facility Next Steps,"Hi Adam,\n\nFollowing up on our call last week regarding the proposed credit facility term sheet. You mentioned needing to finalize internal approvals.\n\nJust checking in on the status and if there are any outstanding questions from your legal or finance teams that I can help address. We're ready to move to definitive documentation when you are.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
16,61.0,2019-09-10 14:45:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Credit Facility Term Sheet,"Hi Adam,\n\nFollowing our discussions and review of Compass's preliminary financials, please find attached the indicative term sheet for the proposed $25M revolving line of credit.\n\nThis outlines the key terms, conditions, indicative pricing, and proposed covenants. Please review with your team, and I'm available to discuss any points in detail.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
17,14.0,2018-09-18 13:30:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Meeting Request: Compass Expansion Financing,"Hi Adam,\n\nExcellent. Tuesday at 10 AM ET is confirmed. I'll send a calendar invite. I look forward to learning more about Compass's plans.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
18,13.0,2018-09-18 13:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Re: Meeting Request: Compass Expansion Financing,"Hi Jane,\n\nGood timing. Yes, we are evaluating options for a new credit facility. I can chat next Tuesday morning. Does 10 AM ET work?\n\nRegards,\n\n--\nAdam Clay\nVP\nCompass\nEmail: adam.clay@compass.com\nPhone: -2931\n"
19,12.0,2018-09-18 09:00:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Meeting Request: Compass Expansion Financing,"Hi Adam,\n\nHope you're having a good week. I wanted to follow up on our brief chat at the Real Estate Finance conference last month regarding Compass's potential need for expansion capital.\n\nBankwell Financial offers various financing solutions, including lines of credit and term loans tailored for growth companies. Would you be available for a call next week to discuss your potential needs and how we might assist?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"

In [51]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE email_data
        SET email_body = 'Hi Adam, Please see attached our Volatility Shift Study. We see reduced volatility compared to Q1 now that the new administration has calmed down. We have added to our offerings of low-volatility funds, which may be of interest to Compass.  Many thanks, Jane'
        WHERE to_emails = 'adam.clay@compass.com'
          AND from_email = 'jane.moneypenny@bankwell.com'
          AND TRIM(email_timestamp) = '2025-05-30 16:00:00' 
    """))

In [44]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE email_data
        SET email_body = 'Jane, I saw an update in regulations from the SEC on AML. Compass legal team has some updated policies on funds documentation to comply that I would like to make sure we are using going forward. Have you heard of any other AML regulation updates we should be aware of? Thanks, Adam'
        WHERE to_emails = 'jane.moneypenny@bankwell.com'
          AND from_email = 'adam.clay@compass.com'
          AND TRIM(email_timestamp) = '2025-06-14 18:15:00' 
    """))

In [33]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""INSERT INTO email_data (index	
    , email_timestamp
    , to_names
    , to_emails
    , from_name	
    , from_email
    , email_subject	
    , email_body)
VALUES (1
, '2025-05-21 09:47:00'
, 'Jane Moneypenny'
, 'jane.moneypenny@bankwell.com'
, 'Adam Clay'
, 'adam.clay@compass.com'
, 'Compass - ESG Ratings Dashboard Review'
, 'Hi Jane, Thank you for bringing this to my attention. I know our board is particularly concerned with the Carbon Score index on the dashboard. Which stocks have been added to the CSI index that were not there previously? Thanks, Adam'
)"""))

In [15]:
df2 = pd.read_sql("""SELECT email_timestamp
        , to_names	
        , to_emails
        , from_name
        , from_email
        , email_subject
        , email_body
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'lisa.kennedy@lockheedmartincorporation.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'lisa.kennedy@lockheedmartincorporation.com') 
        order by email_timestamp desc
        """, con=engine)
df2.head(20)

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2023-03-15 14:00:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Lockheed Martin - Inquiry: Bankwell ESG Investment Capabilities,"Hi Lisa,\n\nCertainly. For early April, how about April 4th at 11 AM ET or April 6th at 1 PM ET?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
1,2023-03-15 13:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Lockheed Martin - Inquiry: Bankwell ESG Investment Capabilities,"Hi Jane,\n\nYes, an updated presentation focused on your ESG capabilities would be timely, as our committee continues to evaluate this area. Can you propose some times in early April?\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
2,2023-03-14 11:00:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Lockheed Martin - Inquiry: Bankwell ESG Investment Capabilities,"Hi Lisa,\n\nHope you're well. Following up on our brief discussion last year about ESG considerations in pension management.\n\nBankwell has continued to expand its capabilities in ESG-integrated investment strategies across various asset classes. Would you be open to a brief, updated presentation focused specifically on our ESG offerings for institutional clients like Lockheed Martin's pension plan?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
3,2022-03-09 10:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Lockheed Martin - Update on Interest Rate Environment & LDI,"Hi Jane,\n\nThank you for sharing the update on the rate environment. It's certainly a dynamic period for LDI management. I'll share this with our internal team and consultants.\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
4,2022-03-08 14:30:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Lockheed Martin - Update on Interest Rate Environment & LDI,"Hi Lisa,\n\nGiven the recent significant shifts in the interest rate outlook, I wanted to provide a brief update on the potential implications for pension LDI strategies.\n\nHigher rates can impact funded status and liability valuations. The attached note provides some commentary. Happy to discuss specific implications for Lockheed Martin's plan if helpful, although I know you work with several dedicated managers.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
5,2021-02-12 13:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Lockheed Martin - Economic Update & Pension Trends,"Hi Jane,\n\nThanks for sharing these reports. I'll take a look when I have a moment. ESG is certainly a growing topic of discussion for our committee.\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
6,2021-02-11 11:30:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Lockheed Martin - Economic Update & Pension Trends,"Hi Lisa,\n\nHope you're having a good start to the year. I wanted to share our latest Bankwell economic outlook report and a piece our institutional team put together on recent trends in pension fund management, particularly around ESG considerations and alternative investments.\n\nNo action needed, just thought these might be of interest given your role. Happy to discuss any points if you'd like.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
7,2020-02-19 10:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Follow Up: Lockheed Martin LDI Presentation,"Hi Jane,\n\nThanks for following up. The presentation was informative. We don't have an active LDI manager search at this precise moment, but we've added Bankwell to our list of potential managers for future consideration when the need arises. We appreciate the information shared.\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
8,2020-02-18 14:00:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Follow Up: Lockheed Martin LDI Presentation,"Hi Lisa,\n\nI wanted to follow up after our LDI presentation earlier this month. I hope it provided a helpful overview of Bankwell's capabilities in managing fixed-income strategies for pension plans.\n\nPlease let me know if you or the pension committee have any further questions or if you'd like any additional information as you continue your manager reviews.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
9,2019-02-06 14:00:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Lockheed Martin - Pension Fund Investment Strategy,"Hi Lisa,\n\nCertainly. How about March 5th at 1 PM ET or March 7th at 10 AM ET for the presentation?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
10,2019-02-06 11:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Lockheed Martin - Pension Fund Investment Strategy,"Hi Jane,\n\nThank you for following up. LDI is a key focus for our pension committee. We typically engage with managers through formal searches, but I'm open to an introductory presentation on Bankwell's capabilities in this specific area. Can you suggest some times in early March?\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
11,2019-02-05 09:30:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Lockheed Martin - Pension Fund Investment Strategy,"Hi Lisa,\n\nFollowing our introductory discussion regarding Bankwell's institutional asset management capabilities, I wanted to explore further how we might assist with specific segments of Lockheed Martin's pension fund investments.\n\nWe have particular expertise in managing fixed-income mandates focused on liability-driven investing (LDI) principles. Would you be open to a more detailed presentation on our LDI strategies and performance?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"

# Update preference dates

In [17]:
pd.read_sql("SELECT * FROM preferences where email = 'jane.moneypenny@bankwell.com' ", con=engine)

,as_of_date,employee_first_name,employee_last_name,email,title,finance_detail,news_detail,macro_news_detail,past_meeting_detail
0,2023-01-23 10:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,full,full,full,full
1,2023-04-02 10:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,short,full,full,short
2,2023-07-26 14:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,none,none,full,short
3,2023-11-04 10:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,short,full,none,none
4,2024-01-30 10:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,short,full,none,full
5,2024-03-10 09:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,full,none,full,full
6,2025-04-03 09:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,full,full,full,full
7,2025-05-19 05:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,short,full,none,full
8,2025-06-12 09:00:00,Jane,Moneypenny,jane.moneypenny@bankwell.com,Relationship Manager,full,full,full,full

In [19]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""INSERT INTO preferences (as_of_date
    , employee_first_name
    , employee_last_name
    , email
    , title
    , finance_detail
    , news_detail
    , macro_news_detail
    , past_meeting_detail)
VALUES ( '2025-05-02 09:00:00'
, 'Jane'
, 'Moneypenny'
, 'jane.moneypenny@bankwell.com'
, 'Relationship Manager'
, 'short'
, 'full'
, 'none'
, 'full'
)"""))

In [17]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""INSERT INTO preferences (as_of_date
    , employee_first_name
    , employee_last_name
    , email
    , title
    , finance_detail
    , news_detail
    , macro_news_detail
    , past_meeting_detail)
VALUES ( '2025-05-25 05:00:00'
, 'Jane'
, 'Moneypenny'
, 'jane.moneypenny@bankwell.com'
, 'Relationship Manager'
, 'full'
, 'none'
, 'full'
, 'none'
)"""))

In [19]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE preferences 
        SET finance_detail = 'full', past_meeting_detail = 'short', macro_news_detail= 'full'
        WHERE email = 'jane.moneypenny@bankwell.com'
          AND TRIM(as_of_date) = '2025-06-12 09:00:00' 
    """))

In [22]:
pd.read_sql("""SELECT as_of_date,  email
    , past_meeting_detail
    , news_detail
    , finance_detail
    , macro_news_detail
     FROM preferences where email = 'jane.moneypenny@bankwell.com' 
     and as_of_date >= '2025-04-03 09:00:00'
     order by as_of_date desc""", con=engine)

,as_of_date,email,past_meeting_detail,news_detail,finance_detail,macro_news_detail
0,2025-06-12 09:00:00,jane.moneypenny@bankwell.com,short,full,full,full
1,2025-05-25 05:00:00,jane.moneypenny@bankwell.com,none,none,full,full
2,2025-05-19 05:00:00,jane.moneypenny@bankwell.com,none,full,full,full
3,2025-05-02 09:00:00,jane.moneypenny@bankwell.com,full,full,none,none
4,2025-04-03 09:00:00,jane.moneypenny@bankwell.com,full,full,full,full

In [ ]:
# april preferences are all full 
# may 18 ish preferences are short on stuff
# mid june go back to full

# Change hasbro meetings and past emails