In [1]:
from google.cloud import secretmanager
import pandas as pd
import numpy as np
from currensee.utils.db_utils import create_pg_engine
from sqlalchemy import text

import pandas as pd
import random
import os
import re
from faker import Faker

2025-07-28 02:58:15,418 - currensee.core.secrets - INFO - PROJECT_ID not found, attempting to load from .env file
2025-07-28 02:58:15,422 - currensee.core.secrets - INFO - Loaded environment from ./.env
2025-07-28 02:58:15,424 - currensee.core.secrets - INFO - SecretManager initialized with project_id: adsp-34002-on02-sopho-scribe

In [2]:
# Update dates to all be in 2025
# Update preference changes to all be more recent to still show variation

In [3]:
# Define DB_NAME
DB_NAME = "crm_outlook"

In [4]:
engine = create_pg_engine(db_name=DB_NAME)

In [5]:
pd.set_option('display.max_colwidth', None)

In [6]:
df1 = pd.read_sql("""SELECT * FROM meeting_data 
where host_email ='jane.moneypenny@bankwell.com' 
order by meeting_timestamp desc""", con=engine)
df1.head(20)

,index,meeting_timestamp,host,host_email,invitees,invitee_emails,meeting_subject
0,NaN,2025-06-29 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Operational Risk Case Study Analysis
1,NaN,2025-06-28 15:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Michelle Jenkins,michelle.jenkins@intuitivesurgical.com,Intuitive Surgical - Alternative Investment Tax Structures
2,NaN,2025-06-28 15:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Guardant Health - Social Governance Strategy Benchmarking
3,NaN,2025-06-28 09:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - Financial Goals & Resource Planning
4,NaN,2025-06-27 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - Innovative Funds & Investment Outlook
5,NaN,2025-06-27 09:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Amy Winters,amy.winters@gamestopcorp.com,GameStop Corp - Treasury Strategy & Finance Objectives
6,NaN,2025-06-25 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Emerging Market Growth vs. Headwinds
7,NaN,2025-06-24 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Liquidity & Daily Redemption Strategies
8,NaN,2025-06-24 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Guardant Health - Diversified Fund Comparison Walkthrough
9,NaN,2025-06-23 12:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - ESG Trends & Fund Flow Insights
10,NaN,2025-06-22 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Mid-Year Objective Adjustment Review
11,NaN,2025-06-22 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Kyle Waters,kyle.waters@amedisys.com,Amedisys - Impact Investing & Green Bond Opportunities
12,NaN,2025-06-18 09:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Amy Winters,amy.winters@gamestopcorp.com,GameStop Corp - State-Level Regulatory Insights
13,NaN,2025-06-18 09:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jennifer Phelps,jennifer.phelps@aerovironment.com,AeroVironment - FX & Interest Rate Risk Strategy Review
14,NaN,2025-06-16 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - Tax Across Jurisdictions Alignment
15,NaN,2025-06-16 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Compass - AML Requirements & Policy Developments
16,NaN,2025-06-15 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Denise Moore,denise.moore@celestica.com,Celestica - Alternative Credit & Private Credit Strategy
17,NaN,2025-06-14 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jennifer Phelps,jennifer.phelps@aerovironment.com,AeroVironment - Inflation & Rate Forecast Scenario
18,NaN,2025-06-14 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - Implementation Timeline & Fit Review
19,NaN,2025-06-14 09:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Ronnie Gray,ronnie.gray@laddercapitalcorp.com,Ladder Capital Corp - International Regulatory Coordination Update

## Hasbro

In [109]:
df1 = pd.read_sql("""SELECT * FROM meeting_data 
where host_email ='jane.moneypenny@bankwell.com' and invitee_emails = 'jessica.palmer@hasbro.com'
order by meeting_timestamp desc""", con=engine)
df1.head(30)

,index,meeting_timestamp,host,host_email,invitees,invitee_emails,meeting_subject
0,94.0,2025-07-10 14:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss Portfolio Diversification and Bond Strategy
1,NaN,2025-06-29 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Operational Risk Case Study Analysis
2,NaN,2025-06-25 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Emerging Market Growth vs. Headwinds
3,NaN,2025-06-24 16:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Liquidity & Daily Redemption Strategies
4,NaN,2025-05-17 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - ESG Integration Framework & Screening
5,NaN,2025-05-16 13:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Fit vs. Mandate: Benchmark Transition
6,NaN,2025-05-03 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Bonus Deferral & Reporting Optimization
7,NaN,2025-05-01 12:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Disclosure Timeline Revision Review
8,NaN,2025-05-01 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Strategic Targets Rollout Discussion
9,81.0,2023-12-11 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Finalize H1 2024 FX Hedging Strategy
10,67.0,2023-01-10 10:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss H1 2023 FX Hedging Strategy
11,8.0,2018-11-14 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Discuss FX Risk Management Strategies (Forwards vs. Options)

In [108]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE meeting_data 
        SET meeting_subject = 'Hasbro - Discuss Portfolio Diversification and '
        WHERE host_email = 'jane.moneypenny@bankwell.com'
          AND invitee_emails = 'jessica.palmer@hasbro.com'
          AND TRIM(meeting_timestamp) = '2025-07-10 14:30:00' 
    """))

In [106]:
df = pd.read_sql("""SELECT *
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com') 
        order by email_timestamp desc""", con=engine)
df.head(10)

,index,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,258.0,2025-07-10 09:10:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica, Great, I will schedule us for 2:30 on the 10th. Best regards, Jane Moneypenny; Financial Advisor; Bankwell Financial; Phone: (555) 123-4567; Email: jane.moneypenny@outlook.com"
1,257.0,2025-07-09 16:10:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi jane, Yes, this needs further thought. I can do 1-5pm tomorrow, or 9am on the 13th. Let me know which works for you. Regards, Jessica Palmer, VP Hasbro Email: jessica.palmer@hasbro.com Phone: 909.878.8329x31984"
2,256.0,2025-07-09 13:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica, I will have our research team further look into small-cap consumer entertainment trends, but from what I have seen in the news I dont believe conditions will shift impactfully before end of year. I suggest we meet soon to have an in depth discussion of the impact of Hasbros risk strategy post divestiture and bond fund allocation. Best, Jane"
3,255.0,2025-07-08 09:40:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Hasbro - Post Divestiture Strategy Adjustments,"Thanks Jane,\n\nThank you for the update. Seems like we need to reevaluate our strategy. I am hesitant to change much at this moment given the likely update to senior leadership. Do you believe that current market trends will continue regarding small-cap consumer entertainment? \n\n Also, I am curious about our allocation in bond funds. Given current inflation, what is the likely impact on the bond market, i.e. should we consider moving further out of bonds? \n\nRegards,\n\n--\nJessica Palmer\nVP\nHasbro\nEmail: jessica.palmer@hasbro.com\nPhone: 909.878.8329x31984\n"
4,254.0,2025-07-06 08:05:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Post Divestiture Strategy Adjustments,"Hi Jessica, I am reaching out regarding Hasbros Q3 goals. I understand that the recent divestitures have been completed. I ran a quick comparative performance check across your key equity positions. Your exposure to small-cap consumer entertainment stocks underperformed the S&P benchmark by roughly 2.3% over the last 6 weeks. That said, your positions in structured notes tied to diversified consumer indexes helped buffer some of the downside. We can explore reallocating a portion of your discretionary sector holdings to lower beta instruments or consider sector-rotation strategies if you would like. We can wait further to see how things evolve, but worth considering an adjustment in the nearterm based on market trends. Best regards, Jane Moneypenny, Financial Advisor, Bankwell Financial, Phone: (555) 123-4567, Email: jane.moneypenny@outlook.com"
5,NaN,2025-06-29 07:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Operational Risk Case Study Analysis,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nWould you prepare for FX exposure discussion?\n\nThanks,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
6,NaN,2025-06-29 07:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Operational Risk Case Study Analysis,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nWould you prepare for FX exposure discussion?\n\nThanks,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
7,NaN,2025-06-28 13:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Operational Risk Case Study Analysis,"Hello Jessica Palmer,\n\nStress testing scenarios walkthrough.\n\nRegards,\nJane"
8,NaN,2025-06-25 12:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Emerging Market Growth vs. Headwinds,"Dear Jane,\n\nThank you for your email. Jane,\n\nGeopolitical risk implications?\n\nBest,\nJessica Palmer\n\nBest regards,\nJessica Palmer"
9,NaN,2025-06-25 12:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Emerging Market Growth vs. Headwinds,"Dear Jane,\n\nThank you for your email. Jane,\n\nGeopolitical risk implications?\n\nBest,\nJessica Palmer\n\nBest regards,\nJessica Palmer"

In [105]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE email_data
        SET email_body = 'Hi jane,  Yes, this needs further thought. I can do 1-5pm tomorrow, or 9am on the 13th. Let me know which works for you. Regards, Jessica Palmer, VP Hasbro  Email: jessica.palmer@hasbro.com  Phone: 909.878.8329x31984'
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com')
          AND from_email in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com')
          AND TRIM(email_timestamp) = '2025-07-09 16:10:00' 
    """))

In [89]:
with engine.begin() as connection:  # ensures COMMIT
    connection.execute(text("""
        UPDATE email_data
        SET email_timestamp = '2025-07-05 13:25:00'
        WHERE to_emails = 'jessica.palmer@hasbro.com'
          AND from_email = 'jane.moneypenny@bankwell.com'
          AND TRIM(email_timestamp) = '2024-01-20 14:40:00'
    """))

In [91]:
df = pd.read_sql("""SELECT email_timestamp
        , to_names	
        , to_emails
        , from_name
        , from_email
        , email_subject
        , email_body
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'jessica.palmer@hasbro.com') 
        and email_timestamp < '2025-04-30'
        order by email_timestamp desc""", con=engine)
df.head(20)

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2025-04-29 20:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Disclosure Timeline Revision Review,"Dear Jessica Palmer,\n\nReminder of our SEC policy briefing. Please share any points you'd like covered.\n\nBest,\nJane"
1,2023-12-12 11:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Thanks Jane,\n\nI will follow up if I have any issues. Happy holidays! \n\nRegards,\n\n--\nJessica Palmer\nVP\nHasbro\nEmail: jessica.palmer@hasbro.com\nPhone: 909.878.8329x31984\n"
2,2023-12-12 10:40:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Hi Jessica,\n\nGreat to speak with you yesterday. I have executed the FX Hedging strategy we discussed, and adjusting for a more conservativre risk profile. Please elt me know if you have any further questions. You can see the adjusted portfolio in your customer portal. I reccomend we check in again in Q1 next year to evaluate strategy after Hasbro's potential divestitures have been completed. \n\n Hope you enjoy time off over the holiday season! \n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
3,2023-11-22 10:45:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Hi Jessica,\n\nDecember 11th at 11 AM ET works. I'll send the invite and prepare some strategy considerations.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
4,2023-11-22 10:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Hi Jane,\n\nYes, let's connect. How about December 11th at 11 AM ET?\n\nRegards,\n\n--\nJessica Palmer\nVP\nHasbro\nEmail: jessica.palmer@hasbro.com\nPhone: 909.878.8329x31984\n"
5,2023-11-21 15:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Strategy Discussion for H1 2024 FX Hedging,"Hi Jessica,\n\nFollowing up on our call earlier this month regarding the H1 2023 hedge performance. Let's schedule time to finalize the FX hedging strategy for H1 2024.\n\nMarket conditions continue to evolve, so we should review Hasbro's objectives and risk tolerance. Please let me know your availability in early December.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
6,2022-12-07 11:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Hasbro - Review of H1 2022 FX Hedge Performance,"Hi Jessica,\n\nCertainly. For early January, how about Jan 10th at 10 AM ET or Jan 12th at 2 PM ET?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
7,2022-12-07 11:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Review of H1 2022 FX Hedge Performance,"Hi Jane,\n\nThanks for sending the performance review. It looks like the forwards provided good budget certainty in a volatile period. Let's schedule time in early January to discuss the H1 2023 strategy. Can you propose some times?\n\nRegards,\n\n--\nJessica Palmer\nVP\nHasbro\nEmail: jessica.palmer@hasbro.com\nPhone: 909.878.8329x31984\n"
8,2022-12-06 09:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Review of H1 2022 FX Hedge Performance,"Hi Jessica,\n\nAs we approach the maturity of the H1 2022 FX hedges, I wanted to provide a preliminary performance review comparing the hedged rates achieved versus the average spot rates during the period.\n\nPlease find the analysis attached. We can discuss this in more detail when we connect to plan the H1 2023 hedging strategy.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
9,2021-12-02 09:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Execution of H1 2022 FX Hedges,"Hi Jane,\n\nExcellent, thanks for the prompt execution and confirmation. All looks good. Appreciate getting these locked in before year-end.\n\nRegards,\n\n--\nJessica Palmer\nVP\nHasbro\nEmail: jessica.palmer@hasbro.com\nPhone: 909.878.8329x31984\n"
10,2021-12-01 14:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Execution of H1 2022 FX Hedges,"Hi Jessica,\n\nConfirming that we have executed the EUR and GBP forward contracts for H1 2022 as per your instructions this morning.\n\nRates locked in were in line with the indicative levels discussed last week. Confirmation details are attached. Please let me know if you need anything further.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
11,2020-11-25 14:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Hasbro - Decision on H1 2021 FX Hedging,"Hi Jessica,\n\nUnderstood. I'll prepare the indicative pricing for the forwards and option scenarios you described based on today's market data and aim to get that over to you by end of day tomorrow.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
12,2020-11-25 10:10:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - Decision on H1 2021 FX Hedging,"Hi Jane,\n\nThanks for the nudge. We've decided to primarily use forward contracts for the bulk of our H1 2021 EUR and GBP exposure to lock in budget rates, perhaps with a small layer of options for flexibility if pricing is attractive.\n\nCan you provide indicative pricing for 3-month and 6-month forwards based on current markets, and maybe some indicative costs for simple 6-month call options (say, 2-3% out-of-the-money)?\n\nRegards,\n\n--\nJessica Palmer\nVP\nHasbro\nEmail: jessica.palmer@hasbro.com\nPhone: 909.878.8329x31984\n"
13,2020-11-23 15:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - Decision on H1 2021 FX Hedging,"Hi Jessica,\n\nHope you're well. Circling back on our discussion regarding the FX hedging strategy for H1 2021.\n\nHas Hasbro made a decision on whether to proceed primarily with forward contracts or incorporate some options for the upcoming period? Happy to provide updated indicative pricing once you have a direction.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
14,2019-11-20 10:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - FX Hedging Strategy - Forwards vs. Options,"Hi Jane,\n\nThis summary is exactly what we needed. Thank you. We'll review this internally and aim to decide on our preferred strategy for H1 2020 hedging shortly. I'll let you know once we're ready to proceed.\n\nRegards,\n\n--\nJessica Palmer\nVP\nHasbro\nEmail: jessica.palmer@hasbro.com\nPhone: 909.878.8329x31984\n"
15,2019-11-18 14:00:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - FX Hedging Strategy - Forwards vs. Options,"Hi Jessica,\n\nThanks for the productive discussion last week comparing FX forward contracts and options for Hasbro's EUR/GBP exposures.\n\nAs requested, I've attached a summary comparing the indicative costs, flexibility, and potential outcomes under different market scenarios for both approaches over a 6-month horizon. This should help in your internal decision-making process.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
16,2018-11-02 14:30:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Hasbro - FX Risk Management for International Sales,"Hi Jessica,\n\nAbsolutely. Discussing the trade-offs between forwards and options would be very productive. How about November 14th at 11 AM ET?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
17,2018-11-02 14:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Jessica Palmer,jessica.palmer@hasbro.com,Re: Hasbro - FX Risk Management for International Sales,"Hi Jane,\n\nThanks for the information. FX volatility is certainly a key concern for us, especially with EUR and GBP. I'd like to understand the costs and flexibility associated with forward contracts versus options. Could we schedule time to discuss this, perhaps mid-November?\n\nRegards,\n\n--\nJessica Palmer\nVP\nHasbro\nEmail: jessica.palmer@hasbro.com\nPhone: 909.878.8329x31984\n"
18,2018-11-01 09:45:00,Jessica Palmer,jessica.palmer@hasbro.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Hasbro - FX Risk Management for International Sales,"Hi Jessica,\n\nFollowing up on our initial conversation, I wanted to provide some information on how Bankwell Financial assists companies like Hasbro in managing foreign exchange risk associated with international sales receivables.\n\nWe offer solutions ranging from simple spot conversions to more structured hedging programs (forwards, options). The attached deck provides an overview. Would you be open to a deeper dive based on Hasbro's specific currency exposures (e.g., EUR, GBP, CAD)?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"

## Guardant Health

In [13]:
df = pd.read_sql("""SELECT email_timestamp
        , to_names	
        , to_emails
        , from_name
        , from_email
        , email_subject
        , email_body
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'roberto.martin@guardanthealth.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'roberto.martin@guardanthealth.com') 
        order by email_timestamp desc
        """, con=engine)
df.head(10)

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2025-06-28 14:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Re: Guardant Health - Social Governance Strategy Benchmarking,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nCan we review ESG fund performance?\n\nThanks,\nRoberto Martin\n\nBest regards,\nRoberto Martin"
1,2025-06-28 14:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Re: Guardant Health - Social Governance Strategy Benchmarking,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nCan we review ESG fund performance?\n\nThanks,\nRoberto Martin\n\nBest regards,\nRoberto Martin"
2,2025-06-28 11:00:00,Roberto Martin,roberto.martin@guardanthealth.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Guardant Health - Social Governance Strategy Benchmarking,"Dear Roberto Martin,\n\nReviewing ESG fund portfolio and benchmark.\n\nBest,\nJane"
3,2025-06-24 09:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Re: Guardant Health - Diversified Fund Comparison Walkthrough,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nLiquidity terms for new funds?\n\nCheers,\nRoberto Martin\n\nBest regards,\nRoberto Martin"
4,2025-06-24 09:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Re: Guardant Health - Diversified Fund Comparison Walkthrough,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nLiquidity terms for new funds?\n\nCheers,\nRoberto Martin\n\nBest regards,\nRoberto Martin"
5,2025-06-23 03:00:00,Roberto Martin,roberto.martin@guardanthealth.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Guardant Health - Diversified Fund Comparison Walkthrough,"Hi Roberto Martin,\n\nLow-volatility fund enhancements.\n\nCheers,\nJane"
6,2025-06-10 08:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Re: Guardant Health - Liquidity Risk & Funding Contingencies,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nAny market risk scenario updates?\n\nCheers,\nRoberto Martin\n\nBest regards,\nRoberto Martin"
7,2025-06-10 08:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Re: Guardant Health - Liquidity Risk & Funding Contingencies,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nAny market risk scenario updates?\n\nCheers,\nRoberto Martin\n\nBest regards,\nRoberto Martin"
8,2025-06-10 05:00:00,Roberto Martin,roberto.martin@guardanthealth.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Guardant Health - Liquidity Risk & Funding Contingencies,"Hello Roberto Martin,\n\nStress testing scenarios walkthrough.\n\nRegards,\nJane"
9,2025-06-09 22:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Roberto Martin,roberto.martin@guardanthealth.com,Re: Guardant Health - Cross-Asset Volatility & Correlation,"Dear Jane,\n\nThank you for your email. Hello Jane,\n\nCommodity price forecasts?\n\nThanks,\nRoberto Martin\n\nBest regards,\nRoberto Martin"

## Lockheed

In [15]:
df2 = pd.read_sql("""SELECT email_timestamp
        , to_names	
        , to_emails
        , from_name
        , from_email
        , email_subject
        , email_body
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'lisa.kennedy@lockheedmartincorporation.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'lisa.kennedy@lockheedmartincorporation.com') 
        order by email_timestamp desc
        """, con=engine)
df2.head(20)

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2023-03-15 14:00:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Lockheed Martin - Inquiry: Bankwell ESG Investment Capabilities,"Hi Lisa,\n\nCertainly. For early April, how about April 4th at 11 AM ET or April 6th at 1 PM ET?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
1,2023-03-15 13:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Lockheed Martin - Inquiry: Bankwell ESG Investment Capabilities,"Hi Jane,\n\nYes, an updated presentation focused on your ESG capabilities would be timely, as our committee continues to evaluate this area. Can you propose some times in early April?\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
2,2023-03-14 11:00:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Lockheed Martin - Inquiry: Bankwell ESG Investment Capabilities,"Hi Lisa,\n\nHope you're well. Following up on our brief discussion last year about ESG considerations in pension management.\n\nBankwell has continued to expand its capabilities in ESG-integrated investment strategies across various asset classes. Would you be open to a brief, updated presentation focused specifically on our ESG offerings for institutional clients like Lockheed Martin's pension plan?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
3,2022-03-09 10:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Lockheed Martin - Update on Interest Rate Environment & LDI,"Hi Jane,\n\nThank you for sharing the update on the rate environment. It's certainly a dynamic period for LDI management. I'll share this with our internal team and consultants.\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
4,2022-03-08 14:30:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Lockheed Martin - Update on Interest Rate Environment & LDI,"Hi Lisa,\n\nGiven the recent significant shifts in the interest rate outlook, I wanted to provide a brief update on the potential implications for pension LDI strategies.\n\nHigher rates can impact funded status and liability valuations. The attached note provides some commentary. Happy to discuss specific implications for Lockheed Martin's plan if helpful, although I know you work with several dedicated managers.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
5,2021-02-12 13:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Lockheed Martin - Economic Update & Pension Trends,"Hi Jane,\n\nThanks for sharing these reports. I'll take a look when I have a moment. ESG is certainly a growing topic of discussion for our committee.\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
6,2021-02-11 11:30:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Lockheed Martin - Economic Update & Pension Trends,"Hi Lisa,\n\nHope you're having a good start to the year. I wanted to share our latest Bankwell economic outlook report and a piece our institutional team put together on recent trends in pension fund management, particularly around ESG considerations and alternative investments.\n\nNo action needed, just thought these might be of interest given your role. Happy to discuss any points if you'd like.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
7,2020-02-19 10:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Follow Up: Lockheed Martin LDI Presentation,"Hi Jane,\n\nThanks for following up. The presentation was informative. We don't have an active LDI manager search at this precise moment, but we've added Bankwell to our list of potential managers for future consideration when the need arises. We appreciate the information shared.\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
8,2020-02-18 14:00:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Follow Up: Lockheed Martin LDI Presentation,"Hi Lisa,\n\nI wanted to follow up after our LDI presentation earlier this month. I hope it provided a helpful overview of Bankwell's capabilities in managing fixed-income strategies for pension plans.\n\nPlease let me know if you or the pension committee have any further questions or if you'd like any additional information as you continue your manager reviews.\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
9,2019-02-06 14:00:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Re: Lockheed Martin - Pension Fund Investment Strategy,"Hi Lisa,\n\nCertainly. How about March 5th at 1 PM ET or March 7th at 10 AM ET for the presentation?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"
10,2019-02-06 11:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Re: Lockheed Martin - Pension Fund Investment Strategy,"Hi Jane,\n\nThank you for following up. LDI is a key focus for our pension committee. We typically engage with managers through formal searches, but I'm open to an introductory presentation on Bankwell's capabilities in this specific area. Can you suggest some times in early March?\n\nRegards,\n\n--\nLisa Kennedy\nSenior Director\nLockheed Martin Corporation\nEmail: lisa.kennedy@lockheedmartincorporation.com\nPhone: +1-341-221-9798x577\n"
11,2019-02-05 09:30:00,Lisa Kennedy,lisa.kennedy@lockheedmartincorporation.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Lockheed Martin - Pension Fund Investment Strategy,"Hi Lisa,\n\nFollowing our introductory discussion regarding Bankwell's institutional asset management capabilities, I wanted to explore further how we might assist with specific segments of Lockheed Martin's pension fund investments.\n\nWe have particular expertise in managing fixed-income mandates focused on liability-driven investing (LDI) principles. Would you be open to a more detailed presentation on our LDI strategies and performance?\n\nBest regards,\n\n--\nJane Moneypenny\nFinancial Advisor\nBankwell Financial\nPhone: (555) 123-4567\nEmail: jane.moneypenny1@outlook.com\n"

## Compass

In [16]:
df = pd.read_sql("""SELECT email_timestamp
        , to_names	
        , to_emails
        , from_name
        , from_email
        , email_subject
        , email_body
        FROM email_data
        WHERE to_emails in ('jane.moneypenny@bankwell.com', 'adam.clay@compass.com') 
        and from_email in ('jane.moneypenny@bankwell.com', 'adam.clay@compass.com') 
        order by email_timestamp desc
        """, con=engine)
df.head(10)

,email_timestamp,to_names,to_emails,from_name,from_email,email_subject,email_body
0,2025-06-16 06:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Re: Compass - AML Requirements & Policy Developments,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nCould you include any upcoming FINRA changes?\n\nBest,\nAdam Clay\n\nBest regards,\nAdam Clay"
1,2025-06-16 06:15:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Re: Compass - AML Requirements & Policy Developments,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nCould you include any upcoming FINRA changes?\n\nBest,\nAdam Clay\n\nBest regards,\nAdam Clay"
2,2025-06-14 20:15:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - AML Requirements & Policy Developments,"Dear Adam Clay,\n\nReminder of our SEC policy briefing. Please share any points you'd like covered.\n\nBest,\nJane"
3,2025-06-11 11:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Re: Compass - Tracking Error & Volatility Shift Study,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nTracking error effects?\n\nCheers,\nAdam Clay\n\nBest regards,\nAdam Clay"
4,2025-06-11 11:45:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Re: Compass - Tracking Error & Volatility Shift Study,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nTracking error effects?\n\nCheers,\nAdam Clay\n\nBest regards,\nAdam Clay"
5,2025-06-11 08:15:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Tracking Error & Volatility Shift Study,"Dear Adam Clay,\n\nSharpe ratio and risk-return effects discussion.\n\nBest,\nJane"
6,2025-06-10 00:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Re: Compass - Geopolitical Risks & Global Supply Effects,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nExpectations on inflation trends?\n\nThanks,\nAdam Clay\n\nBest regards,\nAdam Clay"
7,2025-06-10 00:30:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Re: Compass - Geopolitical Risks & Global Supply Effects,"Dear Jane,\n\nThank you for your email. Hi Jane,\n\nExpectations on inflation trends?\n\nThanks,\nAdam Clay\n\nBest regards,\nAdam Clay"
8,2025-06-09 16:30:00,Adam Clay,adam.clay@compass.com,Jane Moneypenny,jane.moneypenny@bankwell.com,Compass - Geopolitical Risks & Global Supply Effects,"Hello Adam Clay,\n\nFed policy divergence and trajectory review.\n\nRegards,\nJane"
9,2025-05-31 21:00:00,Jane Moneypenny,jane.moneypenny@bankwell.com,Adam Clay,adam.clay@compass.com,Re: Compass - Low-Volatility Fund Enhancements,"Dear Jane,\n\nThank you for your email. Hello Jane,\n\nThematic fund strategy?\n\nThanks,\nAdam Clay\n\nBest regards,\nAdam Clay"